<a href="https://colab.research.google.com/github/tomektom10/dataScienceBootCamp/blob/main/Analiza_danych_Rabina_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import pandas as pd
import numpy as np

In [12]:
df = pd.read_excel("Anal_SK.xlsx", sheet_name="P_1")

In [13]:
df

,Time,Day-ahead price,Imbalance price,Unnamed: 3,P_1,Day-ahead price.1,LONG/SHORT,Profit/loss,Cum. Return,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,01.01.2023 00:00 - 01.01.2023 01:00,20.26,-5.0000,NaN,-7.0835,20.26,SHORT,25.2600,25.2600,NaN,NaN,Max.profit.per.hour:,305.000
1,01.01.2023 01:00 - 01.01.2023 02:00,0.33,-2.2500,NaN,-8.8247,0.33,SHORT,2.5800,27.8400,NaN,NaN,Max.loss.per.hour:,-343.800
2,01.01.2023 02:00 - 01.01.2023 03:00,0.50,-5.0000,NaN,-5.4847,0.50,SHORT,5.5000,33.3400,NaN,NaN,NaN,NaN
3,01.01.2023 03:00 - 01.01.2023 04:00,0.50,-5.0000,NaN,-5.9959,0.50,SHORT,5.5000,38.8400,NaN,NaN,Cum.max.return:,33836.435
4,01.01.2023 04:00 - 01.01.2023 05:00,0.10,-5.0000,NaN,-6.0125,0.10,SHORT,5.1000,43.9400,NaN,NaN,Cum.min.return:,-1896.540
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7458,NaN,NaN,-5.0000,NaN,103.7557,123.10,SHORT,128.1000,33364.4000,12605.1875,NaN,NaN,NaN
7459,NaN,NaN,125.4925,NaN,97.1872,112.66,SHORT,-12.8325,33351.5675,12592.3550,NaN,NaN,NaN
7460,NaN,NaN,161.0000,NaN,87.6755,107.33,SHORT,-53.6700,33297.8975,12538.6850,NaN,NaN,NaN
7461,NaN,NaN,150.2100,NaN,84.3187,100.14,SHORT,-50.0700,33247.8275,12488.6150,NaN,NaN,NaN
7462,NaN,NaN,63.5150,NaN,75.2063,88.02,SHORT,24.5050,33272.3325,12513.1200,NaN,NaN,NaN

In [14]:
wybrane_kolumny = df[['LONG/SHORT', 'Profit/loss']]

In [15]:
wybrane_kolumny

     LONG/SHORT  Profit/loss
0         SHORT      25.2600
1         SHORT       2.5800
2         SHORT       5.5000
3         SHORT       5.5000
4         SHORT       5.1000
...         ...          ...
7458      SHORT     128.1000
7459      SHORT     -12.8325
7460      SHORT     -53.6700
7461      SHORT     -50.0700
7462      SHORT      24.5050

[7463 rows x 2 columns]

In [16]:
suma_wartosci_Profit = df['Profit/loss'].sum()

In [17]:
df.groupby("LONG/SHORT")["Profit/loss"].mean()

LONG/SHORT
LONG     -6.307024
SHORT    16.933258
Name: Profit/loss, dtype: float64

In [18]:
long_data = wybrane_kolumny[wybrane_kolumny['LONG/SHORT'] == 'LONG']

In [19]:
print(long_data)

     LONG/SHORT  Profit/loss
9          LONG      -6.1900
10         LONG      -6.9100
11         LONG      -7.7400
12         LONG      -7.7900
13         LONG      -7.7575
...         ...          ...
7428       LONG      44.2000
7437       LONG     -24.5950
7438       LONG      10.4000
7449       LONG     -24.1300
7450       LONG     -57.7050

[4006 rows x 2 columns]

In [20]:
suma_wartosci_long =long_data["Profit/loss"].sum()

In [ ]:
# GRANIE TYLKO LONG

In [21]:
print(suma_wartosci_long)

-25265.94

In [22]:
szort_data = wybrane_kolumny[wybrane_kolumny['LONG/SHORT'] == 'SHORT']

In [23]:
print(szort_data)

     LONG/SHORT  Profit/loss
0         SHORT      25.2600
1         SHORT       2.5800
2         SHORT       5.5000
3         SHORT       5.5000
4         SHORT       5.1000
...         ...          ...
7458      SHORT     128.1000
7459      SHORT     -12.8325
7460      SHORT     -53.6700
7461      SHORT     -50.0700
7462      SHORT      24.5050

[3457 rows x 2 columns]

In [24]:
suma_wartosci_szort =szort_data["Profit/loss"].sum()

In [ ]:
#GRANIE TYLKO SZORT

In [25]:
print(suma_wartosci_szort)

58538.27250000001

In [26]:
df

,Time,Day-ahead price,Imbalance price,Unnamed: 3,P_1,Day-ahead price.1,LONG/SHORT,Profit/loss,Cum. Return,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,01.01.2023 00:00 - 01.01.2023 01:00,20.26,-5.0000,NaN,-7.0835,20.26,SHORT,25.2600,25.2600,NaN,NaN,Max.profit.per.hour:,305.000
1,01.01.2023 01:00 - 01.01.2023 02:00,0.33,-2.2500,NaN,-8.8247,0.33,SHORT,2.5800,27.8400,NaN,NaN,Max.loss.per.hour:,-343.800
2,01.01.2023 02:00 - 01.01.2023 03:00,0.50,-5.0000,NaN,-5.4847,0.50,SHORT,5.5000,33.3400,NaN,NaN,NaN,NaN
3,01.01.2023 03:00 - 01.01.2023 04:00,0.50,-5.0000,NaN,-5.9959,0.50,SHORT,5.5000,38.8400,NaN,NaN,Cum.max.return:,33836.435
4,01.01.2023 04:00 - 01.01.2023 05:00,0.10,-5.0000,NaN,-6.0125,0.10,SHORT,5.1000,43.9400,NaN,NaN,Cum.min.return:,-1896.540
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7458,NaN,NaN,-5.0000,NaN,103.7557,123.10,SHORT,128.1000,33364.4000,12605.1875,NaN,NaN,NaN
7459,NaN,NaN,125.4925,NaN,97.1872,112.66,SHORT,-12.8325,33351.5675,12592.3550,NaN,NaN,NaN
7460,NaN,NaN,161.0000,NaN,87.6755,107.33,SHORT,-53.6700,33297.8975,12538.6850,NaN,NaN,NaN
7461,NaN,NaN,150.2100,NaN,84.3187,100.14,SHORT,-50.0700,33247.8275,12488.6150,NaN,NaN,NaN
7462,NaN,NaN,63.5150,NaN,75.2063,88.02,SHORT,24.5050,33272.3325,12513.1200,NaN,NaN,NaN