<a href="https://colab.research.google.com/github/tomektom10/dataScienceBootCamp/blob/main/ENERGIA_2024_OBLICZENIA_DLA_GODZIN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("Total_results_statystyka_024-01-01_2024-01-23.xlsx")

In [3]:
df.columns

Index(['Delivery day', 'Period', 'DA price', 'Bilans', 'Price Average ',
       'Weighted average price ', 'Minimal price', 'Maximal price ',
       'Last price '],
      dtype='object')

In [4]:
# Dodanie kolumny 'Profit/Loss', która oblicza zysk lub stratę na podstawie 'DA price' i 'Bilans'
df['Profit_Loss'] = df['Bilans'] - df['DA price']
df  # Wyświetlenie pierwszych kilku wierszy zaktualizowanego DataFrame

,Delivery day,Period,DA price,Bilans,Price Average,Weighted average price,Minimal price,Maximal price,Last price,Profit_Loss
0,2024-01-01,1,0.10,-5.0000,3.14,4.09,0.80,5.00,4.50,-5.1000
1,2024-01-01,2,0.01,29.2500,3.75,6.11,-2.51,20.18,2.18,29.2400
2,2024-01-01,3,0.05,-5.0000,4.21,7.00,-1.28,26.12,2.11,-5.0500
3,2024-01-01,4,0.01,-5.0000,4.15,2.13,-0.50,7.21,4.59,-5.0100
4,2024-01-01,5,0.01,-4.4975,3.73,2.89,-0.50,8.49,6.01,-4.5075
...,...,...,...,...,...,...,...,...,...,...
547,2024-01-23,20,99.78,137.1900,112.37,116.05,93.10,130.60,130.60,37.4100
548,2024-01-23,21,95.43,65.1750,90.82,98.89,81.51,125.85,84.00,-30.2550
549,2024-01-23,22,82.13,92.9750,81.45,86.23,70.00,107.29,76.00,10.8450
550,2024-01-23,23,73.50,97.7500,82.49,85.01,73.50,95.48,73.50,24.2500
551,2024-01-23,24,50.13,97.7500,61.41,59.24,56.00,69.90,69.90,47.6200

In [5]:

# Grupowanie danych wg 'Period' i obliczanie średniej, min, max dla 'DA price'
grouped = df.groupby('Period')['DA price'].agg(['mean', 'min', 'max'])

print(grouped)

# WARTOSCI DLA GODZIN Z ROKU 2024

              mean    min     max
Period
1        69.163478   0.10   91.75
2        65.901739   0.01   88.59
3        63.805652   0.05   87.25
4        60.429130   0.01   85.86
5        61.465217   0.01   88.47
6        68.241304   0.01   95.18
7        81.709565   0.04  111.24
8        93.431739   0.01  129.67
9       100.577826   0.00  144.11
10       96.723913   0.04  138.60
11       90.863043   0.06  122.01
12       86.987391   0.54  116.09
13       82.920435   2.24  115.40
14       83.813478   3.44  118.35
15       88.966087  11.18  122.06
16       97.063043  43.85  134.79
17      107.084783  55.61  143.59
18      110.689130  63.03  147.93
19      108.420870  61.39  140.00
20      104.658261  54.94  132.31
21       97.646522  48.40  125.75
22       86.694783  40.46  112.36
23       82.826957  40.93  105.68
24       74.345217  25.28   96.69

In [6]:


# Grupowanie danych wg 'Period' i obliczanie średniej, min, max dla 'DA price' oraz sumy dla 'Bilans'
grouped1 = df.groupby('Period').agg({'DA price': ['mean', 'min', 'max'], 'Bilans': 'mean'})

print(grouped1)

# DOŁOŻYŁEM JESZCZE  BILANS SREDNIA ZE WSZYSTKICH DNI

          DA price                    Bilans
              mean    min     max       mean
Period
1        69.163478   0.10   91.75  43.104891
2        65.901739   0.01   88.59  48.682826
3        63.805652   0.05   87.25  45.861630
4        60.429130   0.01   85.86  53.102707
5        61.465217   0.01   88.47  51.568783
6        68.241304   0.01   95.18  59.139130
7        81.709565   0.04  111.24  71.573478
8        93.431739   0.01  129.67  73.543293
9       100.577826   0.00  144.11  71.099076
10       96.723913   0.04  138.60  75.147000
11       90.863043   0.06  122.01  54.985000
12       86.987391   0.54  116.09  81.191891
13       82.920435   2.24  115.40  75.900457
14       83.813478   3.44  118.35  70.378370
15       88.966087  11.18  122.06  80.128489
16       97.063043  43.85  134.79  75.068793
17      107.084783  55.61  143.59  84.329641
18      110.689130  63.03  147.93  87.364663
19      108.420870  61.39  140.00  81.489783
20      104.658261  54.94  132.31  86.291304
21       97.646522  48.40  125.75  74.617554
22       86.694783  40.46  112.36  71.550370
23       82.826957  40.93  105.68  76.587457
24       74.345217  25.28   96.69  68.293348

In [7]:
# Obliczenie łącznego wyniku dla 'Profit/Loss' dla poszczególnych okresów z kolumny 'Period'
total_profit_loss_by_period = df.groupby('Period')['Profit_Loss'].sum()

total_profit_loss_by_period.head  # Wyświetlenie pierwszych kilku wyników
# ZYSKI/STRATY ŁĄCZNIE DLA POSZCZEGULNYCH GODZIN

<bound method NDFrame.head of Period
1    -599.34750
2    -396.03500
3    -412.71250
4    -168.50775
5    -227.61800
6    -209.35000
7    -233.13000
8    -457.43425
9    -678.01125
10   -496.26900
11   -825.19500
12   -133.29650
13   -161.45950
14   -309.00750
15   -203.26475
16   -505.86775
17   -523.36825
18   -536.46275
19   -619.41500
20   -422.44000
21   -529.66625
22   -348.32150
23   -143.50850
24   -139.19300
Name: Profit_Loss, dtype: float64>

In [8]:
################    NOWE  #########

In [9]:
df

,Delivery day,Period,DA price,Bilans,Price Average,Weighted average price,Minimal price,Maximal price,Last price,Profit_Loss
0,2024-01-01,1,0.10,-5.0000,3.14,4.09,0.80,5.00,4.50,-5.1000
1,2024-01-01,2,0.01,29.2500,3.75,6.11,-2.51,20.18,2.18,29.2400
2,2024-01-01,3,0.05,-5.0000,4.21,7.00,-1.28,26.12,2.11,-5.0500
3,2024-01-01,4,0.01,-5.0000,4.15,2.13,-0.50,7.21,4.59,-5.0100
4,2024-01-01,5,0.01,-4.4975,3.73,2.89,-0.50,8.49,6.01,-4.5075
...,...,...,...,...,...,...,...,...,...,...
547,2024-01-23,20,99.78,137.1900,112.37,116.05,93.10,130.60,130.60,37.4100
548,2024-01-23,21,95.43,65.1750,90.82,98.89,81.51,125.85,84.00,-30.2550
549,2024-01-23,22,82.13,92.9750,81.45,86.23,70.00,107.29,76.00,10.8450
550,2024-01-23,23,73.50,97.7500,82.49,85.01,73.50,95.48,73.50,24.2500
551,2024-01-23,24,50.13,97.7500,61.41,59.24,56.00,69.90,69.90,47.6200

In [10]:
# Wybór danych tylko dla okresu 1 OKRES 1
df_period_1 = df[df['Period'] == 1]

df_period_1.head(5)  # Wyświetlenie wyników dla okresu 1

,Delivery day,Period,DA price,Bilans,Price Average,Weighted average price,Minimal price,Maximal price,Last price,Profit_Loss
0,2024-01-01,1,0.10,-5.0000,3.14,4.09,0.80,5.00,4.50,-5.1000
24,2024-01-02,1,29.71,-5.0000,16.80,19.51,4.11,40.95,30.00,-34.7100
48,2024-01-03,1,21.93,30.7575,19.82,22.85,8.86,49.99,35.12,8.8275
72,2024-01-04,1,57.30,29.2500,60.92,65.05,52.81,78.45,78.45,-28.0500
96,2024-01-05,1,86.08,97.5025,78.44,75.27,50.14,102.54,50.14,11.4225

In [11]:
# Wybór danych tylko dla okresu 1
df_period_1 = df[df['Period'] == 1]

# Liczenie ile razy wystąpił zysk (Profit/Loss > 0) dla okresu 1
profit_count = df_period_1[df_period_1['Profit_Loss'] > 0].shape[0]

profit_count
# 7 razy zysk z longa dla okresu 1 na 23

7

In [12]:
length = len(df_period_1)
length

23

In [13]:
# Liczenie, ile razy 'Price Average' było większe od 'DA price' dla każdego okresu
count_higher_average_price = df[df['Price Average '] > df['DA price']].groupby('Period').size()

count_higher_average_price.head(24)  # Wyświetlenie wyników dla pierwszych kilku okresów

# TYLE RAZY DLA POSZCZEGULNYCH GODZIN CENA SREDNIA BYLA WYZSZA OD DA

Period
1      9
2     10
3     12
4     14
5     12
6     13
7     13
8     17
9     16
10    15
11    16
12    17
13    14
14    15
15    12
16    15
17     9
18    11
19    11
20    11
21    11
22    14
23     9
24    13
dtype: int64

In [14]:
# Liczenie, ile razy 'Maximal price' było wyższe od 'DA price' o 5 dla każdego okresu
count_higher_maximal_price = df[df['Maximal price '] > df['DA price'] + 5].groupby('Period').size()

count_higher_maximal_price.head(24)  # Wyświetlenie wyników dla pierwszych kilku okresów

# TYLE RAZY MAXYMALAN CENA BYŁA WYZSZA OD DA O 5

Period
1     21
2     14
3     14
4     17
5     16
6     20
7     21
8     22
9     21
10    23
11    22
12    22
13    23
14    22
15    23
16    22
17    18
18    20
19    22
20    21
21    22
22    21
23    18
24    22
dtype: int64

In [15]:
# Wybór wierszy, w których 'Profit_Loss' jest na plusie (większy od 0)
df_profit_positive = df[df['Profit_Loss'] > 0]

df_profit_positive.head(50)  # Wyświetlenie pierwszych kilku wierszy df_profit_positive

,Delivery day,Period,DA price,Bilans,Price Average,Weighted average price,Minimal price,Maximal price,Last price,Profit_Loss
1,2024-01-01,2,0.01,29.25000,3.75,6.11,-2.51,20.18,2.18,29.24000
11,2024-01-01,12,0.54,29.25000,2.60,4.17,-3.10,14.00,1.00,28.71000
13,2024-01-01,14,3.44,63.50000,1.45,4.23,-5.20,13.41,12.22,60.06000
14,2024-01-01,15,11.18,97.75000,2.65,4.81,-5.00,28.50,17.23,86.57000
15,2024-01-01,16,43.85,97.75000,53.86,49.75,25.00,75.00,25.00,53.90000
22,2024-01-01,23,44.59,130.74750,36.45,36.30,20.29,53.43,20.75,86.15750
32,2024-01-02,9,80.12,99.09900,61.69,62.08,40.84,93.22,40.89,18.97900
33,2024-01-02,10,78.46,86.30600,68.15,65.41,41.02,92.33,41.77,7.84600
35,2024-01-02,12,79.66,87.62600,83.82,86.16,75.00,105.88,85.00,7.96600
36,2024-01-02,13,81.93,90.12300,88.74,90.54,76.63,112.28,112.08,8.19300
37,2024-01-02,14,83.02,130.50000,85.98,89.98,78.01,120.28,78.01,47.48000
38,2024-01-02,15,85.98,94.57800,86.54,89.25,74.24,113.45,113.15,8.59800
39,2024-01-02,16,87.67,96.43700,91.59,93.44,79.92,113.99,113.34,8.76700
40,2024-01-02,17,90.19,107.40675,83.49,90.38,75.16,120.22,120.03,17.21675
44,2024-01-02,21,60.22,64.87100,57.27,55.98,38.23,70.34,38.89,4.65100
45,2024-01-02,22,48.02,58.16100,53.82,54.68,44.00,64.29,64.19,10.14100
46,2024-01-02,23,40.93,54.26150,50.97,55.05,41.54,72.33,72.11,13.33150
47,2024-01-02,24,25.28,37.45200,37.61,42.71,20.69,67.88,67.88,12.17200
48,2024-01-03,1,21.93,30.75750,19.82,22.85,8.86,49.99,35.12,8.82750
49,2024-01-03,2,20.69,28.24750,15.20,14.55,10.00,25.00,11.42,7.55750
50,2024-01-03,3,19.77,29.25000,20.51,18.62,10.00,29.24,29.22,9.48000
53,2024-01-03,6,22.82,29.25000,14.59,12.77,4.50,25.00,13.20,6.43000
60,2024-01-03,13,57.39,125.25000,58.51,56.35,35.23,76.05,35.67,67.86000
61,2024-01-03,14,57.08,91.00000,59.84,59.96,35.11,81.34,55.00,33.92000
64,2024-01-03,17,80.59,91.00000,74.99,74.71,50.13,95.38,50.13,10.41000
68,2024-01-03,21,73.23,127.50000,74.58,71.84,48.27,83.40,48.27,54.27000
73,2024-01-04,2,50.46,62.75000,45.74,43.57,40.57,51.94,45.12,12.29000
78,2024-01-04,7,72.65,132.00000,66.62,66.96,62.85,73.74,69.80,59.35000
79,2024-01-04,8,85.02,96.12500,84.66,77.37,50.39,86.80,50.39,11.10500
83,2024-01-04,12,90.76,97.75000,86.42,86.57,50.27,95.00,50.88,6.99000
87,2024-01-04,16,98.62,102.92025,95.70,93.03,56.88,103.80,56.99,4.30025
88,2024-01-04,17,104.74,109.34750,98.52,96.40,54.49,107.21,54.88,4.60750
89,2024-01-04,18,115.23,119.53500,127.85,129.47,112.69,167.88,167.88,4.30500
90,2024-01-04,19,118.06,162.82000,139.25,140.38,123.25,174.89,174.89,44.76000
91,2024-01-04,20,112.32,113.00000,120.30,120.84,110.00,155.12,155.12,0.68000
92,2024-01-04,21,101.41,141.97025,100.49,104.86,88.45,140.19,88.45,40.56025
93,2024-01-04,22,95.75,132.52000,91.10,93.09,77.22,126.44,126.14,36.77000
96,2024-01-05,1,86.08,97.50250,78.44,75.27,50.14,102.54,50.14,11.42250
100,2024-01-05,5,73.18,96.00200,69.85,69.32,66.00,73.53,69.98,22.82200
107,2024-01-05,12,98.58,101.40250,88.85,88.47,60.23,111.39,60.24,2.82250
108,2024-01-05,13,97.94,136.33250,86.22,85.38,55.87,108.89,70.23,38.39250
109,2024-01-05,14,104.58,143.00000,89.75,86.62,60.34,109.78,89.00,38.42000
110,2024-01-05,15,112.34,155.63500,99.14,103.96,70.00,145.89,95.00,43.29500
111,2024-01-05,16,113.91,159.47000,106.56,110.54,96.00,150.11,150.11,45.56000
114,2024-01-05,19,113.27,153.25000,106.98,111.80,97.40,148.99,148.99,39.98000
115,2024-01-05,20,110.70,151.00000,101.01,103.49,90.00,125.34,125.34,40.30000
118,2024-01-05,23,94.92,95.50000,93.86,97.01,86.42,124.87,124.87,0.58000
119,2024-01-05,24,86.80,96.25000,86.99,90.34,80.81,115.34,90.00,9.45000
120,2024-01-06,1,82.25,131.25000,86.96,91.38,47.22,108.22,108.01,49.00000
121,2024-01-06,2,80.20,131.25000,83.52,83.11,80.23,89.54,89.54,51.05000

In [16]:
# Liczenie ile razy 'Maximal price' było wyższe od 'Bilans'
count_maximal_price_higher_than_bilans = df_profit_positive[df_profit_positive['Maximal price '] > df_profit_positive['Bilans']].shape[0]

count_maximal_price_higher_than_bilans

91

In [17]:
length1 = len(df_profit_positive)
length1

236

In [18]:
df

,Delivery day,Period,DA price,Bilans,Price Average,Weighted average price,Minimal price,Maximal price,Last price,Profit_Loss
0,2024-01-01,1,0.10,-5.0000,3.14,4.09,0.80,5.00,4.50,-5.1000
1,2024-01-01,2,0.01,29.2500,3.75,6.11,-2.51,20.18,2.18,29.2400
2,2024-01-01,3,0.05,-5.0000,4.21,7.00,-1.28,26.12,2.11,-5.0500
3,2024-01-01,4,0.01,-5.0000,4.15,2.13,-0.50,7.21,4.59,-5.0100
4,2024-01-01,5,0.01,-4.4975,3.73,2.89,-0.50,8.49,6.01,-4.5075
...,...,...,...,...,...,...,...,...,...,...
547,2024-01-23,20,99.78,137.1900,112.37,116.05,93.10,130.60,130.60,37.4100
548,2024-01-23,21,95.43,65.1750,90.82,98.89,81.51,125.85,84.00,-30.2550
549,2024-01-23,22,82.13,92.9750,81.45,86.23,70.00,107.29,76.00,10.8450
550,2024-01-23,23,73.50,97.7500,82.49,85.01,73.50,95.48,73.50,24.2500
551,2024-01-23,24,50.13,97.7500,61.41,59.24,56.00,69.90,69.90,47.6200

In [19]:
df.columns

Index(['Delivery day', 'Period', 'DA price', 'Bilans', 'Price Average ',
       'Weighted average price ', 'Minimal price', 'Maximal price ',
       'Last price ', 'Profit_Loss'],
      dtype='object')

In [20]:
# Obliczanie różnic między 'DA price' i 'Maximal price'
df['Difference_max'] = df['Maximal price '] - df['DA price']

# Sortowanie danych według największych różnic i wybranie 10 pierwszych
top_10_differences = df.sort_values(by='Difference_max', ascending=False).head(15)

top_10_differences  # Wyświetlenie wyników

## 10 NAJWIKESZYCH RÓŻNIC MIEZDZY MAX A CENA DA

,Delivery day,Period,DA price,Bilans,Price Average,Weighted average price,Minimal price,Maximal price,Last price,Profit_Loss,Difference_max
189,2024-01-08,22,102.80,112.85500,139.42,136.05,100.00,230.70,105.33,10.05500,127.90
513,2024-01-22,10,101.04,102.59000,124.40,127.51,90.94,210.00,95.12,1.55000,108.96
233,2024-01-10,18,143.79,143.07500,178.54,179.46,116.11,230.00,116.11,-0.71500,86.21
235,2024-01-10,20,132.15,137.50500,169.80,173.52,130.00,217.08,130.00,5.35500,84.93
226,2024-01-10,11,119.49,-0.90000,150.73,150.76,96.37,200.00,150.00,-120.39000,80.51
200,2024-01-09,9,132.94,136.27750,162.17,155.57,120.29,207.70,120.29,3.33750,74.76
180,2024-01-08,13,95.48,145.20000,130.49,132.48,95.00,169.99,150.00,49.72000,74.51
546,2024-01-23,19,90.00,97.50000,136.01,135.98,100.12,162.00,125.87,7.50000,72.00
234,2024-01-10,19,140.00,95.49750,170.10,172.06,112.84,211.65,140.00,-44.50250,71.65
187,2024-01-08,20,122.05,170.86750,155.41,158.30,127.81,191.34,150.00,48.81750,69.29
185,2024-01-08,18,130.83,175.50000,162.55,162.07,126.69,200.00,200.00,44.67000,69.17
393,2024-01-17,10,105.50,109.62500,126.14,128.60,84.40,174.57,162.47,4.12500,69.07
446,2024-01-19,15,76.09,32.18225,94.99,93.94,76.09,145.10,145.10,-43.90775,69.01
188,2024-01-08,21,114.19,162.71500,149.83,149.09,129.98,181.79,181.79,48.52500,67.60
202,2024-01-09,11,112.46,37.73500,118.41,121.37,108.49,180.00,180.00,-74.72500,67.54

In [21]:
df_profit_positive

,Delivery day,Period,DA price,Bilans,Price Average,Weighted average price,Minimal price,Maximal price,Last price,Profit_Loss
1,2024-01-01,2,0.01,29.250,3.75,6.11,-2.51,20.18,2.18,29.240
11,2024-01-01,12,0.54,29.250,2.60,4.17,-3.10,14.00,1.00,28.710
13,2024-01-01,14,3.44,63.500,1.45,4.23,-5.20,13.41,12.22,60.060
14,2024-01-01,15,11.18,97.750,2.65,4.81,-5.00,28.50,17.23,86.570
15,2024-01-01,16,43.85,97.750,53.86,49.75,25.00,75.00,25.00,53.900
...,...,...,...,...,...,...,...,...,...,...
546,2024-01-23,19,90.00,97.500,136.01,135.98,100.12,162.00,125.87,7.500
547,2024-01-23,20,99.78,137.190,112.37,116.05,93.10,130.60,130.60,37.410
549,2024-01-23,22,82.13,92.975,81.45,86.23,70.00,107.29,76.00,10.845
550,2024-01-23,23,73.50,97.750,82.49,85.01,73.50,95.48,73.50,24.250
551,2024-01-23,24,50.13,97.750,61.41,59.24,56.00,69.90,69.90,47.620

In [23]:
######## OD TEGO MOMENTU LICZE CZY USREDNIANIE MA SENS.  PONIZEJ WARTOŚCI O ILE SREDNIO CENA MAX BYŁA WIEKSZA OD DA DLA POSZCZEGULNYCH OKRESÓW

# Calculating the average difference between Maximal Price and DA Price for each Period
average_difference_by_period = df_profit_positive.groupby('Period').apply(lambda x: (x['Maximal price '] - x['DA price']).mean())
average_difference_by_period

Period
1     18.892857
2      8.097778
3     15.135556
4     19.961111
5     11.692222
6      8.648571
7     14.660000
8     36.168889
9     33.710000
10    37.388333
11    28.065714
12    30.720714
13    28.529167
14    31.213333
15    33.664615
16    31.005000
17    30.586000
18    38.888571
19    35.920000
20    34.142727
21    24.007500
22    31.547273
23    19.149167
24    21.123333
dtype: float64

In [27]:
# Mapowanie wartości dodatkowych do okresów
additional_values_map = {
    1: 18.892857,
    2: 8.097778,
    3: 15.135556,
    4: 19.961111,
    5: 11.692222,
    6: 8.648571,
    7: 14.660000,
    8: 36.168889,
    9: 33.710000,
    10: 37.388333,
    11: 28.065714,
    12: 30.720714,
    13: 28.529167,
    14: 31.213333,
    15: 33.664615,
    16: 31.005000,
    17: 30.586000,
    18: 38.888571,
    19: 35.920000,
    20: 34.142727,
    21: 24.007500,
    22: 31.547273,
    23: 19.149167,
    24: 21.123333
}

# Dodawanie nowej kolumny do DataFrame
df_profit_positive['DA_plus_srednia_cena_max'] = df_profit_positive.apply(lambda x: x['DA price'] + additional_values_map.get(x['Period'], 0), axis=1)
df_profit_positive
######## DODAŁEM NOWĄ KOLUMNE GDZIE DO CENY DA DODAŁEM WARTOSCI WYZEJ

<ipython-input-27-3ab82535c68d>:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_profit_positive['DA_plus_srednia_cena_max'] = df_profit_positive.apply(lambda x: x['DA price'] + additional_values_map.get(x['Period'], 0), axis=1)

,Delivery day,Period,DA price,Bilans,Price Average,Weighted average price,Minimal price,Maximal price,Last price,Profit_Loss,DA + średnia,DA_plus_srednia_cena_max
1,2024-01-01,2,0.01,29.250,3.75,6.11,-2.51,20.18,2.18,29.240,8.107778,8.107778
11,2024-01-01,12,0.54,29.250,2.60,4.17,-3.10,14.00,1.00,28.710,31.260714,31.260714
13,2024-01-01,14,3.44,63.500,1.45,4.23,-5.20,13.41,12.22,60.060,34.653333,34.653333
14,2024-01-01,15,11.18,97.750,2.65,4.81,-5.00,28.50,17.23,86.570,44.844615,44.844615
15,2024-01-01,16,43.85,97.750,53.86,49.75,25.00,75.00,25.00,53.900,74.855000,74.855000
...,...,...,...,...,...,...,...,...,...,...,...,...
546,2024-01-23,19,90.00,97.500,136.01,135.98,100.12,162.00,125.87,7.500,125.920000,125.920000
547,2024-01-23,20,99.78,137.190,112.37,116.05,93.10,130.60,130.60,37.410,133.922727,133.922727
549,2024-01-23,22,82.13,92.975,81.45,86.23,70.00,107.29,76.00,10.845,113.677273,113.677273
550,2024-01-23,23,73.50,97.750,82.49,85.01,73.50,95.48,73.50,24.250,92.649167,92.649167
551,2024-01-23,24,50.13,97.750,61.41,59.24,56.00,69.90,69.90,47.620,71.253333,71.253333

In [28]:
df_profit_positive['Profit_Loss_po_dodaniu'] = df_profit_positive['Bilans'] - df_profit_positive['DA_plus_srednia_cena_max']

<ipython-input-28-a64f089fc5a4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_profit_positive['Profit_Loss_po_dodaniu'] = df_profit_positive['Bilans'] - df_profit_positive['DA_plus_srednia_cena_max']

In [ ]:
###### ZOBACZYŁEM JAKI BYL ZYSK/STRATA JAKBYSMY KUPOWALI NIE PO CENIE DA ALE ZNACZNIE WYZEJ BO PO DA PLUS SREDNIA WARTOŚĆ MAX

In [29]:
df_profit_positive

,Delivery day,Period,DA price,Bilans,Price Average,Weighted average price,Minimal price,Maximal price,Last price,Profit_Loss,DA + średnia,DA_plus_srednia_cena_max,Profit_Loss_po_dodaniu
1,2024-01-01,2,0.01,29.250,3.75,6.11,-2.51,20.18,2.18,29.240,8.107778,8.107778,21.142222
11,2024-01-01,12,0.54,29.250,2.60,4.17,-3.10,14.00,1.00,28.710,31.260714,31.260714,-2.010714
13,2024-01-01,14,3.44,63.500,1.45,4.23,-5.20,13.41,12.22,60.060,34.653333,34.653333,28.846667
14,2024-01-01,15,11.18,97.750,2.65,4.81,-5.00,28.50,17.23,86.570,44.844615,44.844615,52.905385
15,2024-01-01,16,43.85,97.750,53.86,49.75,25.00,75.00,25.00,53.900,74.855000,74.855000,22.895000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
546,2024-01-23,19,90.00,97.500,136.01,135.98,100.12,162.00,125.87,7.500,125.920000,125.920000,-28.420000
547,2024-01-23,20,99.78,137.190,112.37,116.05,93.10,130.60,130.60,37.410,133.922727,133.922727,3.267273
549,2024-01-23,22,82.13,92.975,81.45,86.23,70.00,107.29,76.00,10.845,113.677273,113.677273,-20.702273
550,2024-01-23,23,73.50,97.750,82.49,85.01,73.50,95.48,73.50,24.250,92.649167,92.649167,5.100833
551,2024-01-23,24,50.13,97.750,61.41,59.24,56.00,69.90,69.90,47.620,71.253333,71.253333,26.496667

In [30]:
total_po_dodaniu = df_profit_positive['Profit_Loss_po_dodaniu'].sum()

In [ ]:
##### MIMO WSZYSTKO ZE KUPOWALISMY PO CENIE WYZSZEJ NIZ DA TO I TAK BYL ZYKS. TO WEDLUG MNEI ZNACYZ ZE JAK IDA LONGIEM TO NIE OPLACA SIE USREDNIAC

In [31]:
total_po_dodaniu

1117.0862679999998