<a href="https://colab.research.google.com/github/tomektom10/dataScienceBootCamp/blob/main/ENERGIA_anal_szczegolowe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel("kkkkkkkk.xlsx")

In [ ]:
df['Profit_Loss'] = df['Bilans'] - df['Price SK (EUR/MWh)']

df

,Delivery day,Period number,Period,Traded Price Average (EUR/MWh),Weighted average price of all trades (EUR/MWh),Minimal price (EUR/MWh),Maximal price (EUR/MWh),Last price (EUR/MWh),Bilans,Price SK (EUR/MWh),Unnamed: 10,Unnamed: 11,Profit_Loss
0,2023-01-01,1.0,00:00 - 01:00,19.40,18.93,7.00,30.26,19.00,-5.0000,20.26,NaN,NaN,-25.2600
1,2023-01-01,2.0,01:00 - 02:00,3.07,1.35,0.30,10.33,0.30,-2.2525,0.33,NaN,NaN,-2.5825
2,2023-01-01,3.0,02:00 - 03:00,4.18,2.05,0.50,10.50,0.50,-5.0000,0.50,NaN,NaN,-5.5000
3,2023-01-01,4.0,03:00 - 04:00,4.40,2.26,0.00,10.50,0.00,-5.0000,0.50,NaN,NaN,-5.5000
4,2023-01-01,5.0,04:00 - 05:00,5.08,3.12,0.00,10.10,0.00,-5.0000,0.10,NaN,NaN,-5.1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8756,2023-12-31,21.0,20:00 - 21:00,26.51,27.36,14.23,48.00,15.00,-5.0000,24.04,NaN,NaN,-29.0400
8757,2023-12-31,22.0,21:00 - 22:00,17.22,18.78,3.87,45.00,5.00,-5.0000,9.85,NaN,NaN,-14.8500
8758,2023-12-31,23.0,22:00 - 23:00,16.81,19.80,4.23,55.00,5.00,-5.0000,10.68,NaN,NaN,-15.6800
8759,2023-12-31,24.0,23:00 - 00:00,13.72,18.38,6.64,35.11,8.59,-5.0000,15.11,NaN,NaN,-20.1100
8760,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96660.676,NaN

In [ ]:
from io import StringIO



# Konwersja kolumny 'Delivery day' do formatu daty
df['Delivery day'] = pd.to_datetime(df['Delivery day'])

# Wyodrębnienie danych za styczeń 2023
df_january = df[df['Delivery day'].dt.month == 1]

df_january

,Delivery day,Period number,Period,Traded Price Average (EUR/MWh),Weighted average price of all trades (EUR/MWh),Minimal price (EUR/MWh),Maximal price (EUR/MWh),Last price (EUR/MWh),Bilans,Price SK (EUR/MWh),Unnamed: 10,Unnamed: 11,Profit_Loss
0,2023-01-01,1.0,00:00 - 01:00,19.40,18.93,7.00,30.26,19.00,-5.00000,20.26,NaN,NaN,-25.26000
1,2023-01-01,2.0,01:00 - 02:00,3.07,1.35,0.30,10.33,0.30,-2.25250,0.33,NaN,NaN,-2.58250
2,2023-01-01,3.0,02:00 - 03:00,4.18,2.05,0.50,10.50,0.50,-5.00000,0.50,NaN,NaN,-5.50000
3,2023-01-01,4.0,03:00 - 04:00,4.40,2.26,0.00,10.50,0.00,-5.00000,0.50,NaN,NaN,-5.50000
4,2023-01-01,5.0,04:00 - 05:00,5.08,3.12,0.00,10.10,0.00,-5.00000,0.10,NaN,NaN,-5.10000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,2023-01-31,20.0,19:00 - 20:00,190.65,190.90,176.01,224.00,200.00,248.93875,222.39,NaN,NaN,26.54875
740,2023-01-31,21.0,20:00 - 21:00,168.67,167.40,155.00,190.19,165.60,202.19500,180.84,NaN,NaN,21.35500
741,2023-01-31,22.0,21:00 - 22:00,146.73,147.35,130.04,154.05,148.08,108.34250,147.79,NaN,NaN,-39.44750
742,2023-01-31,23.0,22:00 - 23:00,134.57,136.34,111.00,151.71,125.48,132.36625,118.77,NaN,NaN,13.59625
743,2023-01-31,24.0,23:00 - 00:00,105.93,105.95,88.00,115.92,100.01,104.54500,94.04,NaN,NaN,10.50500

In [ ]:
zyski_strata_styczen = df_january['Profit_Loss'].sum()
zyski_strata_styczen
# ZYSKI STRATA STYCZEN

-1956.3594999999996

In [ ]:


# Filtering rows where 'Price SK' is between 0 and 50
od0_do50_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 0) & (df['Price SK (EUR/MWh)'] <= 50)]

# Calculating the total Profit/Loss for these rows
total_profit_loss = od0_do50_df['Profit_Loss'].sum()
total_profit_loss
# PRZEDZIAL 0-50 ZYSKI /STRATA Z GRANIA LONGOW

<ipython-input-5-5271784539c3>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  od0_do50_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 0) & (df['Price SK (EUR/MWh)'] <= 50)]

203.98124999999996

In [ ]:
# Filtering rows where 'Price SK' is between 0 and 50
od50_do75_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 50) & (df['Price SK (EUR/MWh)'] <= 75)]

# Calculating the total Profit/Loss for these rows
total_profit_loss = od50_do75_df['Profit_Loss'].sum()
total_profit_loss
# PRZEDZIAL 50-75 ZYSKI /STRATA Z GRANIA LONGOW

<ipython-input-11-0ae066fab071>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  od50_do75_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 50) & (df['Price SK (EUR/MWh)'] <= 75)]

-727.25

In [ ]:
# Filtering rows where 'Price SK' is between 0 and 50
od75_do100_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 75) & (df['Price SK (EUR/MWh)'] <= 100)]

# Calculating the total Profit/Loss for these rows
total_profit_loss = od75_do100_df['Profit_Loss'].sum()
total_profit_loss
# PRZEDZIAL 75-100 ZYSKI /STRATA Z GRANIA LONGOW

<ipython-input-12-2985ecb3832e>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  od75_do100_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 75) & (df['Price SK (EUR/MWh)'] <= 100)]

-30.185000000000002

In [ ]:
# Filtering rows where 'Price SK' is between 0 and 50
od100_do125_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 100) & (df['Price SK (EUR/MWh)'] <= 125)]

# Calculating the total Profit/Loss for these rows
total_profit_loss = od100_do125_df['Profit_Loss'].sum()
total_profit_loss
# PRZEDZIAL 100-125 ZYSKI /STRATA Z GRANIA LONGOW

<ipython-input-13-fa95bca38caf>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  od100_do125_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 100) & (df['Price SK (EUR/MWh)'] <= 125)]

63.804999999999964

In [ ]:
# Filtering rows where 'Price SK' is between 0 and 50
od125_do150_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 125) & (df['Price SK (EUR/MWh)'] <= 150)]

# Calculating the total Profit/Loss for these rows
total_profit_loss = od125_do150_df['Profit_Loss'].sum()
total_profit_loss
# PRZEDZIAL 125-150 ZYSKI /STRATA Z GRANIA LONGOW

<ipython-input-14-336a32ea3a2f>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  od125_do150_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 125) & (df['Price SK (EUR/MWh)'] <= 150)]

-1940.0387500000002

In [ ]:
# Filtering rows where 'Price SK' is between 0 and 50
od150_do500_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 150) & (df['Price SK (EUR/MWh)'] <= 500)]

# Calculating the total Profit/Loss for these rows
total_profit_loss = od150_do500_df['Profit_Loss'].sum()
total_profit_loss
# PRZEDZIAL 150-500 ZYSKI /STRATA Z GRANIA LONGOW

<ipython-input-15-cd7213768525>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  od150_do500_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 150) & (df['Price SK (EUR/MWh)'] <= 500)]

555.8779999999997

In [ ]:
###### 10 NAJWIKESZYCH STRAT W STYCZNIU 2023

In [ ]:
# Creating a new DataFrame with the 10 largest losses based on the 'Profit_Loss' column
df_largest_losses = df_january.nsmallest(10, 'Profit_Loss')

df_largest_losses.reset_index(drop=True, inplace=True)
df_largest_losses

,Delivery day,Period number,Period,Traded Price Average (EUR/MWh),Weighted average price of all trades (EUR/MWh),Minimal price (EUR/MWh),Maximal price (EUR/MWh),Last price (EUR/MWh),Bilans,Price SK (EUR/MWh),Unnamed: 10,Unnamed: 11,Profit_Loss
0,2023-01-23,11.0,10:00 - 11:00,255.30,255.86,237.00,275.00,266.98,-4.99525,252.18,NaN,NaN,-257.17525
1,2023-01-24,19.0,18:00 - 19:00,237.27,238.89,194.61,253.81,194.61,-5.00000,250.00,NaN,NaN,-255.00000
2,2023-01-31,18.0,17:00 - 18:00,180.26,171.73,144.01,231.00,186.99,-5.00000,246.44,NaN,NaN,-251.44000
3,2023-01-24,20.0,19:00 - 20:00,202.69,187.31,20.00,280.00,280.00,-5.00000,233.19,NaN,NaN,-238.19000
4,2023-01-23,12.0,11:00 - 12:00,243.37,245.21,217.00,256.32,245.10,-5.00000,231.82,NaN,NaN,-236.82000
5,2023-01-23,13.0,12:00 - 13:00,217.03,214.21,124.63,235.00,124.63,-5.00000,222.38,NaN,NaN,-227.38000
6,2023-01-12,11.0,10:00 - 11:00,196.34,203.06,190.00,210.09,195.00,-5.00000,195.07,NaN,NaN,-200.07000
7,2023-01-31,9.0,08:00 - 09:00,184.48,182.76,175.00,199.99,181.74,-5.00000,188.24,NaN,NaN,-193.24000
8,2023-01-11,20.0,19:00 - 20:00,180.99,177.97,162.03,227.74,181.98,-5.00000,186.53,NaN,NaN,-191.53000
9,2023-01-11,11.0,10:00 - 11:00,174.20,175.43,156.99,195.00,195.00,-5.00000,185.92,NaN,NaN,-190.92000

In [ ]:
######### wpisałem 10 największych strat z dodatnim bilansem myślalem ze beda jaies straty od szorta ale tutaj też same od longa

In [ ]:
# Filtering the DataFrame for rows where 'Bilans' is positive and then finding the 10 largest losses
df_positive_balance_losses = df_january[df_january['Bilans'] > 0].nsmallest(10, 'Profit_Loss')

df_positive_balance_losses.reset_index(drop=True, inplace=True)
df_positive_balance_losses

,Delivery day,Period number,Period,Traded Price Average (EUR/MWh),Weighted average price of all trades (EUR/MWh),Minimal price (EUR/MWh),Maximal price (EUR/MWh),Last price (EUR/MWh),Bilans,Price SK (EUR/MWh),Unnamed: 10,Unnamed: 11,Profit_Loss
0,2023-01-23,10.0,09:00 - 10:00,251.49,242.23,180.02,299.00,263.10,98.19225,271.82,NaN,NaN,-173.62775
1,2023-01-23,9.0,08:00 - 09:00,262.06,256.77,230.00,290.00,230.00,93.10125,258.27,NaN,NaN,-165.16875
2,2023-01-24,11.0,10:00 - 11:00,199.70,199.93,180.00,227.90,180.00,86.30250,240.14,NaN,NaN,-153.83750
3,2023-01-13,19.0,18:00 - 19:00,203.55,199.85,180.00,230.00,206.00,85.61250,238.30,NaN,NaN,-152.68750
4,2023-01-24,12.0,11:00 - 12:00,200.48,198.59,180.50,233.00,233.00,83.33750,232.22,NaN,NaN,-148.88250
5,2023-01-29,22.0,21:00 - 22:00,143.38,145.24,88.97,250.00,107.00,82.86000,230.96,NaN,NaN,-148.10000
6,2023-01-25,9.0,08:00 - 09:00,219.10,219.94,185.07,245.50,245.50,80.64000,225.04,NaN,NaN,-144.40000
7,2023-01-23,14.0,13:00 - 14:00,200.39,198.19,180.01,222.27,182.41,78.96000,220.56,NaN,NaN,-141.60000
8,2023-01-31,19.0,18:00 - 19:00,182.98,178.77,162.00,212.00,212.00,75.39000,211.04,NaN,NaN,-135.65000
9,2023-01-27,19.0,18:00 - 19:00,184.61,185.72,177.00,210.00,210.00,71.51250,200.70,NaN,NaN,-129.18750

In [ ]:
###### w tym DF BILANS WIEKSZY NIZ PRICE WIEC STRATA Z SZORTA

In [ ]:
# Creating a new DataFrame where 'Bilans' is greater than 'Price SK'
df_bilans_greater_than_price_sk = df_january[df_january['Bilans'] > df_january['Price SK (EUR/MWh)']]

df_bilans_greater_than_price_sk.reset_index(drop=True, inplace=True)
df_bilans_greater_than_price_sk

,Delivery day,Period number,Period,Traded Price Average (EUR/MWh),Weighted average price of all trades (EUR/MWh),Minimal price (EUR/MWh),Maximal price (EUR/MWh),Last price (EUR/MWh),Bilans,Price SK (EUR/MWh),Unnamed: 10,Unnamed: 11,Profit_Loss
0,2023-01-01,17.0,16:00 - 17:00,38.33,38.20,28.51,56.17,56.00,63.50250,36.54,NaN,NaN,26.96250
1,2023-01-01,18.0,17:00 - 18:00,53.24,46.96,34.43,86.40,84.00,97.75000,46.03,NaN,NaN,51.72000
2,2023-01-01,19.0,18:00 - 19:00,65.70,64.73,49.00,105.00,105.00,132.00000,53.68,NaN,NaN,78.32000
3,2023-01-01,20.0,19:00 - 20:00,72.41,70.91,51.50,111.00,111.00,132.00000,54.95,NaN,NaN,77.05000
4,2023-01-01,21.0,20:00 - 21:00,76.89,71.99,48.00,103.10,83.09,63.50000,49.11,NaN,NaN,14.39000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2023-01-31,13.0,12:00 - 13:00,135.63,136.11,122.21,145.00,130.00,214.74000,143.16,NaN,NaN,71.58000
413,2023-01-31,20.0,19:00 - 20:00,190.65,190.90,176.01,224.00,200.00,248.93875,222.39,NaN,NaN,26.54875
414,2023-01-31,21.0,20:00 - 21:00,168.67,167.40,155.00,190.19,165.60,202.19500,180.84,NaN,NaN,21.35500
415,2023-01-31,23.0,22:00 - 23:00,134.57,136.34,111.00,151.71,125.48,132.36625,118.77,NaN,NaN,13.59625
416,2023-01-31,24.0,23:00 - 00:00,105.93,105.95,88.00,115.92,100.01,104.54500,94.04,NaN,NaN,10.50500

In [ ]:
# Re-calculating the profit or loss with the correct interpretation
# When selling at 'Price SK' and buying back at 'Bilans', the profit or loss is calculated as:
# Profit or Loss = Price SK - Bilans

df_bilans_greater_than_price_sk['Profit_loss_od_szorta'] = df_bilans_greater_than_price_sk['Price SK (EUR/MWh)'] - df_bilans_greater_than_price_sk['Bilans']

df_bilans_greater_than_price_sk

<ipython-input-30-46ad387bef0e>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bilans_greater_than_price_sk['Profit_loss_od_szorta'] = df_bilans_greater_than_price_sk['Price SK (EUR/MWh)'] - df_bilans_greater_than_price_sk['Bilans']

,Delivery day,Period number,Period,Traded Price Average (EUR/MWh),Weighted average price of all trades (EUR/MWh),Minimal price (EUR/MWh),Maximal price (EUR/MWh),Last price (EUR/MWh),Bilans,Price SK (EUR/MWh),Unnamed: 10,Unnamed: 11,Profit_Loss,Profit_loss_od_szorta
0,2023-01-01,17.0,16:00 - 17:00,38.33,38.20,28.51,56.17,56.00,63.50250,36.54,NaN,NaN,26.96250,-26.96250
1,2023-01-01,18.0,17:00 - 18:00,53.24,46.96,34.43,86.40,84.00,97.75000,46.03,NaN,NaN,51.72000,-51.72000
2,2023-01-01,19.0,18:00 - 19:00,65.70,64.73,49.00,105.00,105.00,132.00000,53.68,NaN,NaN,78.32000,-78.32000
3,2023-01-01,20.0,19:00 - 20:00,72.41,70.91,51.50,111.00,111.00,132.00000,54.95,NaN,NaN,77.05000,-77.05000
4,2023-01-01,21.0,20:00 - 21:00,76.89,71.99,48.00,103.10,83.09,63.50000,49.11,NaN,NaN,14.39000,-14.39000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2023-01-31,13.0,12:00 - 13:00,135.63,136.11,122.21,145.00,130.00,214.74000,143.16,NaN,NaN,71.58000,-71.58000
413,2023-01-31,20.0,19:00 - 20:00,190.65,190.90,176.01,224.00,200.00,248.93875,222.39,NaN,NaN,26.54875,-26.54875
414,2023-01-31,21.0,20:00 - 21:00,168.67,167.40,155.00,190.19,165.60,202.19500,180.84,NaN,NaN,21.35500,-21.35500
415,2023-01-31,23.0,22:00 - 23:00,134.57,136.34,111.00,151.71,125.48,132.36625,118.77,NaN,NaN,13.59625,-13.59625
416,2023-01-31,24.0,23:00 - 00:00,105.93,105.95,88.00,115.92,100.01,104.54500,94.04,NaN,NaN,10.50500,-10.50500

In [ ]:

# Finding the 10 largest losses (smallest Profit_Loss values)
largest_losses = df_bilans_greater_than_price_sk.nlargest(20, 'Profit_Loss')

largest_losses.reset_index(drop=True, inplace=True)
largest_losses
######## NAJWIKESZKE STRATY W STYCZNIU 2023 OD SZORTA.....

,Delivery day,Period number,Period,Traded Price Average (EUR/MWh),Weighted average price of all trades (EUR/MWh),Minimal price (EUR/MWh),Maximal price (EUR/MWh),Last price (EUR/MWh),Bilans,Price SK (EUR/MWh),Unnamed: 10,Unnamed: 11,Profit_Loss,Profit_loss_od_szorta
0,2023-01-30,16.0,15:00 - 16:00,218.09,222.53,180.00,289.00,180.00,446.895,297.93,NaN,NaN,148.965,-148.965
1,2023-01-30,14.0,13:00 - 14:00,215.44,211.73,175.00,268.00,179.44,428.910,285.94,NaN,NaN,142.970,-142.970
2,2023-01-30,10.0,09:00 - 10:00,258.12,269.87,212.68,311.99,311.99,426.930,284.62,NaN,NaN,142.310,-142.310
3,2023-01-30,19.0,18:00 - 19:00,239.39,242.00,218.92,277.00,277.00,416.715,277.81,NaN,NaN,138.905,-138.905
4,2023-01-04,21.0,20:00 - 21:00,276.83,274.72,180.00,332.86,332.77,414.840,276.56,NaN,NaN,138.280,-138.280
5,2023-01-30,8.0,07:00 - 08:00,326.72,309.04,215.56,424.97,351.51,414.600,276.40,NaN,NaN,138.200,-138.200
6,2023-01-04,17.0,16:00 - 17:00,316.26,329.73,180.00,362.00,339.90,413.010,275.34,NaN,NaN,137.670,-137.670
7,2023-01-30,11.0,10:00 - 11:00,205.16,208.70,183.01,252.00,225.00,402.240,268.16,NaN,NaN,134.080,-134.080
8,2023-01-30,13.0,12:00 - 13:00,212.12,212.32,170.00,267.00,267.00,401.100,267.40,NaN,NaN,133.700,-133.700
9,2023-01-30,17.0,16:00 - 17:00,269.75,269.32,225.01,296.82,225.01,393.135,262.09,NaN,NaN,131.045,-131.045
10,2023-01-30,12.0,11:00 - 12:00,194.75,197.57,168.89,250.00,250.00,385.050,256.70,NaN,NaN,128.350,-128.350
11,2023-01-24,9.0,08:00 - 09:00,209.45,208.70,193.00,239.00,217.62,382.215,254.81,NaN,NaN,127.405,-127.405
12,2023-01-04,20.0,19:00 - 20:00,267.05,280.90,180.00,309.90,309.90,376.350,250.90,NaN,NaN,125.450,-125.450
13,2023-01-24,18.0,17:00 - 18:00,244.10,244.91,220.00,253.97,247.00,375.000,250.00,NaN,NaN,125.000,-125.000
14,2023-01-23,18.0,17:00 - 18:00,254.78,257.95,233.00,270.00,260.70,373.350,248.90,NaN,NaN,124.450,-124.450
15,2023-01-15,7.0,06:00 - 07:00,26.32,25.90,10.00,57.98,13.90,132.000,10.90,NaN,NaN,121.100,-121.100
16,2023-01-04,18.0,17:00 - 18:00,293.20,300.90,180.00,334.91,290.00,356.055,237.37,NaN,NaN,118.685,-118.685
17,2023-01-30,9.0,08:00 - 09:00,264.76,271.46,222.00,299.99,299.00,355.680,237.12,NaN,NaN,118.560,-118.560
18,2023-01-20,9.0,08:00 - 09:00,242.48,243.30,221.00,314.50,240.00,352.680,235.12,NaN,NaN,117.560,-117.560
19,2023-01-30,7.0,06:00 - 07:00,235.09,234.86,219.00,259.99,233.00,350.175,233.45,NaN,NaN,116.725,-116.725

In [ ]:


# Filtering for records where 'Price SK' does not exceed 200
DA_ponizej_200 = df_bilans_greater_than_price_sk[df_bilans_greater_than_price_sk['Price SK (EUR/MWh)'] <= 150]

# Finding the 20 largest losses (most negative values) in 'Profit_loss_od_szorta'
largest_losses = DA_ponizej_200.nsmallest(20, 'Profit_loss_od_szorta')

largest_losses.reset_index(drop=True, inplace=True)
largest_losses
######### najwikesze straty kiedy FIX był poniżej 150. praktycznie duze straty najczesciej sa przy wysokich cenach

,Delivery day,Period number,Period,Traded Price Average (EUR/MWh),Weighted average price of all trades (EUR/MWh),Minimal price (EUR/MWh),Maximal price (EUR/MWh),Last price (EUR/MWh),Bilans,Price SK (EUR/MWh),Unnamed: 10,Unnamed: 11,Profit_Loss,Profit_loss_od_szorta
0,2023-01-15,7.0,06:00 - 07:00,26.32,25.90,10.00,57.98,13.90,132.000,10.90,NaN,NaN,121.100,-121.100
1,2023-01-30,4.0,03:00 - 04:00,86.19,86.31,43.00,105.00,99.96,141.900,45.93,NaN,NaN,95.970,-95.970
2,2023-01-01,19.0,18:00 - 19:00,65.70,64.73,49.00,105.00,105.00,132.000,53.68,NaN,NaN,78.320,-78.320
3,2023-01-01,20.0,19:00 - 20:00,72.41,70.91,51.50,111.00,111.00,132.000,54.95,NaN,NaN,77.050,-77.050
4,2023-01-07,21.0,20:00 - 21:00,156.00,155.62,140.00,195.88,165.00,223.995,149.33,NaN,NaN,74.665,-74.665
5,2023-01-25,5.0,04:00 - 05:00,146.15,144.05,123.28,155.50,149.20,223.305,148.87,NaN,NaN,74.435,-74.435
6,2023-01-30,2.0,01:00 - 02:00,154.33,128.44,105.00,186.00,186.00,223.200,148.80,NaN,NaN,74.400,-74.400
7,2023-01-14,10.0,09:00 - 10:00,193.13,190.52,139.00,228.12,200.00,221.220,147.48,NaN,NaN,73.740,-73.740
8,2023-01-21,20.0,19:00 - 20:00,163.21,163.38,138.00,177.00,152.01,220.575,147.05,NaN,NaN,73.525,-73.525
9,2023-01-28,22.0,21:00 - 22:00,153.47,153.10,134.00,173.80,173.80,219.495,146.33,NaN,NaN,73.165,-73.165
10,2023-01-10,7.0,06:00 - 07:00,152.77,152.48,137.00,165.00,164.00,218.715,145.81,NaN,NaN,72.905,-72.905
11,2023-01-05,12.0,11:00 - 12:00,147.42,147.26,137.00,160.00,151.88,218.700,145.80,NaN,NaN,72.900,-72.900
12,2023-01-31,12.0,11:00 - 12:00,135.54,137.42,115.00,162.09,125.00,217.740,145.16,NaN,NaN,72.580,-72.580
13,2023-01-05,10.0,09:00 - 10:00,141.88,139.56,120.00,160.00,120.00,217.455,144.97,NaN,NaN,72.485,-72.485
14,2023-01-20,6.0,05:00 - 06:00,139.02,146.64,95.01,161.00,160.93,217.245,144.83,NaN,NaN,72.415,-72.415
15,2023-01-07,12.0,11:00 - 12:00,125.89,127.22,104.01,160.99,119.00,216.285,144.19,NaN,NaN,72.095,-72.095
16,2023-01-15,15.0,14:00 - 15:00,140.88,139.83,112.06,168.00,151.11,215.340,143.56,NaN,NaN,71.780,-71.780
17,2023-01-17,23.0,22:00 - 23:00,142.17,143.73,128.53,152.93,140.01,215.160,143.44,NaN,NaN,71.720,-71.720
18,2023-01-31,13.0,12:00 - 13:00,135.63,136.11,122.21,145.00,130.00,214.740,143.16,NaN,NaN,71.580,-71.580
19,2023-01-05,13.0,12:00 - 13:00,148.42,151.38,133.00,160.30,145.00,213.525,142.35,NaN,NaN,71.175,-71.175

In [ ]:
##################

In [ ]:
df_january

,Delivery day,Period number,Period,Traded Price Average (EUR/MWh),Weighted average price of all trades (EUR/MWh),Minimal price (EUR/MWh),Maximal price (EUR/MWh),Last price (EUR/MWh),Bilans,Price SK (EUR/MWh),Unnamed: 10,Unnamed: 11,Profit_Loss
0,2023-01-01,1.0,00:00 - 01:00,19.40,18.93,7.00,30.26,19.00,-5.00000,20.26,NaN,NaN,-25.26000
1,2023-01-01,2.0,01:00 - 02:00,3.07,1.35,0.30,10.33,0.30,-2.25250,0.33,NaN,NaN,-2.58250
2,2023-01-01,3.0,02:00 - 03:00,4.18,2.05,0.50,10.50,0.50,-5.00000,0.50,NaN,NaN,-5.50000
3,2023-01-01,4.0,03:00 - 04:00,4.40,2.26,0.00,10.50,0.00,-5.00000,0.50,NaN,NaN,-5.50000
4,2023-01-01,5.0,04:00 - 05:00,5.08,3.12,0.00,10.10,0.00,-5.00000,0.10,NaN,NaN,-5.10000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,2023-01-31,20.0,19:00 - 20:00,190.65,190.90,176.01,224.00,200.00,248.93875,222.39,NaN,NaN,26.54875
740,2023-01-31,21.0,20:00 - 21:00,168.67,167.40,155.00,190.19,165.60,202.19500,180.84,NaN,NaN,21.35500
741,2023-01-31,22.0,21:00 - 22:00,146.73,147.35,130.04,154.05,148.08,108.34250,147.79,NaN,NaN,-39.44750
742,2023-01-31,23.0,22:00 - 23:00,134.57,136.34,111.00,151.71,125.48,132.36625,118.77,NaN,NaN,13.59625
743,2023-01-31,24.0,23:00 - 00:00,105.93,105.95,88.00,115.92,100.01,104.54500,94.04,NaN,NaN,10.50500