<a href="https://colab.research.google.com/github/tomektom10/dataScienceBootCamp/blob/main/ENERGIA_anal_szczegolowe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("kkkkkkkk.xlsx")

In [3]:
df['Profit_Loss'] = df['Bilans'] - df['Price SK (EUR/MWh)']

df

,Delivery day,Period number,Period,Traded Price Average (EUR/MWh),Weighted average price of all trades (EUR/MWh),Minimal price (EUR/MWh),Maximal price (EUR/MWh),Last price (EUR/MWh),Bilans,Price SK (EUR/MWh),Unnamed: 10,Unnamed: 11,Profit_Loss
0,2023-01-01,1.0,00:00 - 01:00,19.40,18.93,7.00,30.26,19.00,-5.0000,20.26,NaN,NaN,-25.2600
1,2023-01-01,2.0,01:00 - 02:00,3.07,1.35,0.30,10.33,0.30,-2.2525,0.33,NaN,NaN,-2.5825
2,2023-01-01,3.0,02:00 - 03:00,4.18,2.05,0.50,10.50,0.50,-5.0000,0.50,NaN,NaN,-5.5000
3,2023-01-01,4.0,03:00 - 04:00,4.40,2.26,0.00,10.50,0.00,-5.0000,0.50,NaN,NaN,-5.5000
4,2023-01-01,5.0,04:00 - 05:00,5.08,3.12,0.00,10.10,0.00,-5.0000,0.10,NaN,NaN,-5.1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8756,2023-12-31,21.0,20:00 - 21:00,26.51,27.36,14.23,48.00,15.00,-5.0000,24.04,NaN,NaN,-29.0400
8757,2023-12-31,22.0,21:00 - 22:00,17.22,18.78,3.87,45.00,5.00,-5.0000,9.85,NaN,NaN,-14.8500
8758,2023-12-31,23.0,22:00 - 23:00,16.81,19.80,4.23,55.00,5.00,-5.0000,10.68,NaN,NaN,-15.6800
8759,2023-12-31,24.0,23:00 - 00:00,13.72,18.38,6.64,35.11,8.59,-5.0000,15.11,NaN,NaN,-20.1100
8760,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96660.676,NaN

In [7]:
from io import StringIO



# Konwersja kolumny 'Delivery day' do formatu daty
df['Delivery day'] = pd.to_datetime(df['Delivery day'])

# Wyodrębnienie danych za styczeń 2023
df_january = df[df['Delivery day'].dt.month == 1]

df_january

,Delivery day,Period number,Period,Traded Price Average (EUR/MWh),Weighted average price of all trades (EUR/MWh),Minimal price (EUR/MWh),Maximal price (EUR/MWh),Last price (EUR/MWh),Bilans,Price SK (EUR/MWh),Unnamed: 10,Unnamed: 11,Profit_Loss
0,2023-01-01,1.0,00:00 - 01:00,19.40,18.93,7.00,30.26,19.00,-5.00000,20.26,NaN,NaN,-25.26000
1,2023-01-01,2.0,01:00 - 02:00,3.07,1.35,0.30,10.33,0.30,-2.25250,0.33,NaN,NaN,-2.58250
2,2023-01-01,3.0,02:00 - 03:00,4.18,2.05,0.50,10.50,0.50,-5.00000,0.50,NaN,NaN,-5.50000
3,2023-01-01,4.0,03:00 - 04:00,4.40,2.26,0.00,10.50,0.00,-5.00000,0.50,NaN,NaN,-5.50000
4,2023-01-01,5.0,04:00 - 05:00,5.08,3.12,0.00,10.10,0.00,-5.00000,0.10,NaN,NaN,-5.10000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,2023-01-31,20.0,19:00 - 20:00,190.65,190.90,176.01,224.00,200.00,248.93875,222.39,NaN,NaN,26.54875
740,2023-01-31,21.0,20:00 - 21:00,168.67,167.40,155.00,190.19,165.60,202.19500,180.84,NaN,NaN,21.35500
741,2023-01-31,22.0,21:00 - 22:00,146.73,147.35,130.04,154.05,148.08,108.34250,147.79,NaN,NaN,-39.44750
742,2023-01-31,23.0,22:00 - 23:00,134.57,136.34,111.00,151.71,125.48,132.36625,118.77,NaN,NaN,13.59625
743,2023-01-31,24.0,23:00 - 00:00,105.93,105.95,88.00,115.92,100.01,104.54500,94.04,NaN,NaN,10.50500

In [10]:
zyski_strata_styczen = df_january['Profit_Loss'].sum()
zyski_strata_styczen
# ZYSKI STRATA STYCZEN

-1956.3594999999996

In [5]:


# Filtering rows where 'Price SK' is between 0 and 50
od0_do50_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 0) & (df['Price SK (EUR/MWh)'] <= 50)]

# Calculating the total Profit/Loss for these rows
total_profit_loss = od0_do50_df['Profit_Loss'].sum()
total_profit_loss
# PRZEDZIAL 0-50 ZYSKI /STRATA Z GRANIA LONGOW

<ipython-input-5-5271784539c3>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  od0_do50_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 0) & (df['Price SK (EUR/MWh)'] <= 50)]

203.98124999999996

In [11]:
# Filtering rows where 'Price SK' is between 0 and 50
od50_do75_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 50) & (df['Price SK (EUR/MWh)'] <= 75)]

# Calculating the total Profit/Loss for these rows
total_profit_loss = od50_do75_df['Profit_Loss'].sum()
total_profit_loss
# PRZEDZIAL 50-75 ZYSKI /STRATA Z GRANIA LONGOW

<ipython-input-11-0ae066fab071>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  od50_do75_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 50) & (df['Price SK (EUR/MWh)'] <= 75)]

-727.25

In [12]:
# Filtering rows where 'Price SK' is between 0 and 50
od75_do100_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 75) & (df['Price SK (EUR/MWh)'] <= 100)]

# Calculating the total Profit/Loss for these rows
total_profit_loss = od75_do100_df['Profit_Loss'].sum()
total_profit_loss
# PRZEDZIAL 75-100 ZYSKI /STRATA Z GRANIA LONGOW

<ipython-input-12-2985ecb3832e>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  od75_do100_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 75) & (df['Price SK (EUR/MWh)'] <= 100)]

-30.185000000000002

In [13]:
# Filtering rows where 'Price SK' is between 0 and 50
od100_do125_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 100) & (df['Price SK (EUR/MWh)'] <= 125)]

# Calculating the total Profit/Loss for these rows
total_profit_loss = od100_do125_df['Profit_Loss'].sum()
total_profit_loss
# PRZEDZIAL 100-125 ZYSKI /STRATA Z GRANIA LONGOW

<ipython-input-13-fa95bca38caf>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  od100_do125_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 100) & (df['Price SK (EUR/MWh)'] <= 125)]

63.804999999999964

In [14]:
# Filtering rows where 'Price SK' is between 0 and 50
od125_do150_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 125) & (df['Price SK (EUR/MWh)'] <= 150)]

# Calculating the total Profit/Loss for these rows
total_profit_loss = od125_do150_df['Profit_Loss'].sum()
total_profit_loss
# PRZEDZIAL 125-150 ZYSKI /STRATA Z GRANIA LONGOW

<ipython-input-14-336a32ea3a2f>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  od125_do150_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 125) & (df['Price SK (EUR/MWh)'] <= 150)]

-1940.0387500000002

In [15]:
# Filtering rows where 'Price SK' is between 0 and 50
od150_do500_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 150) & (df['Price SK (EUR/MWh)'] <= 500)]

# Calculating the total Profit/Loss for these rows
total_profit_loss = od150_do500_df['Profit_Loss'].sum()
total_profit_loss
# PRZEDZIAL 150-500 ZYSKI /STRATA Z GRANIA LONGOW

<ipython-input-15-cd7213768525>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  od150_do500_df = df_january[(df_january['Price SK (EUR/MWh)'] >= 150) & (df['Price SK (EUR/MWh)'] <= 500)]

555.8779999999997