<a href="https://colab.research.google.com/github/tomektom10/dataScienceBootCamp/blob/main/moje_projekt_cukier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
df = pd.read_excel("Cukry_wszystkie.xlsx")
df
df.columns
import numpy as np
import datetime

In [17]:
df

,SBES1H23,Unnamed: 1,Unnamed: 2,SBES1K23,Unnamed: 4,Unnamed: 5,SBES1N23,Unnamed: 7,Unnamed: 8,SBES1V23,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Date,C,NaN,Date,C,NaN,Date,C,NaN,Date,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,2023-02-28 00:00:00,2.01,NaN,2023-04-28 00:00:00,0.7,NaN,2023-06-30 00:00:00,0.1,NaN,2023-09-29 00:00:00,-0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
2,2023-02-27 00:00:00,1.82,NaN,2023-04-27 00:00:00,0.56,NaN,2023-06-29 00:00:00,-0.01,NaN,2023-09-28 00:00:00,-0.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,2023-02-24 00:00:00,1.62,NaN,2023-04-26 00:00:00,0.7,NaN,2023-06-28 00:00:00,-0.02,NaN,2023-09-27 00:00:00,-0.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
4,2023-02-23 00:00:00,1.27,NaN,2023-04-25 00:00:00,0.67,NaN,2023-06-27 00:00:00,0.02,NaN,2023-09-26 00:00:00,-0.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3033,2012-12-26 00:00:00,0.1,NaN,2013-02-27 00:00:00,-0.11,NaN,2013-04-29 00:00:00,-0.26,NaN,2013-07-30 00:00:00,-0.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3034,2012-12-24 00:00:00,0.12,NaN,2013-02-26 00:00:00,-0.09,NaN,2013-04-26 00:00:00,-0.27,NaN,2013-07-29 00:00:00,-0.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3035,2012-12-21 00:00:00,0.1,NaN,2013-02-25 00:00:00,-0.12,NaN,2013-04-25 00:00:00,-0.27,NaN,2013-07-26 00:00:00,-0.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3036,2012-12-20 00:00:00,0.11,NaN,2013-02-22 00:00:00,-0.14,NaN,2013-04-24 00:00:00,-0.25,NaN,2013-07-25 00:00:00,-0.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3037,2012-12-19 00:00:00,0.11,NaN,2013-02-21 00:00:00,-0.16,NaN,2013-04-23 00:00:00,-0.19,NaN,2013-07-24 00:00:00,-0.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [18]:
df1 = df[["SBES1H23", "Unnamed: 1"]].iloc[1:]
df1

                 SBES1H23 Unnamed: 1
1     2023-02-28 00:00:00       2.01
2     2023-02-27 00:00:00       1.82
3     2023-02-24 00:00:00       1.62
4     2023-02-23 00:00:00       1.27
5     2023-02-22 00:00:00       1.39
...                   ...        ...
3033  2012-12-26 00:00:00        0.1
3034  2012-12-24 00:00:00       0.12
3035  2012-12-21 00:00:00        0.1
3036  2012-12-20 00:00:00       0.11
3037  2012-12-19 00:00:00       0.11

[3037 rows x 2 columns]

In [19]:
df2 = df[["SBES1K23", "Unnamed: 4"]].iloc[1:]
df2
import datetime

df3 = df[["SBES1N23", "Unnamed: 7"]].iloc[1:]
df3

                 SBES1N23 Unnamed: 7
1     2023-06-30 00:00:00        0.1
2     2023-06-29 00:00:00      -0.01
3     2023-06-28 00:00:00      -0.02
4     2023-06-27 00:00:00       0.02
5     2023-06-26 00:00:00       0.06
...                   ...        ...
3033  2013-04-29 00:00:00      -0.26
3034  2013-04-26 00:00:00      -0.27
3035  2013-04-25 00:00:00      -0.27
3036  2013-04-24 00:00:00      -0.25
3037  2013-04-23 00:00:00      -0.19

[3037 rows x 2 columns]

In [ ]:
# przerobiłem tak zeby w przypadku braku danych wyswietlało puste.

In [20]:
days_of_month = ["04-01", "04-02", "04-03", "04-04",  "04-05", "02-24", "02-23", "02-25", "02-26", "02-27", "11-01", "11-02", "11-03", "11-04", "11-05", "11-06", "11-07", "11-08", "11-09", "11-10", "11-11", "11-12", "11-13", "11-14"]  # Lista dwóch różnych dni

wynik_dict = {"Date": [], "cena_flaja1": [], "cena_flaja2": []}

for day_month in days_of_month:
    temp_dict = {"Date": [], "cena_flaja1": [], "cena_flaja2": []}

    for year in [2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014]:
        specyfic_date = str(year) + "-" + day_month
        specyfic_date = datetime.datetime.strptime(specyfic_date, '%Y-%m-%d')
        print(specyfic_date)

        df_row1 = df1[df1["SBES1H23"] == specyfic_date]
        print(df_row1)

        df_row2 = df2[df2["SBES1K23"] == specyfic_date]
        print(df_row2)

        cena_flaja = []
        for i, value in enumerate(df_row1['Unnamed: 1'].values):
            roznica = value - df_row2["Unnamed: 4"].values[i]
            cena_flaja.append(roznica)

        if len(cena_flaja) == 1:
            temp_dict["Date"].append(specyfic_date)
            temp_dict["cena_flaja1"].append(cena_flaja[0])
            temp_dict["cena_flaja2"].append(np.nan)
        elif len(cena_flaja) == 2:
            temp_dict["Date"].append(specyfic_date)
            temp_dict["cena_flaja1"].append(cena_flaja[0])
            temp_dict["cena_flaja2"].append(cena_flaja[1])
        else:
            temp_dict["Date"].append(specyfic_date)
            temp_dict["cena_flaja1"].append(np.nan)
            temp_dict["cena_flaja2"].append(np.nan)

    wynik_dict["Date"].extend(temp_dict["Date"])
    wynik_dict["cena_flaja1"].extend(temp_dict["cena_flaja1"])
    wynik_dict["cena_flaja2"].extend(temp_dict["cena_flaja2"])

df_wynik = pd.DataFrame(wynik_dict)

2023-04-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-04-01 00:00:00
                SBES1H23 Unnamed: 1
228  2022-04-01 00:00:00       0.75
                SBES1K23 Unnamed: 4
270  2022-04-01 00:00:00       0.51
324  2022-04-01 00:00:00       0.19
2021-04-01 00:00:00
                SBES1H23 Unnamed: 1
534  2021-04-01 00:00:00       0.68
                SBES1K23 Unnamed: 4
577  2021-04-01 00:00:00        0.5
629  2021-04-01 00:00:00      -0.01
2020-04-01 00:00:00
                SBES1H23 Unnamed: 1
837  2020-04-01 00:00:00       0.04
                SBES1K23 Unnamed: 4
881  2020-04-01 00:00:00       0.03
933  2020-04-01 00:00:00      -0.04
2019-04-01 00:00:00
                 SBES1H23 Unnamed: 1
1143  2019-04-01 00:00:00      -0.11
                 SBES1K23 Unnamed: 4
1186  2019-04-01 00:00:00      -0.08
1237  2019-04-01 00:00:00      -0.13
2018-04-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-04-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-04-01 00:00:00
                 SBES1H23 Unnamed: 1
2055  2016-04-01 00:00:00       0.23
                 SBES1K23 Unnamed: 4
2097  2016-04-01 00:00:00       0.25
2150  2016-04-01 00:00:00      -0.08
2015-04-01 00:00:00
                 SBES1H23 Unnamed: 1
2359  2015-04-01 00:00:00      -0.05
                 SBES1K23 Unnamed: 4
2402  2015-04-01 00:00:00       0.05
2454  2015-04-01 00:00:00      -0.09
2014-04-01 00:00:00
                 SBES1H23 Unnamed: 1
2663  2014-04-01 00:00:00       0.12
                 SBES1K23 Unnamed: 4
2706  2014-04-01 00:00:00       0.22
2758  2014-04-01 00:00:00      -0.42
2023-04-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-04-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-04-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-04-02 00:00:00
                SBES1H23 Unnamed: 1
836  2020-04-02 00:00:00       0.05
                SBES1K23 Unnamed: 4
880  2020-04-02 00:00:00       0.03
932  2020-04-02 00:00:00      -0.04
2019-04-02 00:00:00
                 SBES1H23 Unnamed: 1
1142  2019-04-02 00:00:00      -0.11
                 SBES1K23 Unnamed: 4
1185  2019-04-02 00:00:00      -0.09
1236  2019-04-02 00:00:00      -0.15
2018-04-02 00:00:00
                 SBES1H23 Unnamed: 1
1447  2018-04-02 00:00:00      -0.16
                 SBES1K23 Unnamed: 4
1489  2018-04-02 00:00:00       -0.1
1541  2018-04-02 00:00:00      -0.11
2017-04-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-04-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2015-04-02 00:00:00
                 SBES1H23 Unnamed: 1
2358  2015-04-02 00:00:00      -0.04
                 SBES1K23 Unnamed: 4
2401  2015-04-02 00:00:00       0.07
2453  2015-04-02 00:00:00      -0.06
2014-04-02 00:00:00
                 SBES1H23 Unnamed: 1
2662  2014-04-02 00:00:00       0.12
                 SBES1K23 Unnamed: 4
2705  2014-04-02 00:00:00       0.16
2757  2014-04-02 00:00:00      -0.46
2023-04-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
19  2023-04-03 00:00:00       0.42
2022-04-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-04-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-04-03 00:00:00
                SBES1H23 Unnamed: 1
835  2020-04-03 00:00:00       0.09
                SBES1K23 Unnamed: 4
879  2020-04-03 00:00:00       0.08
931  2020-04-03 00:00:00      -0.01
2019-04-03 00:00:00
                 SBES1H23 Unnamed: 1
1141  2019-04-03 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1184  2019-04-03 00:00:00      -0.11
1235  2019-04-03 00:00:00      -0.14
2018-04-03 00:00:00
                 SBES1H23 Unnamed: 1
1446  2018-04-03 00:00:00      -0.16
                 SBES1K23 Unnamed: 4
1488  2018-04-03 00:00:00      -0.12
1540  2018-04-03 00:00:00      -0.14
2017-04-03 00:00:00
                 SBES1H23 Unnamed: 1
1749  2017-04-03 00:00:00       0.13
                 SBES1K23 Unnamed: 4
1791  2017-04-03 00:00:00       0.14
1844  2017-04-03 00:00:00      -0.14
2016-04-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2015-04-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2014-04-03 00:00:00
                 SBES1H23 Unnamed: 1
2661  2014-04-03 00:00:00       0.16
                 SBES1K23 Unnamed: 4
2704  2014-04-03 00:00:00        0.2
2756  2014-04-03 00:00:00      -0.41
2023-04-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
18  2023-04-04 00:00:00        0.4
2022-04-04 00:00:00
                SBES1H23 Unnamed: 1
227  2022-04-04 00:00:00       0.78
                SBES1K23 Unnamed: 4
269  2022-04-04 00:00:00       0.54
323  2022-04-04 00:00:00        0.2
2021-04-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-04-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2019-04-04 00:00:00
                 SBES1H23 Unnamed: 1
1140  2019-04-04 00:00:00      -0.09
                 SBES1K23 Unnamed: 4
1183  2019-04-04 00:00:00      -0.07
1234  2019-04-04 00:00:00       -0.1
2018-04-04 00:00:00
                 SBES1H23 Unnamed: 1
1445  2018-04-04 00:00:00      -0.16
                 SBES1K23 Unnamed: 4
1487  2018-04-04 00:00:00      -0.12
1539  2018-04-04 00:00:00      -0.17
2017-04-04 00:00:00
                 SBES1H23 Unnamed: 1
1748  2017-04-04 00:00:00       0.09
                 SBES1K23 Unnamed: 4
1790  2017-04-04 00:00:00       0.12
1843  2017-04-04 00:00:00      -0.17
2016-04-04 00:00:00
                 SBES1H23 Unnamed: 1
2054  2016-04-04 00:00:00       0.21
                 SBES1K23 Unnamed: 4
2096  2016-04-04 00:00:00       0.24
2149  2016-04-04 00:00:00      -0.17
2015-04-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2014-04-04 00:00:00
                 SBES1H23 Unnamed: 1
2660  2014-04-04 00:00:00       0.18
                 SBES1K23 Unnamed: 4
2703  2014-04-04 00:00:00       0.22
2755  2014-04-04 00:00:00      -0.44
2023-04-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
17  2023-04-05 00:00:00        0.4
2022-04-05 00:00:00
                SBES1H23 Unnamed: 1
226  2022-04-05 00:00:00       0.79
                SBES1K23 Unnamed: 4
268  2022-04-05 00:00:00       0.54
322  2022-04-05 00:00:00       0.14
2021-04-05 00:00:00
                SBES1H23 Unnamed: 1
533  2021-04-05 00:00:00       0.67
                SBES1K23 Unnamed: 4
576  2021-04-05 00:00:00       0.48
628  2021-04-05 00:00:00       0.08
2020-04-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2019-04-05 00:00:00
                 SBES1H23 Unnamed: 1
1139  2019-04-05 00:00:00       -0.1
                 SBES1K23 Unnamed: 4
1182  2019-04-05 00:00:00      -0.07
1233  2019-04-05 00:00:00      -0.12
2018-04-05 00:00:00
                 SBES1H23 Unnamed: 1
1444  2018-04-05 00:00:00      -0.16
                 SBES1K23 Unnamed: 4
1486  2018-04-05 00:00:00      -0.13
1538  2018-04-05 00:00:00      -0.12
2017-04-05 00:00:00
                 SBES1H23 Unnamed: 1
1747  2017-04-05 00:00:00        0.1
                 SBES1K23 Unnamed: 4
1789  2017-04-05 00:00:00       0.13
1842  2017-04-05 00:00:00      -0.12
2016-04-05 00:00:00
                 SBES1H23 Unnamed: 1
2053  2016-04-05 00:00:00        0.2
                 SBES1K23 Unnamed: 4
2095  2016-04-05 00:00:00       0.21
2148  2016-04-05 00:00:00      -0.13
2015-04-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2014-04-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-02-24 00:00:00
              SBES1H23 Unnamed: 1
3  2023-02-24 00:00:00       1.62
               SBES1K23 Unnamed: 4
45  2023-02-24 00:00:00       0.45
2022-02-24 00:00:00
                SBES1H23 Unnamed: 1
254  2022-02-24 00:00:00       0.67
307  2022-02-24 00:00:00       0.39
                SBES1K23 Unnamed: 4
296  2022-02-24 00:00:00       0.45
350  2022-02-24 00:00:00       0.15
2021-02-24 00:00:00
                SBES1H23 Unnamed: 1
560  2021-02-24 00:00:00       0.99
611  2021-02-24 00:00:00          1
                SBES1K23 Unnamed: 4
603  2021-02-24 00:00:00       0.72
655  2021-02-24 00:00:00       0.71
2020-02-24 00:00:00
                SBES1H23 Unnamed: 1
864  2020-02-24 00:00:00        0.5
917  2020-02-24 00:00:00       0.56
                SBES1K23 Unnamed: 4
908  2020-02-24 00:00:00       0.43
960  2020-02-24 00:00:00       0.14
2019-02-24 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-02-24 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-02-24 00:00:00
                 SBES1H23 Unnamed: 1
1775  2017-02-24 00:00:00       0.57
1828  2017-02-24 00:00:00      -0.02
                 SBES1K23 Unnamed: 4
1817  2017-02-24 00:00:00       0.53
1870  2017-02-24 00:00:00       0.23
2016-02-24 00:00:00
                 SBES1H23 Unnamed: 1
2081  2016-02-24 00:00:00       0.23
2133  2016-02-24 00:00:00       0.05
                 SBES1K23 Unnamed: 4
2123  2016-02-24 00:00:00       0.23
2176  2016-02-24 00:00:00        0.1
2015-02-24 00:00:00
                 SBES1H23 Unnamed: 1
2385  2015-02-24 00:00:00      -0.07
2437  2015-02-24 00:00:00       0.03
                 SBES1K23 Unnamed: 4
2428  2015-02-24 00:00:00       0.02
2480  2015-02-24 00:00:00      -0.28
2014-02-24 00:00:00
                 SBES1H23 Unnamed: 1
2689  2014-02-24 00:00:00       0.22
2742  2014-02-24 00:00:00      -0.24
                 SBES1K23 Unnamed: 4
2732  2014-02-24 00:00:00       0.17
2784  2014-02-24 00:00:00      -0.09
2023-02-23 00:00:00
              SBES1H23 Unnamed: 1
4  2023-02-23 00:00:00       1.27
               SBES1K23 Unnamed: 4
46  2023-02-23 00:00:00       0.55
2022-02-23 00:00:00
                SBES1H23 Unnamed: 1
255  2022-02-23 00:00:00       0.62
308  2022-02-23 00:00:00       0.65
                SBES1K23 Unnamed: 4
297  2022-02-23 00:00:00       0.44
351  2022-02-23 00:00:00       0.18
2021-02-23 00:00:00
                SBES1H23 Unnamed: 1
561  2021-02-23 00:00:00          1
612  2021-02-23 00:00:00        1.3
                SBES1K23 Unnamed: 4
604  2021-02-23 00:00:00       0.75
656  2021-02-23 00:00:00       0.66
2020-02-23 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2019-02-23 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-02-23 00:00:00
                 SBES1H23 Unnamed: 1
1472  2018-02-23 00:00:00      -0.01
1524  2018-02-23 00:00:00       0.19
                 SBES1K23 Unnamed: 4
1514  2018-02-23 00:00:00      -0.01
1566  2018-02-23 00:00:00      -0.11
2017-02-23 00:00:00
                 SBES1H23 Unnamed: 1
1776  2017-02-23 00:00:00       0.63
1829  2017-02-23 00:00:00       0.02
                 SBES1K23 Unnamed: 4
1818  2017-02-23 00:00:00       0.56
1871  2017-02-23 00:00:00       0.24
2016-02-23 00:00:00
                 SBES1H23 Unnamed: 1
2082  2016-02-23 00:00:00       0.23
2134  2016-02-23 00:00:00       0.13
                 SBES1K23 Unnamed: 4
2124  2016-02-23 00:00:00       0.23
2177  2016-02-23 00:00:00       0.12
2015-02-23 00:00:00
                 SBES1H23 Unnamed: 1
2386  2015-02-23 00:00:00      -0.05
2438  2015-02-23 00:00:00       0.18
                 SBES1K23 Unnamed: 4
2429  2015-02-23 00:00:00       0.06
2481  2015-02-23 00:00:00       -0.3
2014-02-23 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-02-25 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-02-25 00:00:00
                SBES1H23 Unnamed: 1
253  2022-02-25 00:00:00       0.62
306  2022-02-25 00:00:00       0.42
                SBES1K23 Unnamed: 4
295  2022-02-25 00:00:00       0.42
349  2022-02-25 00:00:00       0.13
2021-02-25 00:00:00
                SBES1H23 Unnamed: 1
559  2021-02-25 00:00:00       0.96
610  2021-02-25 00:00:00          1
                SBES1K23 Unnamed: 4
602  2021-02-25 00:00:00        0.7
654  2021-02-25 00:00:00       0.59
2020-02-25 00:00:00
                SBES1H23 Unnamed: 1
863  2020-02-25 00:00:00       0.49
916  2020-02-25 00:00:00       0.39
                SBES1K23 Unnamed: 4
907  2020-02-25 00:00:00       0.43
959  2020-02-25 00:00:00       0.12
2019-02-25 00:00:00
                 SBES1H23 Unnamed: 1
1168  2019-02-25 00:00:00      -0.02
1220  2019-02-25 00:00:00        0.1
                 SBES1K23 Unnamed: 4
1211  2019-02-25 00:00:00       0.01
1262  2019-02-25 00:00:00      -0.25
2018-02-25 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-02-25 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-02-25 00:00:00
                 SBES1H23 Unnamed: 1
2080  2016-02-25 00:00:00       0.25
2132  2016-02-25 00:00:00       0.04
                 SBES1K23 Unnamed: 4
2122  2016-02-25 00:00:00       0.23
2175  2016-02-25 00:00:00       0.14
2015-02-25 00:00:00
                 SBES1H23 Unnamed: 1
2384  2015-02-25 00:00:00      -0.08
2436  2015-02-25 00:00:00       0.02
                 SBES1K23 Unnamed: 4
2427  2015-02-25 00:00:00       0.02
2479  2015-02-25 00:00:00      -0.29
2014-02-25 00:00:00
                 SBES1H23 Unnamed: 1
2688  2014-02-25 00:00:00       0.17
2741  2014-02-25 00:00:00      -0.33
                 SBES1K23 Unnamed: 4
2731  2014-02-25 00:00:00       0.15
2783  2014-02-25 00:00:00       -0.1
2023-02-26 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-02-26 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-02-26 00:00:00
                SBES1H23 Unnamed: 1
558  2021-02-26 00:00:00       0.91
609  2021-02-26 00:00:00       1.08
                SBES1K23 Unnamed: 4
601  2021-02-26 00:00:00       0.64
653  2021-02-26 00:00:00       0.63
2020-02-26 00:00:00
                SBES1H23 Unnamed: 1
862  2020-02-26 00:00:00       0.49
915  2020-02-26 00:00:00       0.29
                SBES1K23 Unnamed: 4
906  2020-02-26 00:00:00       0.42
958  2020-02-26 00:00:00       0.08
2019-02-26 00:00:00
                 SBES1H23 Unnamed: 1
1167  2019-02-26 00:00:00      -0.04
1219  2019-02-26 00:00:00       0.04
                 SBES1K23 Unnamed: 4
1210  2019-02-26 00:00:00      -0.01
1261  2019-02-26 00:00:00      -0.23
2018-02-26 00:00:00
                 SBES1H23 Unnamed: 1
1471  2018-02-26 00:00:00      -0.02
1523  2018-02-26 00:00:00       0.22
                 SBES1K23 Unnamed: 4
1513  2018-02-26 00:00:00      -0.04
1565  2018-02-26 00:00:00       -0.1
2017-02-26 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-02-26 00:00:00
                 SBES1H23 Unnamed: 1
2079  2016-02-26 00:00:00       0.24
2131  2016-02-26 00:00:00      -0.09
                 SBES1K23 Unnamed: 4
2121  2016-02-26 00:00:00       0.25
2174  2016-02-26 00:00:00       0.09
2015-02-26 00:00:00
                 SBES1H23 Unnamed: 1
2383  2015-02-26 00:00:00      -0.04
2435  2015-02-26 00:00:00       0.05
                 SBES1K23 Unnamed: 4
2426  2015-02-26 00:00:00       0.04
2478  2015-02-26 00:00:00      -0.25
2014-02-26 00:00:00
                 SBES1H23 Unnamed: 1
2687  2014-02-26 00:00:00       0.19
2740  2014-02-26 00:00:00      -0.35
                 SBES1K23 Unnamed: 4
2730  2014-02-26 00:00:00       0.16
2782  2014-02-26 00:00:00      -0.07
2023-02-27 00:00:00
              SBES1H23 Unnamed: 1
2  2023-02-27 00:00:00       1.82
               SBES1K23 Unnamed: 4
44  2023-02-27 00:00:00       0.59
2022-02-27 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-02-27 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-02-27 00:00:00
                SBES1H23 Unnamed: 1
861  2020-02-27 00:00:00       0.44
914  2020-02-27 00:00:00       0.18
                SBES1K23 Unnamed: 4
905  2020-02-27 00:00:00       0.39
957  2020-02-27 00:00:00       0.05
2019-02-27 00:00:00
                 SBES1H23 Unnamed: 1
1166  2019-02-27 00:00:00      -0.04
1218  2019-02-27 00:00:00      -0.06
                 SBES1K23 Unnamed: 4
1209  2019-02-27 00:00:00      -0.01
1260  2019-02-27 00:00:00      -0.25
2018-02-27 00:00:00
                 SBES1H23 Unnamed: 1
1470  2018-02-27 00:00:00      -0.06
1522  2018-02-27 00:00:00       0.13
                 SBES1K23 Unnamed: 4
1512  2018-02-27 00:00:00      -0.06
1564  2018-02-27 00:00:00      -0.17
2017-02-27 00:00:00
                 SBES1H23 Unnamed: 1
1774  2017-02-27 00:00:00       0.49
1827  2017-02-27 00:00:00      -0.04
                 SBES1K23 Unnamed: 4
1816  2017-02-27 00:00:00       0.45
1869  2017-02-27 00:00:00       0.12
2016-02-27 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2015-02-27 00:00:00
                 SBES1H23 Unnamed: 1
2382  2015-02-27 00:00:00      -0.06
2434  2015-02-27 00:00:00       0.17
                 SBES1K23 Unnamed: 4
2425  2015-02-27 00:00:00       0.06
2477  2015-02-27 00:00:00      -0.27
2014-02-27 00:00:00
                 SBES1H23 Unnamed: 1
2686  2014-02-27 00:00:00        0.2
2739  2014-02-27 00:00:00      -0.63
                 SBES1K23 Unnamed: 4
2729  2014-02-27 00:00:00       0.15
2781  2014-02-27 00:00:00      -0.01
2023-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-01 00:00:00
               SBES1H23 Unnamed: 1
81  2022-11-01 00:00:00       1.04
                SBES1K23 Unnamed: 4
123  2022-11-01 00:00:00       0.58
2021-11-01 00:00:00
                SBES1H23 Unnamed: 1
386  2021-11-01 00:00:00       0.28
                SBES1K23 Unnamed: 4
429  2021-11-01 00:00:00       0.31
2020-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2019-11-01 00:00:00
                SBES1H23 Unnamed: 1
993  2019-11-01 00:00:00      -0.13
                 SBES1K23 Unnamed: 4
1036  2019-11-01 00:00:00      -0.13
2018-11-01 00:00:00
                 SBES1H23 Unnamed: 1
1297  2018-11-01 00:00:00      -0.09
                 SBES1K23 Unnamed: 4

In [21]:
df_wynik

          Date  cena_flaja1  cena_flaja2
0   2023-04-01          NaN          NaN
1   2022-04-01         0.24          NaN
2   2021-04-01         0.18          NaN
3   2020-04-01         0.01          NaN
4   2019-04-01        -0.03          NaN
..         ...          ...          ...
235 2018-11-14        -0.04          NaN
236 2017-11-14        -0.01          NaN
237 2016-11-14        -0.17          NaN
238 2015-11-14          NaN          NaN
239 2014-11-14        -0.11          NaN

[240 rows x 3 columns]

In [22]:

df_wynik['Date'] = pd.to_datetime(df_wynik['Date'])  # Konwersja kolumny 'Date' na format daty

df_wynik['Year'] = df_wynik['Date'].dt.year
df_wynik['Rest_of_Date'] = df_wynik['Date'].dt.strftime('%m-%d')  # Pozostawienie tylko części miesiąca i dnia

In [23]:
df_wynik

          Date  cena_flaja1  cena_flaja2  Year Rest_of_Date
0   2023-04-01          NaN          NaN  2023        04-01
1   2022-04-01         0.24          NaN  2022        04-01
2   2021-04-01         0.18          NaN  2021        04-01
3   2020-04-01         0.01          NaN  2020        04-01
4   2019-04-01        -0.03          NaN  2019        04-01
..         ...          ...          ...   ...          ...
235 2018-11-14        -0.04          NaN  2018        11-14
236 2017-11-14        -0.01          NaN  2017        11-14
237 2016-11-14        -0.17          NaN  2016        11-14
238 2015-11-14          NaN          NaN  2015        11-14
239 2014-11-14        -0.11          NaN  2014        11-14

[240 rows x 5 columns]

In [24]:
df_wynik['Date'] = pd.to_datetime(df_wynik['Date'])
april_data = df_wynik[df_wynik['Date'].dt.month == 4]

# Oblicz średnią, medianę, wartość maksymalną i minimalną kwecień
mean_april_price = april_data['cena_flaja1'].mean()
median_april_price = april_data['cena_flaja1'].median()
max_april_price = april_data['cena_flaja1'].max()
min_april_price = april_data['cena_flaja1'].min()

df_wynik['Date'] = pd.to_datetime(df_wynik['Date'])
luty_data = df_wynik[df_wynik['Date'].dt.month == 2]

# Oblicz średnią, medianę, wartość maksymalną i minimalną luty
mean_luty_price = luty_data['cena_flaja1'].mean()
median_luty_price = luty_data['cena_flaja1'].median()
max_luty_price = luty_data['cena_flaja1'].max()
min_luty_price = luty_data['cena_flaja1'].min()


df_wynik['Date'] = pd.to_datetime(df_wynik['Date'])
listopad_data = df_wynik[df_wynik['Date'].dt.month == 11]

# Oblicz średnią, medianę, wartość maksymalną i minimalną listopad
mean_listopad_price = listopad_data['cena_flaja1'].mean()
median_listopad_price = listopad_data['cena_flaja1'].median()
max_listopad_price = listopad_data['cena_flaja1'].max()
min_listopad_price = listopad_data['cena_flaja1'].min()

In [25]:
data1 = {
    'Miesiąc': ['Kwiecień', 'Luty', "Listopad"],
    'Średnia': [mean_april_price, mean_luty_price, mean_listopad_price],
    'Mediana': [median_april_price, median_luty_price, median_listopad_price],
    'Wartość maksymalna': [max_april_price, max_luty_price, max_listopad_price],
    'Wartość minimalna': [min_april_price, min_luty_price, min_listopad_price]
}

df_wynik1 = pd.DataFrame(data1)
df_wynik1.set_index('Miesiąc', inplace=True)  # Ustawienie kolumny "Miesiąc" jako indeksu

print(df_wynik1)

           Średnia  Mediana  Wartość maksymalna  Wartość minimalna
Miesiąc
Kwiecień  0.010345    -0.03                0.25              -0.11
Luty      0.132222     0.04                1.23              -0.12
Listopad  0.038889    -0.01                0.46              -0.17

In [ ]:
#DOCELOWA TABELA MA ZAWIERAĆ WSZYSTKIE MIESIACE. JESZCZE MOŻNA DOAĆ ROZRZUT I INEN MIARY STATYSTYCZNE. I PROGRAM MA WYRZUCAC TAKEI TABELA DLA KAZDEGO RYNKU. HITING, KAWA BRENT/LIGHT ITD.

In [26]:
df_wynik1

           Średnia  Mediana  Wartość maksymalna  Wartość minimalna
Miesiąc
Kwiecień  0.010345    -0.03                0.25              -0.11
Luty      0.132222     0.04                1.23              -0.12
Listopad  0.038889    -0.01                0.46              -0.17

In [ ]:
#WYKRESY Z DUPY

In [12]:
import plotly.express as px

In [27]:
fig_bar = px.bar(df_wynik1, x=df_wynik1.index, y=df_wynik1.columns, barmode='group', title='Statystyki dla różnych miesięcy')

fig_scatter = px.scatter(df_wynik1.reset_index(), x='Miesiąc', y=['Średnia', 'Mediana', 'Wartość maksymalna', 'Wartość minimalna'],
                         title='Statystyki dla różnych miesięcy', labels={'value': 'Wartość', 'variable': 'Statystyka'})

# Wykres pudełkowy (box plot)
fig_box = px.box(df_wynik1.reset_index().melt(id_vars='Miesiąc'), x='Miesiąc', y='value', color='variable', title='Statystyki dla różnych miesięcy')

fig_bar.show()
fig_scatter.show()
fig_box.show()

In [28]:
days_of_month = ["02-24", "02-25", "02-26", "02-27"]
wynik_dict = {"Date": [], "cena_flaja1": [], "cena_flaja2": []}

for day_month in days_of_month:
    temp_dict = {"Date": [], "cena_flaja1": [], "cena_flaja2": []}

    for year in [2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014]:
        specyfic_date = str(year) + "-" + day_month
        specyfic_date = datetime.datetime.strptime(specyfic_date, '%Y-%m-%d')
        print(specyfic_date)

        df_row1 = df1[df1["SBES1H23"] == specyfic_date]
        print(df_row1)

        df_row2 = df2[df2["SBES1K23"] == specyfic_date]
        print(df_row2)

        cena_flaja = []
        for i, value in enumerate(df_row1['Unnamed: 1'].values):
            roznica = value - df_row2["Unnamed: 4"].values[i]
            cena_flaja.append(roznica)

        if len(cena_flaja) == 1:
            temp_dict["Date"].append(specyfic_date)
            temp_dict["cena_flaja1"].append(cena_flaja[0])
            temp_dict["cena_flaja2"].append(np.nan)
        elif len(cena_flaja) == 2:
            temp_dict["Date"].append(specyfic_date)
            temp_dict["cena_flaja1"].append(cena_flaja[0])
            temp_dict["cena_flaja2"].append(cena_flaja[1])
        else:
            temp_dict["Date"].append(specyfic_date)
            temp_dict["cena_flaja1"].append(np.nan)
            temp_dict["cena_flaja2"].append(np.nan)

    wynik_dict["Date"].extend(temp_dict["Date"])
    wynik_dict["cena_flaja1"].extend(temp_dict["cena_flaja1"])
    wynik_dict["cena_flaja2"].extend(temp_dict["cena_flaja2"])

df_wynik66 = pd.DataFrame(wynik_dict)

2023-02-24 00:00:00
              SBES1H23 Unnamed: 1
3  2023-02-24 00:00:00       1.62
               SBES1K23 Unnamed: 4
45  2023-02-24 00:00:00       0.45
2022-02-24 00:00:00
                SBES1H23 Unnamed: 1
254  2022-02-24 00:00:00       0.67
307  2022-02-24 00:00:00       0.39
                SBES1K23 Unnamed: 4
296  2022-02-24 00:00:00       0.45
350  2022-02-24 00:00:00       0.15
2021-02-24 00:00:00
                SBES1H23 Unnamed: 1
560  2021-02-24 00:00:00       0.99
611  2021-02-24 00:00:00          1
                SBES1K23 Unnamed: 4
603  2021-02-24 00:00:00       0.72
655  2021-02-24 00:00:00       0.71
2020-02-24 00:00:00
                SBES1H23 Unnamed: 1
864  2020-02-24 00:00:00        0.5
917  2020-02-24 00:00:00       0.56
                SBES1K23 Unnamed: 4
908  2020-02-24 00:00:00       0.43
960  2020-02-24 00:00:00       0.14
2019-02-24 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-02-24 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-02-24 00:00:00
                 SBES1H23 Unnamed: 1
1775  2017-02-24 00:00:00       0.57
1828  2017-02-24 00:00:00      -0.02
                 SBES1K23 Unnamed: 4
1817  2017-02-24 00:00:00       0.53
1870  2017-02-24 00:00:00       0.23
2016-02-24 00:00:00
                 SBES1H23 Unnamed: 1
2081  2016-02-24 00:00:00       0.23
2133  2016-02-24 00:00:00       0.05
                 SBES1K23 Unnamed: 4
2123  2016-02-24 00:00:00       0.23
2176  2016-02-24 00:00:00        0.1
2015-02-24 00:00:00
                 SBES1H23 Unnamed: 1
2385  2015-02-24 00:00:00      -0.07
2437  2015-02-24 00:00:00       0.03
                 SBES1K23 Unnamed: 4
2428  2015-02-24 00:00:00       0.02
2480  2015-02-24 00:00:00      -0.28
2014-02-24 00:00:00
                 SBES1H23 Unnamed: 1
2689  2014-02-24 00:00:00       0.22
2742  2014-02-24 00:00:00      -0.24
                 SBES1K23 Unnamed: 4
2732  2014-02-24 00:00:00       0.17
2784  2014-02-24 00:00:00      -0.09
2023-02-25 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-02-25 00:00:00
                SBES1H23 Unnamed: 1
253  2022-02-25 00:00:00       0.62
306  2022-02-25 00:00:00       0.42
                SBES1K23 Unnamed: 4
295  2022-02-25 00:00:00       0.42
349  2022-02-25 00:00:00       0.13
2021-02-25 00:00:00
                SBES1H23 Unnamed: 1
559  2021-02-25 00:00:00       0.96
610  2021-02-25 00:00:00          1
                SBES1K23 Unnamed: 4
602  2021-02-25 00:00:00        0.7
654  2021-02-25 00:00:00       0.59
2020-02-25 00:00:00
                SBES1H23 Unnamed: 1
863  2020-02-25 00:00:00       0.49
916  2020-02-25 00:00:00       0.39
                SBES1K23 Unnamed: 4
907  2020-02-25 00:00:00       0.43
959  2020-02-25 00:00:00       0.12
2019-02-25 00:00:00
                 SBES1H23 Unnamed: 1
1168  2019-02-25 00:00:00      -0.02
1220  2019-02-25 00:00:00        0.1
                 SBES1K23 Unnamed: 4
1211  2019-02-25 00:00:00       0.01
1262  2019-02-25 00:00:00      -0.25
2018-02-25 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-02-25 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-02-25 00:00:00
                 SBES1H23 Unnamed: 1
2080  2016-02-25 00:00:00       0.25
2132  2016-02-25 00:00:00       0.04
                 SBES1K23 Unnamed: 4
2122  2016-02-25 00:00:00       0.23
2175  2016-02-25 00:00:00       0.14
2015-02-25 00:00:00
                 SBES1H23 Unnamed: 1
2384  2015-02-25 00:00:00      -0.08
2436  2015-02-25 00:00:00       0.02
                 SBES1K23 Unnamed: 4
2427  2015-02-25 00:00:00       0.02
2479  2015-02-25 00:00:00      -0.29
2014-02-25 00:00:00
                 SBES1H23 Unnamed: 1
2688  2014-02-25 00:00:00       0.17
2741  2014-02-25 00:00:00      -0.33
                 SBES1K23 Unnamed: 4
2731  2014-02-25 00:00:00       0.15
2783  2014-02-25 00:00:00       -0.1
2023-02-26 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-02-26 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-02-26 00:00:00
                SBES1H23 Unnamed: 1
558  2021-02-26 00:00:00       0.91
609  2021-02-26 00:00:00       1.08
                SBES1K23 Unnamed: 4
601  2021-02-26 00:00:00       0.64
653  2021-02-26 00:00:00       0.63
2020-02-26 00:00:00
                SBES1H23 Unnamed: 1
862  2020-02-26 00:00:00       0.49
915  2020-02-26 00:00:00       0.29
                SBES1K23 Unnamed: 4
906  2020-02-26 00:00:00       0.42
958  2020-02-26 00:00:00       0.08
2019-02-26 00:00:00
                 SBES1H23 Unnamed: 1
1167  2019-02-26 00:00:00      -0.04
1219  2019-02-26 00:00:00       0.04
                 SBES1K23 Unnamed: 4
1210  2019-02-26 00:00:00      -0.01
1261  2019-02-26 00:00:00      -0.23
2018-02-26 00:00:00
                 SBES1H23 Unnamed: 1
1471  2018-02-26 00:00:00      -0.02
1523  2018-02-26 00:00:00       0.22
                 SBES1K23 Unnamed: 4
1513  2018-02-26 00:00:00      -0.04
1565  2018-02-26 00:00:00       -0.1
2017-02-26 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-02-26 00:00:00
                 SBES1H23 Unnamed: 1
2079  2016-02-26 00:00:00       0.24
2131  2016-02-26 00:00:00      -0.09
                 SBES1K23 Unnamed: 4
2121  2016-02-26 00:00:00       0.25
2174  2016-02-26 00:00:00       0.09
2015-02-26 00:00:00
                 SBES1H23 Unnamed: 1
2383  2015-02-26 00:00:00      -0.04
2435  2015-02-26 00:00:00       0.05
                 SBES1K23 Unnamed: 4
2426  2015-02-26 00:00:00       0.04
2478  2015-02-26 00:00:00      -0.25
2014-02-26 00:00:00
                 SBES1H23 Unnamed: 1
2687  2014-02-26 00:00:00       0.19
2740  2014-02-26 00:00:00      -0.35
                 SBES1K23 Unnamed: 4
2730  2014-02-26 00:00:00       0.16
2782  2014-02-26 00:00:00      -0.07
2023-02-27 00:00:00
              SBES1H23 Unnamed: 1
2  2023-02-27 00:00:00       1.82
               SBES1K23 Unnamed: 4
44  2023-02-27 00:00:00       0.59
2022-02-27 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-02-27 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-02-27 00:00:00
                SBES1H23 Unnamed: 1
861  2020-02-27 00:00:00       0.44
914  2020-02-27 00:00:00       0.18
                SBES1K23 Unnamed: 4
905  2020-02-27 00:00:00       0.39
957  2020-02-27 00:00:00       0.05
2019-02-27 00:00:00
                 SBES1H23 Unnamed: 1
1166  2019-02-27 00:00:00      -0.04
1218  2019-02-27 00:00:00      -0.06
                 SBES1K23 Unnamed: 4
1209  2019-02-27 00:00:00      -0.01
1260  2019-02-27 00:00:00      -0.25
2018-02-27 00:00:00
                 SBES1H23 Unnamed: 1
1470  2018-02-27 00:00:00      -0.06
1522  2018-02-27 00:00:00       0.13
                 SBES1K23 Unnamed: 4
1512  2018-02-27 00:00:00      -0.06
1564  2018-02-27 00:00:00      -0.17
2017-02-27 00:00:00
                 SBES1H23 Unnamed: 1
1774  2017-02-27 00:00:00       0.49
1827  2017-02-27 00:00:00      -0.04
                 SBES1K23 Unnamed: 4
1816  2017-02-27 00:00:00       0.45
1869  2017-02-27 00:00:00       0.12
2016-02-27 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2015-02-27 00:00:00
                 SBES1H23 Unnamed: 1
2382  2015-02-27 00:00:00      -0.06
2434  2015-02-27 00:00:00       0.17
                 SBES1K23 Unnamed: 4
2425  2015-02-27 00:00:00       0.06
2477  2015-02-27 00:00:00      -0.27
2014-02-27 00:00:00
                 SBES1H23 Unnamed: 1
2686  2014-02-27 00:00:00        0.2
2739  2014-02-27 00:00:00      -0.63
                 SBES1K23 Unnamed: 4
2729  2014-02-27 00:00:00       0.15
2781  2014-02-27 00:00:00      -0.01

In [ ]:
# przy niektórych datach pojawiaja sie 2 ceny. jedna jedna gdy spred jest na bekach, druga na froncie.. nie wime czy podzielić wtedy te wartosci przy liecznei średniej.
# czy określac cene na bekach flaja i na froncie odzielnie

In [29]:
df_wynik66

         Date  cena_flaja1  cena_flaja2
0  2023-02-24         1.17          NaN
1  2022-02-24         0.22         0.24
2  2021-02-24         0.27         0.29
3  2020-02-24         0.07         0.42
4  2019-02-24          NaN          NaN
5  2018-02-24          NaN          NaN
6  2017-02-24         0.04        -0.25
7  2016-02-24         0.00        -0.05
8  2015-02-24        -0.09         0.31
9  2014-02-24         0.05        -0.15
10 2023-02-25          NaN          NaN
11 2022-02-25         0.20         0.29
12 2021-02-25         0.26         0.41
13 2020-02-25         0.06         0.27
14 2019-02-25        -0.03         0.35
15 2018-02-25          NaN          NaN
16 2017-02-25          NaN          NaN
17 2016-02-25         0.02        -0.10
18 2015-02-25        -0.10         0.31
19 2014-02-25         0.02        -0.23
20 2023-02-26          NaN          NaN
21 2022-02-26          NaN          NaN
22 2021-02-26         0.27         0.45
23 2020-02-26         0.07         0.21
24 2019-02-26        -0.03         0.27
25 2018-02-26         0.02         0.32
26 2017-02-26          NaN          NaN
27 2016-02-26        -0.01        -0.18
28 2015-02-26        -0.08         0.30
29 2014-02-26         0.03        -0.28
30 2023-02-27         1.23          NaN
31 2022-02-27          NaN          NaN
32 2021-02-27          NaN          NaN
33 2020-02-27         0.05         0.13
34 2019-02-27        -0.03         0.19
35 2018-02-27         0.00         0.30
36 2017-02-27         0.04        -0.16
37 2016-02-27          NaN          NaN
38 2015-02-27        -0.12         0.44
39 2014-02-27         0.05        -0.62