<a href="https://colab.research.google.com/github/tomektom10/dataScienceBootCamp/blob/main/proekt_cukierj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
df = pd.read_excel("Cukry_wszystkie.xlsx")
df
df.columns
import numpy as np

In [21]:
df

,SBES1H23,Unnamed: 1,Unnamed: 2,SBES1K23,Unnamed: 4,Unnamed: 5,SBES1N23,Unnamed: 7,Unnamed: 8,SBES1V23,Unnamed: 10
0,Date,C,NaN,Date,C,NaN,Date,C,NaN,Date,C
1,2023-02-28 00:00:00,2.01,NaN,2023-04-28 00:00:00,0.7,NaN,2023-06-30 00:00:00,0.1,NaN,2023-09-29 00:00:00,-0.25
2,2023-02-27 00:00:00,1.82,NaN,2023-04-27 00:00:00,0.56,NaN,2023-06-29 00:00:00,-0.01,NaN,2023-09-28 00:00:00,-0.26
3,2023-02-24 00:00:00,1.62,NaN,2023-04-26 00:00:00,0.7,NaN,2023-06-28 00:00:00,-0.02,NaN,2023-09-27 00:00:00,-0.27
4,2023-02-23 00:00:00,1.27,NaN,2023-04-25 00:00:00,0.67,NaN,2023-06-27 00:00:00,0.02,NaN,2023-09-26 00:00:00,-0.23
...,...,...,...,...,...,...,...,...,...,...,...
3033,2012-12-26 00:00:00,0.1,NaN,2013-02-27 00:00:00,-0.11,NaN,2013-04-29 00:00:00,-0.26,NaN,2013-07-30 00:00:00,-0.43
3034,2012-12-24 00:00:00,0.12,NaN,2013-02-26 00:00:00,-0.09,NaN,2013-04-26 00:00:00,-0.27,NaN,2013-07-29 00:00:00,-0.43
3035,2012-12-21 00:00:00,0.1,NaN,2013-02-25 00:00:00,-0.12,NaN,2013-04-25 00:00:00,-0.27,NaN,2013-07-26 00:00:00,-0.46
3036,2012-12-20 00:00:00,0.11,NaN,2013-02-22 00:00:00,-0.14,NaN,2013-04-24 00:00:00,-0.25,NaN,2013-07-25 00:00:00,-0.44
3037,2012-12-19 00:00:00,0.11,NaN,2013-02-21 00:00:00,-0.16,NaN,2013-04-23 00:00:00,-0.19,NaN,2013-07-24 00:00:00,-0.46

In [22]:
df1 = df[["SBES1H23", "Unnamed: 1"]].iloc[1:]
df1

                 SBES1H23 Unnamed: 1
1     2023-02-28 00:00:00       2.01
2     2023-02-27 00:00:00       1.82
3     2023-02-24 00:00:00       1.62
4     2023-02-23 00:00:00       1.27
5     2023-02-22 00:00:00       1.39
...                   ...        ...
3033  2012-12-26 00:00:00        0.1
3034  2012-12-24 00:00:00       0.12
3035  2012-12-21 00:00:00        0.1
3036  2012-12-20 00:00:00       0.11
3037  2012-12-19 00:00:00       0.11

[3037 rows x 2 columns]

In [23]:
df2 = df[["SBES1K23", "Unnamed: 4"]].iloc[1:]
df2
import datetime

In [24]:
day_month = "01-24"
wynik_dict = {"Date":[], "cena_flaja1":[] }
for year in [2023, 2022, 2021, 2020]:
  specyfic_date = str(year) + "-" + day_month
  specyfic_date = datetime.datetime.strptime(specyfic_date, '%Y-%m-%d')
  print(specyfic_date)
  df_row1 = df1[df1["SBES1H23"] == specyfic_date]
  print(df_row1)

  df_row2 = df2[df2["SBES1K23"] == specyfic_date]
  print(df_row2)
  cena_flaja = []
  if len(df_row1) > 0 and len(df_row2) >0:

    value = df_row1['Unnamed: 1'].values[0]
    cena_flaja = value - df_row2["Unnamed: 4"].values[0]


    wynik_dict["Date"].append(specyfic_date)
    wynik_dict["cena_flaja1"].append(cena_flaja)


df_wynik = pd.DataFrame(wynik_dict)

2023-01-24 00:00:00
               SBES1H23 Unnamed: 1
25  2023-01-24 00:00:00       1.25
               SBES1K23 Unnamed: 4
67  2023-01-24 00:00:00       0.64
2022-01-24 00:00:00
                SBES1H23 Unnamed: 1
276  2022-01-24 00:00:00       0.84
329  2022-01-24 00:00:00       0.34
                SBES1K23 Unnamed: 4
372  2022-01-24 00:00:00       0.23
2021-01-24 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-01-24 00:00:00
                SBES1H23 Unnamed: 1
884  2020-01-24 00:00:00       0.28
937  2020-01-24 00:00:00       0.07
                SBES1K23 Unnamed: 4
980  2020-01-24 00:00:00       0.07

In [25]:
def oblicz_ceny_flaja(df1, df2, kod1, kod2, cena1, cena2, day_month):

  wynik_dict = {"Date":[], "cena_flaja1":[] }
  df_wynik = pd.DataFrame()
  for year in [2023, 2022, 2021, 2020]:
    specyfic_date = str(year) + "-" + day_month
    specyfic_date = datetime.datetime.strptime(specyfic_date, '%Y-%m-%d')
    print(specyfic_date)
    df_row1 = df1[df1[kod1] == specyfic_date]
    print(df_row1)

    df_row2 = df2[df2[kod2] == specyfic_date]
    print(df_row2)
    cena_flaja = []
    if len(df_row1) > 0 and len(df_row2) >0:

      value = df_row1[cena1].values[0]
      cena_flaja = value - df_row2[cena2].values[0]


      wynik_dict["Date"].append(specyfic_date)
      wynik_dict["cena_flaja1"].append(cena_flaja)


      df_wynik = pd.DataFrame(wynik_dict)
  return df_wynik

In [26]:
oblicz_ceny_flaja(df1, df2, "SBES1H23" , "SBES1K23" , "Unnamed: 1", "Unnamed: 4", "02-11" )

2023-02-11 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-02-11 00:00:00
                SBES1H23 Unnamed: 1
262  2022-02-11 00:00:00       0.65
315  2022-02-11 00:00:00       0.47
                SBES1K23 Unnamed: 4
358  2022-02-11 00:00:00       0.07
2021-02-11 00:00:00
                SBES1H23 Unnamed: 1
568  2021-02-11 00:00:00       0.86
619  2021-02-11 00:00:00       0.73
                SBES1K23 Unnamed: 4
663  2021-02-11 00:00:00       0.52
2020-02-11 00:00:00
                SBES1H23 Unnamed: 1
872  2020-02-11 00:00:00        0.6
925  2020-02-11 00:00:00       0.37
                SBES1K23 Unnamed: 4
968  2020-02-11 00:00:00       0.13

        Date  cena_flaja1
0 2022-02-11         0.58
1 2021-02-11         0.34
2 2020-02-11         0.47

In [27]:
import calendar
month = "02"

In [28]:
def create_days_for_month(month, year = 2023):
  numdays = calendar.monthrange(year, int(month))[-1]
  print(calendar.monthrange(year, int(month)))
  days_list = [f'{month}-{day:02d}' for day in range(1, numdays + 1)]
  return days_list

In [29]:
create_days_for_month("03")

(2, 31)

['03-01',
 '03-02',
 '03-03',
 '03-04',
 '03-05',
 '03-06',
 '03-07',
 '03-08',
 '03-09',
 '03-10',
 '03-11',
 '03-12',
 '03-13',
 '03-14',
 '03-15',
 '03-16',
 '03-17',
 '03-18',
 '03-19',
 '03-20',
 '03-21',
 '03-22',
 '03-23',
 '03-24',
 '03-25',
 '03-26',
 '03-27',
 '03-28',
 '03-29',
 '03-30',
 '03-31']

In [30]:
days_list = create_days_for_month("03")

(2, 31)

In [31]:
srednia_df = []
for month_day in days_list:
 df= oblicz_ceny_flaja(df1, df2, "SBES1H23" , "SBES1K23" , "Unnamed: 1", "Unnamed: 4", month_day )
 srednia_df.append({"month_day": month_day, "cena_flaja_srednia": df["cena_flaja1"].mean()})

2023-03-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
42  2023-03-01 00:00:00       0.55
2022-03-01 00:00:00
                SBES1H23 Unnamed: 1
251  2022-03-01 00:00:00       0.64
                SBES1K23 Unnamed: 4
293  2022-03-01 00:00:00       0.45
347  2022-03-01 00:00:00       0.19
2021-03-01 00:00:00
                SBES1H23 Unnamed: 1
557  2021-03-01 00:00:00       0.84
                SBES1K23 Unnamed: 4
600  2021-03-01 00:00:00       0.59
652  2021-03-01 00:00:00       0.51
2020-03-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-03-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
41  2023-03-02 00:00:00       0.55
2022-03-02 00:00:00
                SBES1H23 Unnamed: 1
250  2022-03-02 00:00:00       0.74
                SBES1K23 Unnamed: 4
292  2022-03-02 00:00:00       0.51
346  2022-03-02 00:00:00       0.17
2021-03-02 00:00:00
                SBES1H23 Unnamed: 1
556  2021-03-02 00:00:00       0.89
                SBES1K23 Unnamed: 4
599  2021-03-02 00:00:00       0.62
651  2021-03-02 00:00:00        0.6
2020-03-02 00:00:00
                SBES1H23 Unnamed: 1
859  2020-03-02 00:00:00        0.4
                SBES1K23 Unnamed: 4
903  2020-03-02 00:00:00       0.31
955  2020-03-02 00:00:00          0
2023-03-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
40  2023-03-03 00:00:00       0.68
2022-03-03 00:00:00
                SBES1H23 Unnamed: 1
249  2022-03-03 00:00:00       0.77
                SBES1K23 Unnamed: 4
291  2022-03-03 00:00:00       0.52
345  2022-03-03 00:00:00       0.21
2021-03-03 00:00:00
                SBES1H23 Unnamed: 1
555  2021-03-03 00:00:00       0.85
                SBES1K23 Unnamed: 4
598  2021-03-03 00:00:00        0.6
650  2021-03-03 00:00:00       0.51
2020-03-03 00:00:00
                SBES1H23 Unnamed: 1
858  2020-03-03 00:00:00       0.36
                SBES1K23 Unnamed: 4
902  2020-03-03 00:00:00        0.3
954  2020-03-03 00:00:00       0.02
2023-03-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-03-04 00:00:00
                SBES1H23 Unnamed: 1
248  2022-03-04 00:00:00       0.91
                SBES1K23 Unnamed: 4
290  2022-03-04 00:00:00       0.58
344  2022-03-04 00:00:00       0.26
2021-03-04 00:00:00
                SBES1H23 Unnamed: 1
554  2021-03-04 00:00:00       0.83
                SBES1K23 Unnamed: 4
597  2021-03-04 00:00:00       0.61
649  2021-03-04 00:00:00       0.56
2020-03-04 00:00:00
                SBES1H23 Unnamed: 1
857  2020-03-04 00:00:00       0.37
                SBES1K23 Unnamed: 4
901  2020-03-04 00:00:00       0.28
953  2020-03-04 00:00:00          0
2023-03-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-03-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-03-05 00:00:00
                SBES1H23 Unnamed: 1
553  2021-03-05 00:00:00       0.83
                SBES1K23 Unnamed: 4
596  2021-03-05 00:00:00       0.63
648  2021-03-05 00:00:00       0.55
2020-03-05 00:00:00
                SBES1H23 Unnamed: 1
856  2020-03-05 00:00:00       0.41
                SBES1K23 Unnamed: 4
900  2020-03-05 00:00:00       0.32
952  2020-03-05 00:00:00       0.04
2023-03-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
39  2023-03-06 00:00:00       0.64
2022-03-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-03-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-03-06 00:00:00
                SBES1H23 Unnamed: 1
855  2020-03-06 00:00:00       0.35
                SBES1K23 Unnamed: 4
899  2020-03-06 00:00:00       0.27
951  2020-03-06 00:00:00      -0.01
2023-03-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
38  2023-03-07 00:00:00       0.59
2022-03-07 00:00:00
                SBES1H23 Unnamed: 1
247  2022-03-07 00:00:00       0.91
                SBES1K23 Unnamed: 4
289  2022-03-07 00:00:00       0.56
343  2022-03-07 00:00:00       0.12
2021-03-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-03-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-03-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
37  2023-03-08 00:00:00       0.57
2022-03-08 00:00:00
                SBES1H23 Unnamed: 1
246  2022-03-08 00:00:00       0.96
                SBES1K23 Unnamed: 4
288  2022-03-08 00:00:00       0.63
342  2022-03-08 00:00:00       0.12
2021-03-08 00:00:00
                SBES1H23 Unnamed: 1
552  2021-03-08 00:00:00        0.8
                SBES1K23 Unnamed: 4
595  2021-03-08 00:00:00       0.61
647  2021-03-08 00:00:00       0.48
2020-03-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-03-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
36  2023-03-09 00:00:00       0.57
2022-03-09 00:00:00
                SBES1H23 Unnamed: 1
245  2022-03-09 00:00:00       0.86
                SBES1K23 Unnamed: 4
287  2022-03-09 00:00:00       0.58
341  2022-03-09 00:00:00       0.04
2021-03-09 00:00:00
                SBES1H23 Unnamed: 1
551  2021-03-09 00:00:00       0.77
                SBES1K23 Unnamed: 4
594  2021-03-09 00:00:00       0.61
646  2021-03-09 00:00:00       0.46
2020-03-09 00:00:00
                SBES1H23 Unnamed: 1
854  2020-03-09 00:00:00       0.26
                SBES1K23 Unnamed: 4
898  2020-03-09 00:00:00       0.21
950  2020-03-09 00:00:00       0.04
2023-03-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
35  2023-03-10 00:00:00       0.56
2022-03-10 00:00:00
                SBES1H23 Unnamed: 1
244  2022-03-10 00:00:00       0.89
                SBES1K23 Unnamed: 4
286  2022-03-10 00:00:00       0.58
340  2022-03-10 00:00:00       0.04
2021-03-10 00:00:00
                SBES1H23 Unnamed: 1
550  2021-03-10 00:00:00       0.78
                SBES1K23 Unnamed: 4
593  2021-03-10 00:00:00       0.62
645  2021-03-10 00:00:00       0.43
2020-03-10 00:00:00
                SBES1H23 Unnamed: 1
853  2020-03-10 00:00:00       0.24
                SBES1K23 Unnamed: 4
897  2020-03-10 00:00:00       0.19
949  2020-03-10 00:00:00       0.04
2023-03-11 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-03-11 00:00:00
                SBES1H23 Unnamed: 1
243  2022-03-11 00:00:00       0.91
                SBES1K23 Unnamed: 4
285  2022-03-11 00:00:00        0.6
339  2022-03-11 00:00:00       0.06
2021-03-11 00:00:00
                SBES1H23 Unnamed: 1
549  2021-03-11 00:00:00       0.78
                SBES1K23 Unnamed: 4
592  2021-03-11 00:00:00       0.62
644  2021-03-11 00:00:00       0.48
2020-03-11 00:00:00
                SBES1H23 Unnamed: 1
852  2020-03-11 00:00:00       0.23
                SBES1K23 Unnamed: 4
896  2020-03-11 00:00:00       0.17
948  2020-03-11 00:00:00       0.01
2023-03-12 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-03-12 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-03-12 00:00:00
                SBES1H23 Unnamed: 1
548  2021-03-12 00:00:00       0.74
                SBES1K23 Unnamed: 4
591  2021-03-12 00:00:00       0.57
643  2021-03-12 00:00:00       0.41
2020-03-12 00:00:00
                SBES1H23 Unnamed: 1
851  2020-03-12 00:00:00       0.18
                SBES1K23 Unnamed: 4
895  2020-03-12 00:00:00       0.14
947  2020-03-12 00:00:00      -0.02
2023-03-13 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
34  2023-03-13 00:00:00       0.53
2022-03-13 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-03-13 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-03-13 00:00:00
                SBES1H23 Unnamed: 1
850  2020-03-13 00:00:00       0.17
                SBES1K23 Unnamed: 4
894  2020-03-13 00:00:00       0.13
946  2020-03-13 00:00:00       0.06
2023-03-14 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
33  2023-03-14 00:00:00       0.51
2022-03-14 00:00:00
                SBES1H23 Unnamed: 1
242  2022-03-14 00:00:00       0.87
                SBES1K23 Unnamed: 4
284  2022-03-14 00:00:00        0.6
338  2022-03-14 00:00:00       0.03
2021-03-14 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-03-14 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-03-15 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
32  2023-03-15 00:00:00       0.51
2022-03-15 00:00:00
                SBES1H23 Unnamed: 1
241  2022-03-15 00:00:00       0.81
                SBES1K23 Unnamed: 4
283  2022-03-15 00:00:00       0.58
337  2022-03-15 00:00:00       0.06
2021-03-15 00:00:00
                SBES1H23 Unnamed: 1
547  2021-03-15 00:00:00       0.75
                SBES1K23 Unnamed: 4
590  2021-03-15 00:00:00        0.6
642  2021-03-15 00:00:00        0.4
2020-03-15 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-03-16 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
31  2023-03-16 00:00:00       0.52
2022-03-16 00:00:00
                SBES1H23 Unnamed: 1
240  2022-03-16 00:00:00       0.76
                SBES1K23 Unnamed: 4
282  2022-03-16 00:00:00       0.55
336  2022-03-16 00:00:00       0.07
2021-03-16 00:00:00
                SBES1H23 Unnamed: 1
546  2021-03-16 00:00:00       0.76
                SBES1K23 Unnamed: 4
589  2021-03-16 00:00:00       0.61
641  2021-03-16 00:00:00       0.41
2020-03-16 00:00:00
                SBES1H23 Unnamed: 1
849  2020-03-16 00:00:00       0.11
                SBES1K23 Unnamed: 4
893  2020-03-16 00:00:00       0.08
945  2020-03-16 00:00:00       0.04
2023-03-17 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
30  2023-03-17 00:00:00       0.52
2022-03-17 00:00:00
                SBES1H23 Unnamed: 1
239  2022-03-17 00:00:00       0.78
                SBES1K23 Unnamed: 4
281  2022-03-17 00:00:00       0.59
335  2022-03-17 00:00:00       0.07
2021-03-17 00:00:00
                SBES1H23 Unnamed: 1
545  2021-03-17 00:00:00       0.76
                SBES1K23 Unnamed: 4
588  2021-03-17 00:00:00       0.62
640  2021-03-17 00:00:00       0.32
2020-03-17 00:00:00
                SBES1H23 Unnamed: 1
848  2020-03-17 00:00:00       0.08
                SBES1K23 Unnamed: 4
892  2020-03-17 00:00:00       0.05
944  2020-03-17 00:00:00       0.03
2023-03-18 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-03-18 00:00:00
                SBES1H23 Unnamed: 1
238  2022-03-18 00:00:00       0.76
                SBES1K23 Unnamed: 4
280  2022-03-18 00:00:00       0.59
334  2022-03-18 00:00:00       0.11
2021-03-18 00:00:00
                SBES1H23 Unnamed: 1
544  2021-03-18 00:00:00        0.7
                SBES1K23 Unnamed: 4
587  2021-03-18 00:00:00       0.54
639  2021-03-18 00:00:00       0.33
2020-03-18 00:00:00
                SBES1H23 Unnamed: 1
847  2020-03-18 00:00:00       0.07
                SBES1K23 Unnamed: 4
891  2020-03-18 00:00:00       0.05
943  2020-03-18 00:00:00       0.05
2023-03-19 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-03-19 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-03-19 00:00:00
                SBES1H23 Unnamed: 1
543  2021-03-19 00:00:00       0.65
                SBES1K23 Unnamed: 4
586  2021-03-19 00:00:00        0.5
638  2021-03-19 00:00:00       0.32
2020-03-19 00:00:00
                SBES1H23 Unnamed: 1
846  2020-03-19 00:00:00       0.09
                SBES1K23 Unnamed: 4
890  2020-03-19 00:00:00       0.07
942  2020-03-19 00:00:00       0.06
2023-03-20 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
29  2023-03-20 00:00:00       0.49
2022-03-20 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-03-20 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-03-20 00:00:00
                SBES1H23 Unnamed: 1
845  2020-03-20 00:00:00       0.08
                SBES1K23 Unnamed: 4
889  2020-03-20 00:00:00       0.05
941  2020-03-20 00:00:00       0.09
2023-03-21 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
28  2023-03-21 00:00:00       0.52
2022-03-21 00:00:00
                SBES1H23 Unnamed: 1
237  2022-03-21 00:00:00       0.83
                SBES1K23 Unnamed: 4
279  2022-03-21 00:00:00       0.62
333  2022-03-21 00:00:00       0.11
2021-03-21 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-03-21 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-03-22 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
27  2023-03-22 00:00:00       0.59
2022-03-22 00:00:00
                SBES1H23 Unnamed: 1
236  2022-03-22 00:00:00       0.84
                SBES1K23 Unnamed: 4
278  2022-03-22 00:00:00        0.6
332  2022-03-22 00:00:00       0.06
2021-03-22 00:00:00
                SBES1H23 Unnamed: 1
542  2021-03-22 00:00:00       0.65
                SBES1K23 Unnamed: 4
585  2021-03-22 00:00:00        0.5
637  2021-03-22 00:00:00       0.24
2020-03-22 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-03-23 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
26  2023-03-23 00:00:00       0.51
2022-03-23 00:00:00
                SBES1H23 Unnamed: 1
235  2022-03-23 00:00:00       0.85
                SBES1K23 Unnamed: 4
277  2022-03-23 00:00:00       0.62
331  2022-03-23 00:00:00       0.06
2021-03-23 00:00:00
                SBES1H23 Unnamed: 1
541  2021-03-23 00:00:00       0.68
                SBES1K23 Unnamed: 4
584  2021-03-23 00:00:00       0.52
636  2021-03-23 00:00:00       0.25
2020-03-23 00:00:00
                SBES1H23 Unnamed: 1
844  2020-03-23 00:00:00       0.12
                SBES1K23 Unnamed: 4
888  2020-03-23 00:00:00       0.06
940  2020-03-23 00:00:00       0.15
2023-03-24 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
25  2023-03-24 00:00:00       0.48
2022-03-24 00:00:00
                SBES1H23 Unnamed: 1
234  2022-03-24 00:00:00       0.83
                SBES1K23 Unnamed: 4
276  2022-03-24 00:00:00       0.59
330  2022-03-24 00:00:00       0.08
2021-03-24 00:00:00
                SBES1H23 Unnamed: 1
540  2021-03-24 00:00:00       0.73
                SBES1K23 Unnamed: 4
583  2021-03-24 00:00:00       0.58
635  2021-03-24 00:00:00       0.22
2020-03-24 00:00:00
                SBES1H23 Unnamed: 1
843  2020-03-24 00:00:00       0.18
                SBES1K23 Unnamed: 4
887  2020-03-24 00:00:00        0.1
939  2020-03-24 00:00:00       0.16
2023-03-25 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-03-25 00:00:00
                SBES1H23 Unnamed: 1
233  2022-03-25 00:00:00       0.87
                SBES1K23 Unnamed: 4
275  2022-03-25 00:00:00       0.58
329  2022-03-25 00:00:00       0.15
2021-03-25 00:00:00
                SBES1H23 Unnamed: 1
539  2021-03-25 00:00:00       0.65
                SBES1K23 Unnamed: 4
582  2021-03-25 00:00:00       0.49
634  2021-03-25 00:00:00       0.13
2020-03-25 00:00:00
                SBES1H23 Unnamed: 1
842  2020-03-25 00:00:00       0.18
                SBES1K23 Unnamed: 4
886  2020-03-25 00:00:00       0.11
938  2020-03-25 00:00:00       0.14
2023-03-26 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-03-26 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-03-26 00:00:00
                SBES1H23 Unnamed: 1
538  2021-03-26 00:00:00        0.7
                SBES1K23 Unnamed: 4
581  2021-03-26 00:00:00       0.56
633  2021-03-26 00:00:00       0.17
2020-03-26 00:00:00
                SBES1H23 Unnamed: 1
841  2020-03-26 00:00:00        0.2
                SBES1K23 Unnamed: 4
885  2020-03-26 00:00:00       0.13
937  2020-03-26 00:00:00        0.1
2023-03-27 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
24  2023-03-27 00:00:00       0.48
2022-03-27 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-03-27 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-03-27 00:00:00
                SBES1H23 Unnamed: 1
840  2020-03-27 00:00:00       0.16
                SBES1K23 Unnamed: 4
884  2020-03-27 00:00:00       0.12
936  2020-03-27 00:00:00       0.05
2023-03-28 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
23  2023-03-28 00:00:00       0.49
2022-03-28 00:00:00
                SBES1H23 Unnamed: 1
232  2022-03-28 00:00:00       0.83
                SBES1K23 Unnamed: 4
274  2022-03-28 00:00:00       0.54
328  2022-03-28 00:00:00       0.12
2021-03-28 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-03-28 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-03-29 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
               SBES1K23 Unnamed: 4
22  2023-03-29 00:00:00       0.43
2022-03-29 00:00:00
                SBES1H23 Unnamed: 1
231  2022-03-29 00:00:00       0.77
                SBES1K23 Unnamed: 4
273  2022-03-29 00:00:00       0.53
327  2022-03-29 00:00:00        0.1
2021-03-29 00:00:00
                SBES1H23 Unnamed: 1
537  2021-03-29 00:00:00       0.66
                SBES1K23 Unnamed: 4
580  2021-03-29 00:00:00       0.54
632  2021-03-29 00:00:00       0.12
2020-03-29 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []

In [32]:
srednia_df

[{'month_day': '03-01', 'cena_flaja_srednia': 0.22},
 {'month_day': '03-02', 'cena_flaja_srednia': 0.19666666666666668},
 {'month_day': '03-03', 'cena_flaja_srednia': 0.18666666666666668},
 {'month_day': '03-04', 'cena_flaja_srednia': 0.21333333333333335},
 {'month_day': '03-05', 'cena_flaja_srednia': 0.14499999999999996},
 {'month_day': '03-06', 'cena_flaja_srednia': 0.07999999999999996},
 {'month_day': '03-07', 'cena_flaja_srednia': 0.35},
 {'month_day': '03-08', 'cena_flaja_srednia': 0.26},
 {'month_day': '03-09', 'cena_flaja_srednia': 0.16333333333333336},
 {'month_day': '03-10', 'cena_flaja_srednia': 0.17333333333333334},
 {'month_day': '03-11', 'cena_flaja_srednia': 0.17666666666666667},
 {'month_day': '03-12', 'cena_flaja_srednia': 0.10500000000000001},
 {'month_day': '03-13', 'cena_flaja_srednia': 0.04000000000000001},
 {'month_day': '03-14', 'cena_flaja_srednia': 0.27},
 {'month_day': '03-15', 'cena_flaja_srednia': 0.19000000000000006},
 {'month_day': '03-16', 'cena_flaja_srednia': 0.13},
 {'month_day': '03-17', 'cena_flaja_srednia': 0.12000000000000004},
 {'month_day': '03-18', 'cena_flaja_srednia': 0.11666666666666665},
 {'month_day': '03-19', 'cena_flaja_srednia': 0.085},
 {'month_day': '03-20', 'cena_flaja_srednia': 0.03},
 {'month_day': '03-21', 'cena_flaja_srednia': 0.20999999999999996},
 {'month_day': '03-22', 'cena_flaja_srednia': 0.195},
 {'month_day': '03-23', 'cena_flaja_srednia': 0.15},
 {'month_day': '03-24', 'cena_flaja_srednia': 0.15666666666666665},
 {'month_day': '03-25', 'cena_flaja_srednia': 0.17333333333333334},
 {'month_day': '03-26', 'cena_flaja_srednia': 0.10499999999999995},
 {'month_day': '03-27', 'cena_flaja_srednia': 0.04000000000000001},
 {'month_day': '03-28', 'cena_flaja_srednia': 0.2899999999999999},
 {'month_day': '03-29', 'cena_flaja_srednia': 0.18},
 {'month_day': '03-30', 'cena_flaja_srednia': 0.13333333333333333},
 {'month_day': '03-31', 'cena_flaja_srednia': 0.1466666666666667}]

In [33]:
pd.DataFrame(srednia_df)

   month_day  cena_flaja_srednia
0      03-01            0.220000
1      03-02            0.196667
2      03-03            0.186667
3      03-04            0.213333
4      03-05            0.145000
5      03-06            0.080000
6      03-07            0.350000
7      03-08            0.260000
8      03-09            0.163333
9      03-10            0.173333
10     03-11            0.176667
11     03-12            0.105000
12     03-13            0.040000
13     03-14            0.270000
14     03-15            0.190000
15     03-16            0.130000
16     03-17            0.120000
17     03-18            0.116667
18     03-19            0.085000
19     03-20            0.030000
20     03-21            0.210000
21     03-22            0.195000
22     03-23            0.150000
23     03-24            0.156667
24     03-25            0.173333
25     03-26            0.105000
26     03-27            0.040000
27     03-28            0.290000
28     03-29            0.180000
29     03-30            0.133333
30     03-31            0.146667

In [34]:
def oblicz_ceny_flaja_dla_miesiaca(month, df1, df2, kod1 , kod2 , ceny1, ceny2):
  days_list = create_days_for_month(month)
  srednia_df = []
  for month_day in days_list:
    df= oblicz_ceny_flaja(df1, df2, kod1 , kod2 , ceny1, ceny2, month_day )
    if len(df) > 0:
      srednia_df.append({"month_day": month_day, "cena_flaja_srednia": df["cena_flaja1"].mean()})
  return srednia_df

In [35]:
oblicz_ceny_flaja_dla_miesiaca("01", df1, df2, "SBES1H23" , "SBES1K23" , "Unnamed: 1", "Unnamed: 4" )

(6, 31)
2023-01-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-01-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-01-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-01-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-01-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-01-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-01-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-01-02 00:00:00
                SBES1H23 Unnamed: 1
899  2020-01-02 00:00:00       0.09
952  2020-01-02 00:00:00      -0.11
                SBES1K23 Unnamed: 4
995  2020-01-02 00:00:00      -0.11
2023-01-03 00:00:00
               SBES1H23 Unnamed: 1
39  2023-01-03 00:00:00       1.27
               SBES1K23 Unnamed: 4
81  2023-01-03 00:00:00       0.67
2022-01-03 00:00:00
                SBES1H23 Unnamed: 1
290  2022-01-03 00:00:00       0.81
343  2022-01-03 00:00:00       0.25
                SBES1K23 Unnamed: 4
386  2022-01-03 00:00:00       0.16
2021-01-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-01-03 00:00:00
                SBES1H23 Unnamed: 1
898  2020-01-03 00:00:00        0.1
951  2020-01-03 00:00:00      -0.07
                SBES1K23 Unnamed: 4
994  2020-01-03 00:00:00      -0.09
2023-01-04 00:00:00
               SBES1H23 Unnamed: 1
38  2023-01-04 00:00:00        1.2
               SBES1K23 Unnamed: 4
80  2023-01-04 00:00:00       0.64
2022-01-04 00:00:00
                SBES1H23 Unnamed: 1
289  2022-01-04 00:00:00       0.89
342  2022-01-04 00:00:00       0.29
                SBES1K23 Unnamed: 4
385  2022-01-04 00:00:00       0.14
2021-01-04 00:00:00
                SBES1H23 Unnamed: 1
595  2021-01-04 00:00:00       0.57
646  2021-01-04 00:00:00        0.8
                SBES1K23 Unnamed: 4
690  2021-01-04 00:00:00        0.5
2020-01-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-01-05 00:00:00
               SBES1H23 Unnamed: 1
37  2023-01-05 00:00:00       1.13
               SBES1K23 Unnamed: 4
79  2023-01-05 00:00:00       0.63
2022-01-05 00:00:00
                SBES1H23 Unnamed: 1
288  2022-01-05 00:00:00       0.84
341  2022-01-05 00:00:00       0.23
                SBES1K23 Unnamed: 4
384  2022-01-05 00:00:00       0.11
2021-01-05 00:00:00
                SBES1H23 Unnamed: 1
594  2021-01-05 00:00:00        0.7
645  2021-01-05 00:00:00       0.98
                SBES1K23 Unnamed: 4
689  2021-01-05 00:00:00       0.59
2020-01-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-01-06 00:00:00
               SBES1H23 Unnamed: 1
36  2023-01-06 00:00:00       1.04
               SBES1K23 Unnamed: 4
78  2023-01-06 00:00:00       0.57
2022-01-06 00:00:00
                SBES1H23 Unnamed: 1
287  2022-01-06 00:00:00        0.8
340  2022-01-06 00:00:00       0.28
                SBES1K23 Unnamed: 4
383  2022-01-06 00:00:00       0.16
2021-01-06 00:00:00
                SBES1H23 Unnamed: 1
593  2021-01-06 00:00:00       0.75
644  2021-01-06 00:00:00       1.03
                SBES1K23 Unnamed: 4
688  2021-01-06 00:00:00       0.63
2020-01-06 00:00:00
                SBES1H23 Unnamed: 1
897  2020-01-06 00:00:00       0.15
950  2020-01-06 00:00:00      -0.07
                SBES1K23 Unnamed: 4
993  2020-01-06 00:00:00      -0.06
2023-01-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-01-07 00:00:00
                SBES1H23 Unnamed: 1
286  2022-01-07 00:00:00       0.77
339  2022-01-07 00:00:00       0.26
                SBES1K23 Unnamed: 4
382  2022-01-07 00:00:00       0.11
2021-01-07 00:00:00
                SBES1H23 Unnamed: 1
592  2021-01-07 00:00:00       0.71
643  2021-01-07 00:00:00       0.81
                SBES1K23 Unnamed: 4
687  2021-01-07 00:00:00       0.49
2020-01-07 00:00:00
                SBES1H23 Unnamed: 1
896  2020-01-07 00:00:00       0.15
949  2020-01-07 00:00:00      -0.09
                SBES1K23 Unnamed: 4
992  2020-01-07 00:00:00      -0.09
2023-01-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-01-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-01-08 00:00:00
                SBES1H23 Unnamed: 1
591  2021-01-08 00:00:00       0.72
642  2021-01-08 00:00:00       0.81
                SBES1K23 Unnamed: 4
686  2021-01-08 00:00:00       0.42
2020-01-08 00:00:00
                SBES1H23 Unnamed: 1
895  2020-01-08 00:00:00       0.15
948  2020-01-08 00:00:00      -0.09
                SBES1K23 Unnamed: 4
991  2020-01-08 00:00:00       -0.1
2023-01-09 00:00:00
               SBES1H23 Unnamed: 1
35  2023-01-09 00:00:00       1.12
               SBES1K23 Unnamed: 4
77  2023-01-09 00:00:00       0.61
2022-01-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-01-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-01-09 00:00:00
                SBES1H23 Unnamed: 1
894  2020-01-09 00:00:00       0.16
947  2020-01-09 00:00:00      -0.05
                SBES1K23 Unnamed: 4
990  2020-01-09 00:00:00      -0.07
2023-01-10 00:00:00
               SBES1H23 Unnamed: 1
34  2023-01-10 00:00:00       1.29
               SBES1K23 Unnamed: 4
76  2023-01-10 00:00:00       0.72
2022-01-10 00:00:00
                SBES1H23 Unnamed: 1
285  2022-01-10 00:00:00       0.72
338  2022-01-10 00:00:00       0.23
                SBES1K23 Unnamed: 4
381  2022-01-10 00:00:00       0.09
2021-01-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-01-10 00:00:00
                SBES1H23 Unnamed: 1
893  2020-01-10 00:00:00        0.2
946  2020-01-10 00:00:00       0.01
                SBES1K23 Unnamed: 4
989  2020-01-10 00:00:00          0
2023-01-11 00:00:00
               SBES1H23 Unnamed: 1
33  2023-01-11 00:00:00       1.29
               SBES1K23 Unnamed: 4
75  2023-01-11 00:00:00       0.71
2022-01-11 00:00:00
                SBES1H23 Unnamed: 1
284  2022-01-11 00:00:00       0.72
337  2022-01-11 00:00:00       0.29
                SBES1K23 Unnamed: 4
380  2022-01-11 00:00:00       0.16
2021-01-11 00:00:00
                SBES1H23 Unnamed: 1
590  2021-01-11 00:00:00       0.77
641  2021-01-11 00:00:00       0.93
                SBES1K23 Unnamed: 4
685  2021-01-11 00:00:00       0.47
2020-01-11 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-01-12 00:00:00
               SBES1H23 Unnamed: 1
32  2023-01-12 00:00:00       1.26
               SBES1K23 Unnamed: 4
74  2023-01-12 00:00:00       0.68
2022-01-12 00:00:00
                SBES1H23 Unnamed: 1
283  2022-01-12 00:00:00       0.72
336  2022-01-12 00:00:00       0.26
                SBES1K23 Unnamed: 4
379  2022-01-12 00:00:00       0.19
2021-01-12 00:00:00
                SBES1H23 Unnamed: 1
589  2021-01-12 00:00:00       0.79
640  2021-01-12 00:00:00       0.85
                SBES1K23 Unnamed: 4
684  2021-01-12 00:00:00        0.4
2020-01-12 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-01-13 00:00:00
               SBES1H23 Unnamed: 1
31  2023-01-13 00:00:00        1.3
               SBES1K23 Unnamed: 4
73  2023-01-13 00:00:00       0.73
2022-01-13 00:00:00
                SBES1H23 Unnamed: 1
282  2022-01-13 00:00:00        0.7
335  2022-01-13 00:00:00       0.22
                SBES1K23 Unnamed: 4
378  2022-01-13 00:00:00       0.15
2021-01-13 00:00:00
                SBES1H23 Unnamed: 1
588  2021-01-13 00:00:00       0.84
639  2021-01-13 00:00:00       0.87
                SBES1K23 Unnamed: 4
683  2021-01-13 00:00:00       0.47
2020-01-13 00:00:00
                SBES1H23 Unnamed: 1
892  2020-01-13 00:00:00       0.24
945  2020-01-13 00:00:00       0.01
                SBES1K23 Unnamed: 4
988  2020-01-13 00:00:00          0
2023-01-14 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-01-14 00:00:00
                SBES1H23 Unnamed: 1
281  2022-01-14 00:00:00       0.72
334  2022-01-14 00:00:00       0.23
                SBES1K23 Unnamed: 4
377  2022-01-14 00:00:00       0.17
2021-01-14 00:00:00
                SBES1H23 Unnamed: 1
587  2021-01-14 00:00:00       0.96
638  2021-01-14 00:00:00       0.98
                SBES1K23 Unnamed: 4
682  2021-01-14 00:00:00       0.68
2020-01-14 00:00:00
                SBES1H23 Unnamed: 1
891  2020-01-14 00:00:00       0.26
944  2020-01-14 00:00:00       0.02
                SBES1K23 Unnamed: 4
987  2020-01-14 00:00:00       0.01
2023-01-15 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-01-15 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-01-15 00:00:00
                SBES1H23 Unnamed: 1
586  2021-01-15 00:00:00       0.83
637  2021-01-15 00:00:00       0.88
                SBES1K23 Unnamed: 4
681  2021-01-15 00:00:00       0.59
2020-01-15 00:00:00
                SBES1H23 Unnamed: 1
890  2020-01-15 00:00:00       0.32
943  2020-01-15 00:00:00       0.04
                SBES1K23 Unnamed: 4
986  2020-01-15 00:00:00       0.04
2023-01-16 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-01-16 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-01-16 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-01-16 00:00:00
                SBES1H23 Unnamed: 1
889  2020-01-16 00:00:00       0.29
942  2020-01-16 00:00:00       0.04
                SBES1K23 Unnamed: 4
985  2020-01-16 00:00:00       0.04
2023-01-17 00:00:00
               SBES1H23 Unnamed: 1
30  2023-01-17 00:00:00       1.37
               SBES1K23 Unnamed: 4
72  2023-01-17 00:00:00       0.75
2022-01-17 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-01-17 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-01-17 00:00:00
                SBES1H23 Unnamed: 1
888  2020-01-17 00:00:00        0.3
941  2020-01-17 00:00:00       0.05
                SBES1K23 Unnamed: 4
984  2020-01-17 00:00:00       0.05
2023-01-18 00:00:00
               SBES1H23 Unnamed: 1
29  2023-01-18 00:00:00       1.28
               SBES1K23 Unnamed: 4
71  2023-01-18 00:00:00       0.67
2022-01-18 00:00:00
                SBES1H23 Unnamed: 1
280  2022-01-18 00:00:00       0.78
333  2022-01-18 00:00:00       0.25
                SBES1K23 Unnamed: 4
376  2022-01-18 00:00:00       0.23
2021-01-18 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-01-18 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-01-19 00:00:00
               SBES1H23 Unnamed: 1
28  2023-01-19 00:00:00       1.27
               SBES1K23 Unnamed: 4
70  2023-01-19 00:00:00       0.65
2022-01-19 00:00:00
                SBES1H23 Unnamed: 1
279  2022-01-19 00:00:00       0.82
332  2022-01-19 00:00:00       0.29
                SBES1K23 Unnamed: 4
375  2022-01-19 00:00:00       0.27
2021-01-19 00:00:00
                SBES1H23 Unnamed: 1
585  2021-01-19 00:00:00       0.82
636  2021-01-19 00:00:00       0.86
                SBES1K23 Unnamed: 4
680  2021-01-19 00:00:00       0.58
2020-01-19 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-01-20 00:00:00
               SBES1H23 Unnamed: 1
27  2023-01-20 00:00:00       1.31
               SBES1K23 Unnamed: 4
69  2023-01-20 00:00:00       0.64
2022-01-20 00:00:00
                SBES1H23 Unnamed: 1
278  2022-01-20 00:00:00       0.81
331  2022-01-20 00:00:00       0.26
                SBES1K23 Unnamed: 4
374  2022-01-20 00:00:00       0.25
2021-01-20 00:00:00
                SBES1H23 Unnamed: 1
584  2021-01-20 00:00:00       0.85
635  2021-01-20 00:00:00       0.85
                SBES1K23 Unnamed: 4
679  2021-01-20 00:00:00       0.59
2020-01-20 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-01-21 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-01-21 00:00:00
                SBES1H23 Unnamed: 1
277  2022-01-21 00:00:00       0.82
330  2022-01-21 00:00:00        0.3
                SBES1K23 Unnamed: 4
373  2022-01-21 00:00:00       0.23
2021-01-21 00:00:00
                SBES1H23 Unnamed: 1
583  2021-01-21 00:00:00       0.85
634  2021-01-21 00:00:00       0.76
                SBES1K23 Unnamed: 4
678  2021-01-21 00:00:00       0.52
2020-01-21 00:00:00
                SBES1H23 Unnamed: 1
887  2020-01-21 00:00:00       0.32
940  2020-01-21 00:00:00       0.06
                SBES1K23 Unnamed: 4
983  2020-01-21 00:00:00       0.07
2023-01-22 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-01-22 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-01-22 00:00:00
                SBES1H23 Unnamed: 1
582  2021-01-22 00:00:00       0.84
633  2021-01-22 00:00:00       0.77
                SBES1K23 Unnamed: 4
677  2021-01-22 00:00:00       0.46
2020-01-22 00:00:00
                SBES1H23 Unnamed: 1
886  2020-01-22 00:00:00       0.33
939  2020-01-22 00:00:00       0.09
                SBES1K23 Unnamed: 4
982  2020-01-22 00:00:00        0.1
2023-01-23 00:00:00
               SBES1H23 Unnamed: 1
26  2023-01-23 00:00:00       1.26
               SBES1K23 Unnamed: 4
68  2023-01-23 00:00:00       0.64
2022-01-23 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-01-23 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-01-23 00:00:00
                SBES1H23 Unnamed: 1
885  2020-01-23 00:00:00       0.29
938  2020-01-23 00:00:00        0.1
                SBES1K23 Unnamed: 4
981  2020-01-23 00:00:00       0.08
2023-01-24 00:00:00
               SBES1H23 Unnamed: 1
25  2023-01-24 00:00:00       1.25
               SBES1K23 Unnamed: 4
67  2023-01-24 00:00:00       0.64
2022-01-24 00:00:00
                SBES1H23 Unnamed: 1
276  2022-01-24 00:00:00       0.84
329  2022-01-24 00:00:00       0.34
                SBES1K23 Unnamed: 4
372  2022-01-24 00:00:00       0.23
2021-01-24 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-01-24 00:00:00
                SBES1H23 Unnamed: 1
884  2020-01-24 00:00:00       0.28
937  2020-01-24 00:00:00       0.07
                SBES1K23 Unnamed: 4
980  2020-01-24 00:00:00       0.07
2023-01-25 00:00:00
               SBES1H23 Unnamed: 1
24  2023-01-25 00:00:00       1.27
               SBES1K23 Unnamed: 4
66  2023-01-25 00:00:00       0.66
2022-01-25 00:00:00
                SBES1H23 Unnamed: 1
275  2022-01-25 00:00:00       0.83
328  2022-01-25 00:00:00       0.37
                SBES1K23 Unnamed: 4
371  2022-01-25 00:00:00       0.19
2021-01-25 00:00:00
                SBES1H23 Unnamed: 1
581  2021-01-25 00:00:00       0.82
632  2021-01-25 00:00:00       0.72
                SBES1K23 Unnamed: 4
676  2021-01-25 00:00:00       0.42
2020-01-25 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-01-26 00:00:00
               SBES1H23 Unnamed: 1
23  2023-01-26 00:00:00       1.39
               SBES1K23 Unnamed: 4
65  2023-01-26 00:00:00       0.82
2022-01-26 00:00:00
                SBES1H23 Unnamed: 1
274  2022-01-26 00:00:00        0.8
327  2022-01-26 00:00:00       0.31
                SBES1K23 Unnamed: 4
370  2022-01-26 00:00:00       0.15
2021-01-26 00:00:00
                SBES1H23 Unnamed: 1
580  2021-01-26 00:00:00        0.8
631  2021-01-26 00:00:00       0.71
                SBES1K23 Unnamed: 4
675  2021-01-26 00:00:00       0.44
2020-01-26 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-01-27 00:00:00
               SBES1H23 Unnamed: 1
22  2023-01-27 00:00:00       1.36
               SBES1K23 Unnamed: 4
64  2023-01-27 00:00:00       0.85
2022-01-27 00:00:00
                SBES1H23 Unnamed: 1
273  2022-01-27 00:00:00       0.81
326  2022-01-27 00:00:00       0.33
                SBES1K23 Unnamed: 4
369  2022-01-27 00:00:00       0.14
2021-01-27 00:00:00
                SBES1H23 Unnamed: 1
579  2021-01-27 00:00:00       0.82
630  2021-01-27 00:00:00       0.72
                SBES1K23 Unnamed: 4
674  2021-01-27 00:00:00       0.46
2020-01-27 00:00:00
                SBES1H23 Unnamed: 1
883  2020-01-27 00:00:00       0.28
936  2020-01-27 00:00:00       0.08
                SBES1K23 Unnamed: 4
979  2020-01-27 00:00:00       0.01
2023-01-28 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-01-28 00:00:00
                SBES1H23 Unnamed: 1
272  2022-01-28 00:00:00        0.7
325  2022-01-28 00:00:00       0.33
                SBES1K23 Unnamed: 4
368  2022-01-28 00:00:00       0.11
2021-01-28 00:00:00
                SBES1H23 Unnamed: 1
578  2021-01-28 00:00:00       0.82
629  2021-01-28 00:00:00       0.65
                SBES1K23 Unnamed: 4
673  2021-01-28 00:00:00       0.43
2020-01-28 00:00:00
                SBES1H23 Unnamed: 1
882  2020-01-28 00:00:00        0.3
935  2020-01-28 00:00:00       0.13
                SBES1K23 Unnamed: 4
978  2020-01-28 00:00:00       0.04
2023-01-29 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-01-29 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-01-29 00:00:00
                SBES1H23 Unnamed: 1
577  2021-01-29 00:00:00       0.85
628  2021-01-29 00:00:00       0.76
                SBES1K23 Unnamed: 4
672  2021-01-29 00:00:00       0.47
2020-01-29 00:00:00
                SBES1H23 Unnamed: 1
881  2020-01-29 00:00:00       0.28
934  2020-01-29 00:00:00       0.17
                SBES1K23 Unnamed: 4
977  2020-01-29 00:00:00       0.09
2023-01-30 00:00:00
               SBES1H23 Unnamed: 1
21  2023-01-30 00:00:00       1.31
               SBES1K23 Unnamed: 4

[{'month_day': '01-02', 'cena_flaja_srednia': 0.2},
 {'month_day': '01-03', 'cena_flaja_srednia': 0.48},
 {'month_day': '01-04', 'cena_flaja_srednia': 0.45999999999999996},
 {'month_day': '01-05', 'cena_flaja_srednia': 0.4466666666666666},
 {'month_day': '01-06', 'cena_flaja_srednia': 0.36},
 {'month_day': '01-07', 'cena_flaja_srednia': 0.37333333333333335},
 {'month_day': '01-08', 'cena_flaja_srednia': 0.275},
 {'month_day': '01-09', 'cena_flaja_srednia': 0.37000000000000005},
 {'month_day': '01-10', 'cena_flaja_srednia': 0.46666666666666673},
 {'month_day': '01-11', 'cena_flaja_srednia': 0.48000000000000004},
 {'month_day': '01-12', 'cena_flaja_srednia': 0.5},
 {'month_day': '01-13', 'cena_flaja_srednia': 0.43250000000000005},
 {'month_day': '01-14', 'cena_flaja_srednia': 0.35999999999999993},
 {'month_day': '01-15', 'cena_flaja_srednia': 0.26},
 {'month_day': '01-16', 'cena_flaja_srednia': 0.24999999999999997},
 {'month_day': '01-17', 'cena_flaja_srednia': 0.43500000000000005},
 {'month_day': '01-18', 'cena_flaja_srednia': 0.5800000000000001},
 {'month_day': '01-19', 'cena_flaja_srednia': 0.47},
 {'month_day': '01-20', 'cena_flaja_srednia': 0.49666666666666665},
 {'month_day': '01-21', 'cena_flaja_srednia': 0.38999999999999996},
 {'month_day': '01-22', 'cena_flaja_srednia': 0.305},
 {'month_day': '01-23', 'cena_flaja_srednia': 0.415},
 {'month_day': '01-24', 'cena_flaja_srednia': 0.4766666666666666},
 {'month_day': '01-25', 'cena_flaja_srednia': 0.5499999999999999},
 {'month_day': '01-26', 'cena_flaja_srednia': 0.5266666666666667},
 {'month_day': '01-27', 'cena_flaja_srednia': 0.4525},
 {'month_day': '01-28', 'cena_flaja_srednia': 0.41333333333333333},
 {'month_day': '01-29', 'cena_flaja_srednia': 0.28500000000000003},
 {'month_day': '01-30', 'cena_flaja_srednia': 0.3350000000000001},
 {'month_day': '01-31', 'cena_flaja_srednia': 0.3766666666666667}]

In [36]:
srednie_ceny_rok = []
for month_i in range(1,13):
  month = f"{month_i:02d}"
  cena_flaja_miesiac = oblicz_ceny_flaja_dla_miesiaca(month, df1, df2, "SBES1H23" , "SBES1K23" , "Unnamed: 1", "Unnamed: 4" )
  srednie_ceny_rok += cena_flaja_miesiac

Strumieniowane dane wyjściowe obcięte do 5000 ostatnich wierszy.
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-06 00:00:00
                SBES1H23 Unnamed: 1
184  2022-06-06 00:00:00       0.63
                SBES1K23 Unnamed: 4
226  2022-06-06 00:00:00       0.35
2021-06-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-06-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-06-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-07 00:00:00
                SBES1H23 Unnamed: 1
183  2022-06-07 00:00:00       0.58
                SBES1K23 Unnamed: 4
225  2022-06-07 00:00:00       0.31
2021-06-07 00:00:00
                SBES1H23 Unnamed: 1
489  2021-06-07 00:00:00       0.89
                SBES1K23 Unnamed: 4
532  2021-06-07 00:00:00       0.68
2020-06-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-06-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-08 00:00:00
                SBES1H23 Unnamed: 1
182  2022-06-08 00:00:00       0.59
                SBES1K23 Unnamed: 4
224  2022-06-08 00:00:00        0.3
2021-06-08 00:00:00
                SBES1H23 Unnamed: 1
488  2021-06-08 00:00:00        0.9
                SBES1K23 Unnamed: 4
531  2021-06-08 00:00:00       0.69
2020-06-08 00:00:00
                SBES1H23 Unnamed: 1
791  2020-06-08 00:00:00       0.16
                SBES1K23 Unnamed: 4
835  2020-06-08 00:00:00       0.13
2023-06-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-09 00:00:00
                SBES1H23 Unnamed: 1
181  2022-06-09 00:00:00       0.64
                SBES1K23 Unnamed: 4
223  2022-06-09 00:00:00       0.34
2021-06-09 00:00:00
                SBES1H23 Unnamed: 1
487  2021-06-09 00:00:00        0.9
                SBES1K23 Unnamed: 4
530  2021-06-09 00:00:00       0.71
2020-06-09 00:00:00
                SBES1H23 Unnamed: 1
790  2020-06-09 00:00:00       0.21
                SBES1K23 Unnamed: 4
834  2020-06-09 00:00:00       0.15
2023-06-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-10 00:00:00
                SBES1H23 Unnamed: 1
180  2022-06-10 00:00:00       0.59
                SBES1K23 Unnamed: 4
222  2022-06-10 00:00:00       0.29
2021-06-10 00:00:00
                SBES1H23 Unnamed: 1
486  2021-06-10 00:00:00       0.89
                SBES1K23 Unnamed: 4
529  2021-06-10 00:00:00       0.64
2020-06-10 00:00:00
                SBES1H23 Unnamed: 1
789  2020-06-10 00:00:00        0.3
                SBES1K23 Unnamed: 4
833  2020-06-10 00:00:00       0.22
2023-06-11 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-11 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-06-11 00:00:00
                SBES1H23 Unnamed: 1
485  2021-06-11 00:00:00       0.85
                SBES1K23 Unnamed: 4
528  2021-06-11 00:00:00       0.63
2020-06-11 00:00:00
                SBES1H23 Unnamed: 1
788  2020-06-11 00:00:00       0.19
                SBES1K23 Unnamed: 4
832  2020-06-11 00:00:00       0.16
2023-06-12 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-12 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-06-12 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-06-12 00:00:00
                SBES1H23 Unnamed: 1
787  2020-06-12 00:00:00        0.2
                SBES1K23 Unnamed: 4
831  2020-06-12 00:00:00       0.18
2023-06-13 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-13 00:00:00
                SBES1H23 Unnamed: 1
179  2022-06-13 00:00:00       0.55
                SBES1K23 Unnamed: 4
221  2022-06-13 00:00:00       0.28
2021-06-13 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-06-13 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-06-14 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-14 00:00:00
                SBES1H23 Unnamed: 1
178  2022-06-14 00:00:00       0.58
                SBES1K23 Unnamed: 4
220  2022-06-14 00:00:00       0.29
2021-06-14 00:00:00
                SBES1H23 Unnamed: 1
484  2021-06-14 00:00:00       0.85
                SBES1K23 Unnamed: 4
527  2021-06-14 00:00:00       0.58
2020-06-14 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-06-15 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-15 00:00:00
                SBES1H23 Unnamed: 1
177  2022-06-15 00:00:00       0.53
                SBES1K23 Unnamed: 4
219  2022-06-15 00:00:00       0.24
2021-06-15 00:00:00
                SBES1H23 Unnamed: 1
483  2021-06-15 00:00:00       0.85
                SBES1K23 Unnamed: 4
526  2021-06-15 00:00:00       0.59
2020-06-15 00:00:00
                SBES1H23 Unnamed: 1
786  2020-06-15 00:00:00       0.27
                SBES1K23 Unnamed: 4
830  2020-06-15 00:00:00       0.25
2023-06-16 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-16 00:00:00
                SBES1H23 Unnamed: 1
176  2022-06-16 00:00:00       0.55
                SBES1K23 Unnamed: 4
218  2022-06-16 00:00:00       0.27
2021-06-16 00:00:00
                SBES1H23 Unnamed: 1
482  2021-06-16 00:00:00       0.81
                SBES1K23 Unnamed: 4
525  2021-06-16 00:00:00       0.57
2020-06-16 00:00:00
                SBES1H23 Unnamed: 1
785  2020-06-16 00:00:00       0.33
                SBES1K23 Unnamed: 4
829  2020-06-16 00:00:00       0.31
2023-06-17 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-17 00:00:00
                SBES1H23 Unnamed: 1
175  2022-06-17 00:00:00       0.57
                SBES1K23 Unnamed: 4
217  2022-06-17 00:00:00       0.26
2021-06-17 00:00:00
                SBES1H23 Unnamed: 1
481  2021-06-17 00:00:00       0.79
                SBES1K23 Unnamed: 4
524  2021-06-17 00:00:00       0.52
2020-06-17 00:00:00
                SBES1H23 Unnamed: 1
784  2020-06-17 00:00:00       0.32
                SBES1K23 Unnamed: 4
828  2020-06-17 00:00:00       0.32
2023-06-18 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-18 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-06-18 00:00:00
                SBES1H23 Unnamed: 1
480  2021-06-18 00:00:00       0.77
                SBES1K23 Unnamed: 4
523  2021-06-18 00:00:00       0.51
2020-06-18 00:00:00
                SBES1H23 Unnamed: 1
783  2020-06-18 00:00:00       0.32
                SBES1K23 Unnamed: 4
827  2020-06-18 00:00:00        0.3
2023-06-19 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-19 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-06-19 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-06-19 00:00:00
                SBES1H23 Unnamed: 1
782  2020-06-19 00:00:00       0.35
                SBES1K23 Unnamed: 4
826  2020-06-19 00:00:00        0.3
2023-06-20 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-20 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-06-20 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-06-20 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-06-21 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-21 00:00:00
                SBES1H23 Unnamed: 1
174  2022-06-21 00:00:00       0.59
                SBES1K23 Unnamed: 4
216  2022-06-21 00:00:00       0.27
2021-06-21 00:00:00
                SBES1H23 Unnamed: 1
479  2021-06-21 00:00:00       0.84
                SBES1K23 Unnamed: 4
522  2021-06-21 00:00:00       0.56
2020-06-21 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-06-22 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-22 00:00:00
                SBES1H23 Unnamed: 1
173  2022-06-22 00:00:00       0.54
                SBES1K23 Unnamed: 4
215  2022-06-22 00:00:00       0.23
2021-06-22 00:00:00
                SBES1H23 Unnamed: 1
478  2021-06-22 00:00:00       0.81
                SBES1K23 Unnamed: 4
521  2021-06-22 00:00:00       0.52
2020-06-22 00:00:00
                SBES1H23 Unnamed: 1
781  2020-06-22 00:00:00       0.26
                SBES1K23 Unnamed: 4
825  2020-06-22 00:00:00       0.24
2023-06-23 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-23 00:00:00
                SBES1H23 Unnamed: 1
172  2022-06-23 00:00:00       0.54
                SBES1K23 Unnamed: 4
214  2022-06-23 00:00:00       0.23
2021-06-23 00:00:00
                SBES1H23 Unnamed: 1
477  2021-06-23 00:00:00       0.82
                SBES1K23 Unnamed: 4
520  2021-06-23 00:00:00       0.55
2020-06-23 00:00:00
                SBES1H23 Unnamed: 1
780  2020-06-23 00:00:00       0.24
                SBES1K23 Unnamed: 4
824  2020-06-23 00:00:00        0.2
2023-06-24 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-24 00:00:00
                SBES1H23 Unnamed: 1
171  2022-06-24 00:00:00       0.55
                SBES1K23 Unnamed: 4
213  2022-06-24 00:00:00       0.26
2021-06-24 00:00:00
                SBES1H23 Unnamed: 1
476  2021-06-24 00:00:00       0.85
                SBES1K23 Unnamed: 4
519  2021-06-24 00:00:00       0.61
2020-06-24 00:00:00
                SBES1H23 Unnamed: 1
779  2020-06-24 00:00:00       0.25
                SBES1K23 Unnamed: 4
823  2020-06-24 00:00:00       0.22
2023-06-25 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-25 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-06-25 00:00:00
                SBES1H23 Unnamed: 1
475  2021-06-25 00:00:00       0.83
                SBES1K23 Unnamed: 4
518  2021-06-25 00:00:00       0.62
2020-06-25 00:00:00
                SBES1H23 Unnamed: 1
778  2020-06-25 00:00:00       0.24
                SBES1K23 Unnamed: 4
822  2020-06-25 00:00:00       0.23
2023-06-26 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-26 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-06-26 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-06-26 00:00:00
                SBES1H23 Unnamed: 1
777  2020-06-26 00:00:00       0.23
                SBES1K23 Unnamed: 4
821  2020-06-26 00:00:00       0.21
2023-06-27 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-27 00:00:00
                SBES1H23 Unnamed: 1
170  2022-06-27 00:00:00       0.54
                SBES1K23 Unnamed: 4
212  2022-06-27 00:00:00       0.23
2021-06-27 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-06-27 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-06-28 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-28 00:00:00
                SBES1H23 Unnamed: 1
169  2022-06-28 00:00:00       0.61
                SBES1K23 Unnamed: 4
211  2022-06-28 00:00:00       0.29
2021-06-28 00:00:00
                SBES1H23 Unnamed: 1
474  2021-06-28 00:00:00       0.85
                SBES1K23 Unnamed: 4
517  2021-06-28 00:00:00       0.68
2020-06-28 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-06-29 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-29 00:00:00
                SBES1H23 Unnamed: 1
168  2022-06-29 00:00:00        0.6
                SBES1K23 Unnamed: 4
210  2022-06-29 00:00:00       0.31
2021-06-29 00:00:00
                SBES1H23 Unnamed: 1
473  2021-06-29 00:00:00       0.81
                SBES1K23 Unnamed: 4
516  2021-06-29 00:00:00       0.68
2020-06-29 00:00:00
                SBES1H23 Unnamed: 1
776  2020-06-29 00:00:00       0.24
                SBES1K23 Unnamed: 4
820  2020-06-29 00:00:00       0.24
2023-06-30 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-06-30 00:00:00
                SBES1H23 Unnamed: 1
167  2022-06-30 00:00:00       0.54
                SBES1K23 Unnamed: 4
209  2022-06-30 00:00:00       0.25
2021-06-30 00:00:00
                SBES1H23 Unnamed: 1
472  2021-06-30 00:00:00       0.87
                SBES1K23 Unnamed: 4
515  2021-06-30 00:00:00       0.73
2020-06-30 00:00:00
                SBES1H23 Unnamed: 1
775  2020-06-30 00:00:00       0.28
                SBES1K23 Unnamed: 4
819  2020-06-30 00:00:00       0.26
(5, 31)
2023-07-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-07-01 00:00:00
                SBES1H23 Unnamed: 1
166  2022-07-01 00:00:00       0.52
                SBES1K23 Unnamed: 4
208  2022-07-01 00:00:00       0.26
2021-07-01 00:00:00
                SBES1H23 Unnamed: 1
471  2021-07-01 00:00:00        0.9
                SBES1K23 Unnamed: 4
514  2021-07-01 00:00:00       0.74
2020-07-01 00:00:00
                SBES1H23 Unnamed: 1
774  2020-07-01 00:00:00       0.27
                SBES1K23 Unnamed: 4
818  2020-07-01 00:00:00       0.26
2023-07-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-07-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-07-02 00:00:00
                SBES1H23 Unnamed: 1
470  2021-07-02 00:00:00       0.88
                SBES1K23 Unnamed: 4
513  2021-07-02 00:00:00       0.76
2020-07-02 00:00:00
                SBES1H23 Unnamed: 1
773  2020-07-02 00:00:00       0.34
                SBES1K23 Unnamed: 4
817  2020-07-02 00:00:00        0.3
2023-07-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-07-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-07-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-07-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-07-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-07-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-07-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-07-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-07-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-07-05 00:00:00
                SBES1H23 Unnamed: 1
165  2022-07-05 00:00:00       0.55
                SBES1K23 Unnamed: 4
207  2022-07-05 00:00:00       0.26
2021-07-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-07-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-07-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-07-06 00:00:00
                SBES1H23 Unnamed: 1
164  2022-07-06 00:00:00        0.6
                SBES1K23 Unnamed: 4
206  2022-07-06 00:00:00        0.3
2021-07-06 00:00:00
                SBES1H23 Unnamed: 1
469  2021-07-06 00:00:00       0.84
                SBES1K23 Unnamed: 4
512  2021-07-06 00:00:00       0.73
2020-07-06 00:00:00
                SBES1H23 Unnamed: 1
772  2020-07-06 00:00:00        0.3
                SBES1K23 Unnamed: 4
816  2020-07-06 00:00:00       0.26
2023-07-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-07-07 00:00:00
                SBES1H23 Unnamed: 1
163  2022-07-07 00:00:00       0.65
                SBES1K23 Unnamed: 4
205  2022-07-07 00:00:00       0.33
2021-07-07 00:00:00
                SBES1H23 Unnamed: 1
468  2021-07-07 00:00:00       0.84
                SBES1K23 Unnamed: 4
511  2021-07-07 00:00:00       0.75
2020-07-07 00:00:00
                SBES1H23 Unnamed: 1
771  2020-07-07 00:00:00       0.34
                SBES1K23 Unnamed: 4
815  2020-07-07 00:00:00        0.3
2023-07-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-07-08 00:00:00
                SBES1H23 Unnamed: 1
162  2022-07-08 00:00:00       0.75
                SBES1K23 Unnamed: 4
204  2022-07-08 00:00:00       0.42
2021-07-08 00:00:00
                SBES1H23 Unnamed: 1
467  2021-07-08 00:00:00       0.81
                SBES1K23 Unnamed: 4
510  2021-07-08 00:00:00       0.67
2020-07-08 00:00:00
                SBES1H23 Unnamed: 1
770  2020-07-08 00:00:00       0.33
                SBES1K23 Unnamed: 4
814  2020-07-08 00:00:00        0.3
2023-07-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-07-09 00:00:00

In [37]:
df_rok = pd.DataFrame(srednie_ceny_rok)

In [38]:
df_rok

    month_day  cena_flaja_srednia
0       01-02            0.200000
1       01-03            0.480000
2       01-04            0.460000
3       01-05            0.446667
4       01-06            0.360000
..        ...                 ...
351     12-27            0.585000
352     12-28            0.433333
353     12-29            0.446667
354     12-30            0.410000
355     12-31            0.320000

[356 rows x 2 columns]