<a href="https://colab.research.google.com/github/tomektom10/dataScienceBootCamp/blob/main/PROJEKT_CUKIER_NAJNOWSZE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
df = pd.read_excel("Cukry_wszystkie_plus24.xlsx")
df
df.columns
import numpy as np

In [18]:
df1 = df[["SBES1H24", "Unnamed: 1"]].iloc[1:]
df1

                 SBES1H24 Unnamed: 1
1     2023-11-20 00:00:00       1.32
2     2023-11-17 00:00:00       1.31
3     2023-11-16 00:00:00       1.33
4     2023-11-15 00:00:00       1.35
5     2023-11-14 00:00:00       1.38
...                   ...        ...
3338  2012-12-26 00:00:00        0.1
3339  2012-12-24 00:00:00       0.12
3340  2012-12-21 00:00:00        0.1
3341  2012-12-20 00:00:00       0.11
3342  2012-12-19 00:00:00       0.11

[3342 rows x 2 columns]

In [19]:
df2 = df[["SBES1K24", "Unnamed: 4"]].iloc[1:]
df2
import datetime

In [53]:
day_month = "10-13"
wynik_dict = {"Date":[], "cena_flaja1":[] }
for year in [2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012]:
  specyfic_date = str(year) + "-" + day_month
  specyfic_date = datetime.datetime.strptime(specyfic_date, '%Y-%m-%d')
  print(specyfic_date)
  df_row1 = df1[df1["SBES1H24"] == specyfic_date]
  print(df_row1)

  df_row2 = df2[df2["SBES1K24"] == specyfic_date]
  print(df_row2)
  cena_flaja = []
  if len(df_row1) > 0 and len(df_row2) >0:

    value = df_row1['Unnamed: 1'].values[0]
    cena_flaja = value - df_row2["Unnamed: 4"].values[0]


    wynik_dict["Date"].append(specyfic_date)
    wynik_dict["cena_flaja1"].append(cena_flaja)


df_wynik = pd.DataFrame(wynik_dict)

2023-10-13 00:00:00
               SBES1H24 Unnamed: 1
27  2023-10-13 00:00:00        1.3
               SBES1K24 Unnamed: 4
27  2023-10-13 00:00:00       1.03
2022-10-13 00:00:00
                SBES1H24 Unnamed: 1
278  2022-10-13 00:00:00       0.63
399  2022-10-13 00:00:00       0.94
                SBES1K24 Unnamed: 4
278  2022-10-13 00:00:00       0.45
441  2022-10-13 00:00:00       0.57
2021-10-13 00:00:00
                SBES1H24 Unnamed: 1
704  2021-10-13 00:00:00       0.42
                SBES1K24 Unnamed: 4
747  2021-10-13 00:00:00       0.44
2020-10-13 00:00:00
                 SBES1H24 Unnamed: 1
1007  2020-10-13 00:00:00       0.45
                 SBES1K24 Unnamed: 4
1051  2020-10-13 00:00:00       0.38
2019-10-13 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2018-10-13 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-10-13 00:00:00
                 SBES1H24 Unnamed: 1
1919  2017-10-13 00:00:00      -0.09
                 SBES1K24 Unnamed: 4
1961  2017-10-13 00:00:00      -0.16
2016-10-13 00:00:00
                 SBES1H24 Unnamed: 1
2224  2016-10-13 00:00:00       0.66
                 SBES1K24 Unnamed: 4
2266  2016-10-13 00:00:00       0.63
2015-10-13 00:00:00
                 SBES1H24 Unnamed: 1
2529  2015-10-13 00:00:00       0.18
                 SBES1K24 Unnamed: 4
2572  2015-10-13 00:00:00       0.15
2014-10-13 00:00:00
                 SBES1H24 Unnamed: 1
2833  2014-10-13 00:00:00      -0.28
                 SBES1K24 Unnamed: 4
2876  2014-10-13 00:00:00       -0.3
2013-10-13 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2012-10-13 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []

In [21]:
df_wynik

        Date  cena_flaja1
0 2023-10-16         0.26
1 2020-10-16         0.10
2 2019-10-16         0.03
3 2018-10-16        -0.07
4 2017-10-16         0.04
5 2015-10-16         0.02
6 2014-10-16         0.02
7 2013-10-16        -0.01

In [23]:
def oblicz_ceny_flaja(df1, df2, kod1, kod2, cena1, cena2, day_month):

  wynik_dict = {"Date":[], "cena_flaja1":[] }
  for year in [2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012]:
    specyfic_date = str(year) + "-" + day_month
    specyfic_date = datetime.datetime.strptime(specyfic_date, '%Y-%m-%d')
    print(specyfic_date)
    df_row1 = df1[df1[kod1] == specyfic_date]
    print(df_row1)

    df_row2 = df2[df2[kod2] == specyfic_date]
    print(df_row2)
    cena_flaja = []
    if len(df_row1) > 0 and len(df_row2) >0:

      value = df_row1[cena1].values[0]
      cena_flaja = value - df_row2[cena2].values[0]


      wynik_dict["Date"].append(specyfic_date)
      wynik_dict["cena_flaja1"].append(cena_flaja)


      df_wynik = pd.DataFrame(wynik_dict)
  return df_wynik

In [24]:
oblicz_ceny_flaja(df1, df2, "SBES1H24" , "SBES1K24" , "Unnamed: 1", "Unnamed: 4", "10-16" )

2023-10-16 00:00:00
               SBES1H24 Unnamed: 1
26  2023-10-16 00:00:00       1.27
               SBES1K24 Unnamed: 4
26  2023-10-16 00:00:00       1.01
2022-10-16 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-10-16 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2020-10-16 00:00:00
                 SBES1H24 Unnamed: 1
1004  2020-10-16 00:00:00       0.63
                 SBES1K24 Unnamed: 4
1048  2020-10-16 00:00:00       0.53
2019-10-16 00:00:00
                 SBES1H24 Unnamed: 1
1310  2019-10-16 00:00:00       -0.1
                 SBES1K24 Unnamed: 4
1353  2019-10-16 00:00:00      -0.13
2018-10-16 00:00:00
                 SBES1H24 Unnamed: 1
1614  2018-10-16 00:00:00      -0.14
                 SBES1K24 Unnamed: 4
1656  2018-10-16 00:00:00      -0.07
2017-10-16 00:00:00
                 SBES1H24 Unnamed: 1
1918  2017-10-16 00:00:00      -0.11
                 SBES1K24 Unnamed: 4
1960  2017-10-16 00:00:00      -0.15
2016-10-16 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-10-16 00:00:00
                 SBES1H24 Unnamed: 1
2526  2015-10-16 00:00:00       0.22
                 SBES1K24 Unnamed: 4
2569  2015-10-16 00:00:00        0.2
2014-10-16 00:00:00
                 SBES1H24 Unnamed: 1
2830  2014-10-16 00:00:00      -0.24
                 SBES1K24 Unnamed: 4
2873  2014-10-16 00:00:00      -0.26
2013-10-16 00:00:00
                 SBES1H24 Unnamed: 1
3135  2013-10-16 00:00:00       0.14
                 SBES1K24 Unnamed: 4
3177  2013-10-16 00:00:00       0.15
2012-10-16 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []

        Date  cena_flaja1
0 2023-10-16         0.26
1 2020-10-16         0.10
2 2019-10-16         0.03
3 2018-10-16        -0.07
4 2017-10-16         0.04
5 2015-10-16         0.02
6 2014-10-16         0.02
7 2013-10-16        -0.01

In [25]:
import calendar
month = "02"

In [28]:
def create_days_for_month(month, year = 2023):
  numdays = calendar.monthrange(year, int(month))[-1]
  print(calendar.monthrange(year, int(month)))
  days_list = [f'{month}-{day:02d}' for day in range(1, numdays + 1)]
  return days_list

In [29]:
create_days_for_month("9")

(4, 30)

['9-01',
 '9-02',
 '9-03',
 '9-04',
 '9-05',
 '9-06',
 '9-07',
 '9-08',
 '9-09',
 '9-10',
 '9-11',
 '9-12',
 '9-13',
 '9-14',
 '9-15',
 '9-16',
 '9-17',
 '9-18',
 '9-19',
 '9-20',
 '9-21',
 '9-22',
 '9-23',
 '9-24',
 '9-25',
 '9-26',
 '9-27',
 '9-28',
 '9-29',
 '9-30']

In [30]:
days_list = create_days_for_month("9")

(4, 30)

In [31]:
srednia_df = []
for month_day in days_list:
 df= oblicz_ceny_flaja(df1, df2, "SBES1H24" , "SBES1K24" , "Unnamed: 1", "Unnamed: 4", month_day )
 srednia_df.append({"month_day": month_day, "cena_flaja_srednia": df["cena_flaja1"].mean()})

2023-09-01 00:00:00
               SBES1H24 Unnamed: 1
56  2023-09-01 00:00:00        1.5
               SBES1K24 Unnamed: 4
56  2023-09-01 00:00:00       1.26
2022-09-01 00:00:00
                SBES1H24 Unnamed: 1
428  2022-09-01 00:00:00       0.59
                SBES1K24 Unnamed: 4
470  2022-09-01 00:00:00       0.27
2021-09-01 00:00:00
                SBES1H24 Unnamed: 1
733  2021-09-01 00:00:00       0.68
                SBES1K24 Unnamed: 4
776  2021-09-01 00:00:00        0.8
2020-09-01 00:00:00
                 SBES1H24 Unnamed: 1
1036  2020-09-01 00:00:00       0.21
                 SBES1K24 Unnamed: 4
1080  2020-09-01 00:00:00       0.28
2019-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2018-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-01 00:00:00
                 SBES1H24 Unnamed: 1
1948  2017-09-01 00:00:00      -0.24
                 SBES1K24 Unnamed: 4
1990  2017-09-01 00:00:00      -0.25
2016-09-01 00:00:00
                 SBES1H24 Unnamed: 1
2253  2016-09-01 00:00:00       0.47
                 SBES1K24 Unnamed: 4
2295  2016-09-01 00:00:00       0.51
2015-09-01 00:00:00
                 SBES1H24 Unnamed: 1
2558  2015-09-01 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
2601  2015-09-01 00:00:00          0
2014-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2013-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2012-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-02 00:00:00
                SBES1H24 Unnamed: 1
427  2022-09-02 00:00:00       0.53
                SBES1K24 Unnamed: 4
469  2022-09-02 00:00:00       0.21
2021-09-02 00:00:00
                SBES1H24 Unnamed: 1
732  2021-09-02 00:00:00       0.66
                SBES1K24 Unnamed: 4
775  2021-09-02 00:00:00       0.74
2020-09-02 00:00:00
                 SBES1H24 Unnamed: 1
1035  2020-09-02 00:00:00       0.11
                 SBES1K24 Unnamed: 4
1079  2020-09-02 00:00:00       0.18
2019-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2018-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-02 00:00:00
                 SBES1H24 Unnamed: 1
2252  2016-09-02 00:00:00       0.56
                 SBES1K24 Unnamed: 4
2294  2016-09-02 00:00:00       0.54
2015-09-02 00:00:00
                 SBES1H24 Unnamed: 1
2557  2015-09-02 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
2600  2015-09-02 00:00:00      -0.03
2014-09-02 00:00:00
                 SBES1H24 Unnamed: 1
2862  2014-09-02 00:00:00      -0.42
                 SBES1K24 Unnamed: 4
2905  2014-09-02 00:00:00      -0.23
2013-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2012-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-03 00:00:00
                SBES1H24 Unnamed: 1
731  2021-09-03 00:00:00        0.6
                SBES1K24 Unnamed: 4
774  2021-09-03 00:00:00        0.7
2020-09-03 00:00:00
                 SBES1H24 Unnamed: 1
1034  2020-09-03 00:00:00        0.1
                 SBES1K24 Unnamed: 4
1078  2020-09-03 00:00:00       0.14
2019-09-03 00:00:00
                 SBES1H24 Unnamed: 1
1341  2019-09-03 00:00:00      -0.11
                 SBES1K24 Unnamed: 4
1384  2019-09-03 00:00:00      -0.14
2018-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-03 00:00:00
                 SBES1H24 Unnamed: 1
2556  2015-09-03 00:00:00      -0.03
                 SBES1K24 Unnamed: 4
2599  2015-09-03 00:00:00       0.06
2014-09-03 00:00:00
                 SBES1H24 Unnamed: 1
2861  2014-09-03 00:00:00      -0.48
                 SBES1K24 Unnamed: 4
2904  2014-09-03 00:00:00      -0.26
2013-09-03 00:00:00
                 SBES1H24 Unnamed: 1
3166  2013-09-03 00:00:00        0.1
                 SBES1K24 Unnamed: 4
3208  2013-09-03 00:00:00       0.08
2012-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2020-09-04 00:00:00
                 SBES1H24 Unnamed: 1
1033  2020-09-04 00:00:00       0.09
                 SBES1K24 Unnamed: 4
1077  2020-09-04 00:00:00       0.12
2019-09-04 00:00:00
                 SBES1H24 Unnamed: 1
1340  2019-09-04 00:00:00      -0.14
                 SBES1K24 Unnamed: 4
1383  2019-09-04 00:00:00      -0.17
2018-09-04 00:00:00
                 SBES1H24 Unnamed: 1
1644  2018-09-04 00:00:00      -0.09
                 SBES1K24 Unnamed: 4
1686  2018-09-04 00:00:00      -0.08
2017-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-04 00:00:00
                 SBES1H24 Unnamed: 1
2555  2015-09-04 00:00:00      -0.08
                 SBES1K24 Unnamed: 4
2598  2015-09-04 00:00:00       0.01
2014-09-04 00:00:00
                 SBES1H24 Unnamed: 1
2860  2014-09-04 00:00:00      -0.54
                 SBES1K24 Unnamed: 4
2903  2014-09-04 00:00:00      -0.35
2013-09-04 00:00:00
                 SBES1H24 Unnamed: 1
3165  2013-09-04 00:00:00       0.06
                 SBES1K24 Unnamed: 4
3207  2013-09-04 00:00:00       0.06
2012-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-05 00:00:00
               SBES1H24 Unnamed: 1
55  2023-09-05 00:00:00       1.57
               SBES1K24 Unnamed: 4
55  2023-09-05 00:00:00       1.45
2022-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2020-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2019-09-05 00:00:00
                 SBES1H24 Unnamed: 1
1339  2019-09-05 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
1382  2019-09-05 00:00:00      -0.17
2018-09-05 00:00:00
                 SBES1H24 Unnamed: 1
1643  2018-09-05 00:00:00      -0.13
                 SBES1K24 Unnamed: 4
1685  2018-09-05 00:00:00      -0.13
2017-09-05 00:00:00
                 SBES1H24 Unnamed: 1
1947  2017-09-05 00:00:00      -0.22
                 SBES1K24 Unnamed: 4
1989  2017-09-05 00:00:00      -0.25
2016-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2014-09-05 00:00:00
                 SBES1H24 Unnamed: 1
2859  2014-09-05 00:00:00      -0.53
                 SBES1K24 Unnamed: 4
2902  2014-09-05 00:00:00      -0.37
2013-09-05 00:00:00
                 SBES1H24 Unnamed: 1
3164  2013-09-05 00:00:00       0.07
                 SBES1K24 Unnamed: 4
3206  2013-09-05 00:00:00       0.07
2012-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-06 00:00:00
               SBES1H24 Unnamed: 1
54  2023-09-06 00:00:00       1.45
               SBES1K24 Unnamed: 4
54  2023-09-06 00:00:00       1.37
2022-09-06 00:00:00
                SBES1H24 Unnamed: 1
426  2022-09-06 00:00:00       0.55
                SBES1K24 Unnamed: 4
468  2022-09-06 00:00:00       0.24
2021-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2020-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2019-09-06 00:00:00
                 SBES1H24 Unnamed: 1
1338  2019-09-06 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
1381  2019-09-06 00:00:00      -0.18
2018-09-06 00:00:00
                 SBES1H24 Unnamed: 1
1642  2018-09-06 00:00:00      -0.16
                 SBES1K24 Unnamed: 4
1684  2018-09-06 00:00:00      -0.13
2017-09-06 00:00:00
                 SBES1H24 Unnamed: 1
1946  2017-09-06 00:00:00      -0.17
                 SBES1K24 Unnamed: 4
1988  2017-09-06 00:00:00      -0.24
2016-09-06 00:00:00
                 SBES1H24 Unnamed: 1
2251  2016-09-06 00:00:00       0.51
                 SBES1K24 Unnamed: 4
2293  2016-09-06 00:00:00       0.49
2015-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2014-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2013-09-06 00:00:00
                 SBES1H24 Unnamed: 1
3163  2013-09-06 00:00:00       0.07
                 SBES1K24 Unnamed: 4
3205  2013-09-06 00:00:00       0.08
2012-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-07 00:00:00
               SBES1H24 Unnamed: 1
53  2023-09-07 00:00:00       1.56
               SBES1K24 Unnamed: 4
53  2023-09-07 00:00:00       1.43
2022-09-07 00:00:00
                SBES1H24 Unnamed: 1
425  2022-09-07 00:00:00       0.54
                SBES1K24 Unnamed: 4
467  2022-09-07 00:00:00       0.22
2021-09-07 00:00:00
                SBES1H24 Unnamed: 1
730  2021-09-07 00:00:00       0.57
                SBES1K24 Unnamed: 4
773  2021-09-07 00:00:00       0.67
2020-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2019-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2018-09-07 00:00:00
                 SBES1H24 Unnamed: 1
1641  2018-09-07 00:00:00      -0.15
                 SBES1K24 Unnamed: 4
1683  2018-09-07 00:00:00      -0.09
2017-09-07 00:00:00
                 SBES1H24 Unnamed: 1
1945  2017-09-07 00:00:00      -0.17
                 SBES1K24 Unnamed: 4
1987  2017-09-07 00:00:00      -0.26
2016-09-07 00:00:00
                 SBES1H24 Unnamed: 1
2250  2016-09-07 00:00:00       0.46
                 SBES1K24 Unnamed: 4
2292  2016-09-07 00:00:00       0.49
2015-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2014-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2013-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2012-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-08 00:00:00
               SBES1H24 Unnamed: 1
52  2023-09-08 00:00:00       1.48
               SBES1K24 Unnamed: 4
52  2023-09-08 00:00:00       1.35
2022-09-08 00:00:00
                SBES1H24 Unnamed: 1
424  2022-09-08 00:00:00       0.47
                SBES1K24 Unnamed: 4
466  2022-09-08 00:00:00       0.18
2021-09-08 00:00:00
                SBES1H24 Unnamed: 1
729  2021-09-08 00:00:00       0.53
                SBES1K24 Unnamed: 4
772  2021-09-08 00:00:00       0.63
2020-09-08 00:00:00
                 SBES1H24 Unnamed: 1
1032  2020-09-08 00:00:00       0.15
                 SBES1K24 Unnamed: 4
1076  2020-09-08 00:00:00       0.16
2019-09-08 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2018-09-08 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-08 00:00:00
                 SBES1H24 Unnamed: 1
1944  2017-09-08 00:00:00      -0.15
                 SBES1K24 Unnamed: 4
1986  2017-09-08 00:00:00      -0.24
2016-09-08 00:00:00
                 SBES1H24 Unnamed: 1
2249  2016-09-08 00:00:00       0.44
                 SBES1K24 Unnamed: 4
2291  2016-09-08 00:00:00        0.5
2015-09-08 00:00:00
                 SBES1H24 Unnamed: 1
2554  2015-09-08 00:00:00      -0.13
                 SBES1K24 Unnamed: 4
2597  2015-09-08 00:00:00      -0.04
2014-09-08 00:00:00
                 SBES1H24 Unnamed: 1
2858  2014-09-08 00:00:00      -0.47
                 SBES1K24 Unnamed: 4
2901  2014-09-08 00:00:00      -0.35
2013-09-08 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2012-09-08 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-09 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-09 00:00:00
                SBES1H24 Unnamed: 1
423  2022-09-09 00:00:00       0.47
                SBES1K24 Unnamed: 4
465  2022-09-09 00:00:00       0.17
2021-09-09 00:00:00
                SBES1H24 Unnamed: 1
728  2021-09-09 00:00:00        0.5
                SBES1K24 Unnamed: 4
771  2021-09-09 00:00:00       0.56
2020-09-09 00:00:00
                 SBES1H24 Unnamed: 1
1031  2020-09-09 00:00:00       0.17
                 SBES1K24 Unnamed: 4
1075  2020-09-09 00:00:00       0.15
2019-09-09 00:00:00
                 SBES1H24 Unnamed: 1
1337  2019-09-09 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
1380  2019-09-09 00:00:00      -0.17
2018-09-09 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-09 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-09 00:00:00
                 SBES1H24 Unnamed: 1
2248  2016-09-09 00:00:00        0.4
                 SBES1K24 Unnamed: 4
2290  2016-09-09 00:00:00       0.49
2015-09-09 00:00:00
                 SBES1H24 Unnamed: 1
2553  2015-09-09 00:00:00       -0.1
                 SBES1K24 Unnamed: 4
2596  2015-09-09 00:00:00          0
2014-09-09 00:00:00
                 SBES1H24 Unnamed: 1
2857  2014-09-09 00:00:00      -0.49
                 SBES1K24 Unnamed: 4
2900  2014-09-09 00:00:00      -0.36
2013-09-09 00:00:00
                 SBES1H24 Unnamed: 1
3162  2013-09-09 00:00:00        0.1
                 SBES1K24 Unnamed: 4
3204  2013-09-09 00:00:00       0.09
2012-09-09 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-10 00:00:00
                SBES1H24 Unnamed: 1
727  2021-09-10 00:00:00       0.45
                SBES1K24 Unnamed: 4
770  2021-09-10 00:00:00       0.53
2020-09-10 00:00:00
                 SBES1H24 Unnamed: 1
1030  2020-09-10 00:00:00       0.14
                 SBES1K24 Unnamed: 4
1074  2020-09-10 00:00:00       0.12
2019-09-10 00:00:00
                 SBES1H24 Unnamed: 1
1336  2019-09-10 00:00:00      -0.13
                 SBES1K24 Unnamed: 4
1379  2019-09-10 00:00:00      -0.17
2018-09-10 00:00:00
                 SBES1H24 Unnamed: 1
1640  2018-09-10 00:00:00      -0.15
                 SBES1K24 Unnamed: 4
1682  2018-09-10 00:00:00      -0.09
2017-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-10 00:00:00
                 SBES1H24 Unnamed: 1
2552  2015-09-10 00:00:00      -0.04
                 SBES1K24 Unnamed: 4
2595  2015-09-10 00:00:00       0.04
2014-09-10 00:00:00
                 SBES1H24 Unnamed: 1
2856  2014-09-10 00:00:00      -0.48
                 SBES1K24 Unnamed: 4
2899  2014-09-10 00:00:00      -0.41
2013-09-10 00:00:00
                 SBES1H24 Unnamed: 1
3161  2013-09-10 00:00:00        0.1
                 SBES1K24 Unnamed: 4
3203  2013-09-10 00:00:00       0.08
2012-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-11 00:00:00
               SBES1H24 Unnamed: 1
51  2023-09-11 00:00:00       1.43
               SBES1K24 Unnamed: 4
51  2023-09-11 00:00:00       1.22
2022-09-11 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-11 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2020-09-11 00:00:00
                 SBES1H24 Unnamed: 1
1029  2020-09-11 00:00:00       0.13
                 SBES1K24 Unnamed: 4
1073  2020-09-11 00:00:00       0.12
2019-09-11 00:00:00
                 SBES1H24 Unnamed: 1
1335  2019-09-11 00:00:00      -0.15
                 SBES1K24 Unnamed: 4
1378  2019-09-11 00:00:00       -0.2
2018-09-11 00:00:00
                 SBES1H24 Unnamed: 1
1639  2018-09-11 00:00:00      -0.18
                 SBES1K24 Unnamed: 4
1681  2018-09-11 00:00:00      -0.13
2017-09-11 00:00:00
                 SBES1H24 Unnamed: 1
1943  2017-09-11 00:00:00       -0.1
                 SBES1K24 Unnamed: 4
1985  2017-09-11 00:00:00      -0.18
2016-09-11 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-11 00:00:00
                 SBES1H24 Unnamed: 1
2551  2015-09-11 00:00:00       0.01
                 SBES1K24 Unnamed: 4
2594  2015-09-11 00:00:00       0.06
2014-09-11 00:00:00
                 SBES1H24 Unnamed: 1
2855  2014-09-11 00:00:00       -0.5
                 SBES1K24 Unnamed: 4
2898  2014-09-11 00:00:00       -0.4
2013-09-11 00:00:00

In [32]:
srednia_df

[{'month_day': '9-01', 'cena_flaja_srednia': 0.03142857142857141},
 {'month_day': '9-02', 'cena_flaja_srednia': -0.014999999999999977},
 {'month_day': '9-03', 'cena_flaja_srednia': -0.06666666666666665},
 {'month_day': '9-04', 'cena_flaja_srednia': -0.04833333333333334},
 {'month_day': '9-05', 'cena_flaja_srednia': 0.006666666666666682},
 {'month_day': '9-06', 'cena_flaja_srednia': 0.07142857142857141},
 {'month_day': '9-07', 'cena_flaja_srednia': 0.058333333333333355},
 {'month_day': '9-08', 'cena_flaja_srednia': 0.016249999999999987},
 {'month_day': '9-09', 'cena_flaja_srednia': 0.0},
 {'month_day': '9-10', 'cena_flaja_srednia': -0.029999999999999995},
 {'month_day': '9-11', 'cena_flaja_srednia': 0.022500000000000003},
 {'month_day': '9-12', 'cena_flaja_srednia': 0.0475},
 {'month_day': '9-13', 'cena_flaja_srednia': 0.04249999999999998},
 {'month_day': '9-14', 'cena_flaja_srednia': 0.018749999999999985},
 {'month_day': '9-15', 'cena_flaja_srednia': 0.010000000000000023},
 {'month_day': '9-16', 'cena_flaja_srednia': 0.01125},
 {'month_day': '9-17', 'cena_flaja_srednia': -0.03142857142857144},
 {'month_day': '9-18', 'cena_flaja_srednia': 0.006250000000000016},
 {'month_day': '9-19', 'cena_flaja_srednia': 0.04874999999999999},
 {'month_day': '9-20', 'cena_flaja_srednia': 0.03000000000000002},
 {'month_day': '9-21', 'cena_flaja_srednia': 0.015000000000000017},
 {'month_day': '9-22', 'cena_flaja_srednia': 0.013749999999999998},
 {'month_day': '9-23', 'cena_flaja_srednia': -0.012499999999999995},
 {'month_day': '9-24', 'cena_flaja_srednia': -0.012857142857142867},
 {'month_day': '9-25', 'cena_flaja_srednia': 0.04},
 {'month_day': '9-26', 'cena_flaja_srednia': 0.05500000000000001},
 {'month_day': '9-27', 'cena_flaja_srednia': 0.045},
 {'month_day': '9-28', 'cena_flaja_srednia': 0.0375},
 {'month_day': '9-29', 'cena_flaja_srednia': 0.024999999999999994},
 {'month_day': '9-30', 'cena_flaja_srednia': -1.734723475976807e-17}]

In [33]:
df_srednia = pd.DataFrame(srednia_df)

In [34]:
df_srednia

   month_day  cena_flaja_srednia
0       9-01        3.142857e-02
1       9-02       -1.500000e-02
2       9-03       -6.666667e-02
3       9-04       -4.833333e-02
4       9-05        6.666667e-03
5       9-06        7.142857e-02
6       9-07        5.833333e-02
7       9-08        1.625000e-02
8       9-09        0.000000e+00
9       9-10       -3.000000e-02
10      9-11        2.250000e-02
11      9-12        4.750000e-02
12      9-13        4.250000e-02
13      9-14        1.875000e-02
14      9-15        1.000000e-02
15      9-16        1.125000e-02
16      9-17       -3.142857e-02
17      9-18        6.250000e-03
18      9-19        4.875000e-02
19      9-20        3.000000e-02
20      9-21        1.500000e-02
21      9-22        1.375000e-02
22      9-23       -1.250000e-02
23      9-24       -1.285714e-02
24      9-25        4.000000e-02
25      9-26        5.500000e-02
26      9-27        4.500000e-02
27      9-28        3.750000e-02
28      9-29        2.500000e-02
29      9-30       -1.734723e-17

In [36]:
mediana_df = []
for month_day in days_list:
 df= oblicz_ceny_flaja(df1, df2, "SBES1H24" , "SBES1K24" , "Unnamed: 1", "Unnamed: 4", month_day )
 mediana_df.append({"month_day": month_day, "cena_flaja_mediana": df["cena_flaja1"].median()})

2023-09-01 00:00:00
               SBES1H24 Unnamed: 1
56  2023-09-01 00:00:00        1.5
               SBES1K24 Unnamed: 4
56  2023-09-01 00:00:00       1.26
2022-09-01 00:00:00
                SBES1H24 Unnamed: 1
428  2022-09-01 00:00:00       0.59
                SBES1K24 Unnamed: 4
470  2022-09-01 00:00:00       0.27
2021-09-01 00:00:00
                SBES1H24 Unnamed: 1
733  2021-09-01 00:00:00       0.68
                SBES1K24 Unnamed: 4
776  2021-09-01 00:00:00        0.8
2020-09-01 00:00:00
                 SBES1H24 Unnamed: 1
1036  2020-09-01 00:00:00       0.21
                 SBES1K24 Unnamed: 4
1080  2020-09-01 00:00:00       0.28
2019-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2018-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-01 00:00:00
                 SBES1H24 Unnamed: 1
1948  2017-09-01 00:00:00      -0.24
                 SBES1K24 Unnamed: 4
1990  2017-09-01 00:00:00      -0.25
2016-09-01 00:00:00
                 SBES1H24 Unnamed: 1
2253  2016-09-01 00:00:00       0.47
                 SBES1K24 Unnamed: 4
2295  2016-09-01 00:00:00       0.51
2015-09-01 00:00:00
                 SBES1H24 Unnamed: 1
2558  2015-09-01 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
2601  2015-09-01 00:00:00          0
2014-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2013-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2012-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-02 00:00:00
                SBES1H24 Unnamed: 1
427  2022-09-02 00:00:00       0.53
                SBES1K24 Unnamed: 4
469  2022-09-02 00:00:00       0.21
2021-09-02 00:00:00
                SBES1H24 Unnamed: 1
732  2021-09-02 00:00:00       0.66
                SBES1K24 Unnamed: 4
775  2021-09-02 00:00:00       0.74
2020-09-02 00:00:00
                 SBES1H24 Unnamed: 1
1035  2020-09-02 00:00:00       0.11
                 SBES1K24 Unnamed: 4
1079  2020-09-02 00:00:00       0.18
2019-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2018-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-02 00:00:00
                 SBES1H24 Unnamed: 1
2252  2016-09-02 00:00:00       0.56
                 SBES1K24 Unnamed: 4
2294  2016-09-02 00:00:00       0.54
2015-09-02 00:00:00
                 SBES1H24 Unnamed: 1
2557  2015-09-02 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
2600  2015-09-02 00:00:00      -0.03
2014-09-02 00:00:00
                 SBES1H24 Unnamed: 1
2862  2014-09-02 00:00:00      -0.42
                 SBES1K24 Unnamed: 4
2905  2014-09-02 00:00:00      -0.23
2013-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2012-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-03 00:00:00
                SBES1H24 Unnamed: 1
731  2021-09-03 00:00:00        0.6
                SBES1K24 Unnamed: 4
774  2021-09-03 00:00:00        0.7
2020-09-03 00:00:00
                 SBES1H24 Unnamed: 1
1034  2020-09-03 00:00:00        0.1
                 SBES1K24 Unnamed: 4
1078  2020-09-03 00:00:00       0.14
2019-09-03 00:00:00
                 SBES1H24 Unnamed: 1
1341  2019-09-03 00:00:00      -0.11
                 SBES1K24 Unnamed: 4
1384  2019-09-03 00:00:00      -0.14
2018-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-03 00:00:00
                 SBES1H24 Unnamed: 1
2556  2015-09-03 00:00:00      -0.03
                 SBES1K24 Unnamed: 4
2599  2015-09-03 00:00:00       0.06
2014-09-03 00:00:00
                 SBES1H24 Unnamed: 1
2861  2014-09-03 00:00:00      -0.48
                 SBES1K24 Unnamed: 4
2904  2014-09-03 00:00:00      -0.26
2013-09-03 00:00:00
                 SBES1H24 Unnamed: 1
3166  2013-09-03 00:00:00        0.1
                 SBES1K24 Unnamed: 4
3208  2013-09-03 00:00:00       0.08
2012-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2020-09-04 00:00:00
                 SBES1H24 Unnamed: 1
1033  2020-09-04 00:00:00       0.09
                 SBES1K24 Unnamed: 4
1077  2020-09-04 00:00:00       0.12
2019-09-04 00:00:00
                 SBES1H24 Unnamed: 1
1340  2019-09-04 00:00:00      -0.14
                 SBES1K24 Unnamed: 4
1383  2019-09-04 00:00:00      -0.17
2018-09-04 00:00:00
                 SBES1H24 Unnamed: 1
1644  2018-09-04 00:00:00      -0.09
                 SBES1K24 Unnamed: 4
1686  2018-09-04 00:00:00      -0.08
2017-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-04 00:00:00
                 SBES1H24 Unnamed: 1
2555  2015-09-04 00:00:00      -0.08
                 SBES1K24 Unnamed: 4
2598  2015-09-04 00:00:00       0.01
2014-09-04 00:00:00
                 SBES1H24 Unnamed: 1
2860  2014-09-04 00:00:00      -0.54
                 SBES1K24 Unnamed: 4
2903  2014-09-04 00:00:00      -0.35
2013-09-04 00:00:00
                 SBES1H24 Unnamed: 1
3165  2013-09-04 00:00:00       0.06
                 SBES1K24 Unnamed: 4
3207  2013-09-04 00:00:00       0.06
2012-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-05 00:00:00
               SBES1H24 Unnamed: 1
55  2023-09-05 00:00:00       1.57
               SBES1K24 Unnamed: 4
55  2023-09-05 00:00:00       1.45
2022-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2020-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2019-09-05 00:00:00
                 SBES1H24 Unnamed: 1
1339  2019-09-05 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
1382  2019-09-05 00:00:00      -0.17
2018-09-05 00:00:00
                 SBES1H24 Unnamed: 1
1643  2018-09-05 00:00:00      -0.13
                 SBES1K24 Unnamed: 4
1685  2018-09-05 00:00:00      -0.13
2017-09-05 00:00:00
                 SBES1H24 Unnamed: 1
1947  2017-09-05 00:00:00      -0.22
                 SBES1K24 Unnamed: 4
1989  2017-09-05 00:00:00      -0.25
2016-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2014-09-05 00:00:00
                 SBES1H24 Unnamed: 1
2859  2014-09-05 00:00:00      -0.53
                 SBES1K24 Unnamed: 4
2902  2014-09-05 00:00:00      -0.37
2013-09-05 00:00:00
                 SBES1H24 Unnamed: 1
3164  2013-09-05 00:00:00       0.07
                 SBES1K24 Unnamed: 4
3206  2013-09-05 00:00:00       0.07
2012-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-06 00:00:00
               SBES1H24 Unnamed: 1
54  2023-09-06 00:00:00       1.45
               SBES1K24 Unnamed: 4
54  2023-09-06 00:00:00       1.37
2022-09-06 00:00:00
                SBES1H24 Unnamed: 1
426  2022-09-06 00:00:00       0.55
                SBES1K24 Unnamed: 4
468  2022-09-06 00:00:00       0.24
2021-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2020-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2019-09-06 00:00:00
                 SBES1H24 Unnamed: 1
1338  2019-09-06 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
1381  2019-09-06 00:00:00      -0.18
2018-09-06 00:00:00
                 SBES1H24 Unnamed: 1
1642  2018-09-06 00:00:00      -0.16
                 SBES1K24 Unnamed: 4
1684  2018-09-06 00:00:00      -0.13
2017-09-06 00:00:00
                 SBES1H24 Unnamed: 1
1946  2017-09-06 00:00:00      -0.17
                 SBES1K24 Unnamed: 4
1988  2017-09-06 00:00:00      -0.24
2016-09-06 00:00:00
                 SBES1H24 Unnamed: 1
2251  2016-09-06 00:00:00       0.51
                 SBES1K24 Unnamed: 4
2293  2016-09-06 00:00:00       0.49
2015-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2014-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2013-09-06 00:00:00
                 SBES1H24 Unnamed: 1
3163  2013-09-06 00:00:00       0.07
                 SBES1K24 Unnamed: 4
3205  2013-09-06 00:00:00       0.08
2012-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-07 00:00:00
               SBES1H24 Unnamed: 1
53  2023-09-07 00:00:00       1.56
               SBES1K24 Unnamed: 4
53  2023-09-07 00:00:00       1.43
2022-09-07 00:00:00
                SBES1H24 Unnamed: 1
425  2022-09-07 00:00:00       0.54
                SBES1K24 Unnamed: 4
467  2022-09-07 00:00:00       0.22
2021-09-07 00:00:00
                SBES1H24 Unnamed: 1
730  2021-09-07 00:00:00       0.57
                SBES1K24 Unnamed: 4
773  2021-09-07 00:00:00       0.67
2020-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2019-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2018-09-07 00:00:00
                 SBES1H24 Unnamed: 1
1641  2018-09-07 00:00:00      -0.15
                 SBES1K24 Unnamed: 4
1683  2018-09-07 00:00:00      -0.09
2017-09-07 00:00:00
                 SBES1H24 Unnamed: 1
1945  2017-09-07 00:00:00      -0.17
                 SBES1K24 Unnamed: 4
1987  2017-09-07 00:00:00      -0.26
2016-09-07 00:00:00
                 SBES1H24 Unnamed: 1
2250  2016-09-07 00:00:00       0.46
                 SBES1K24 Unnamed: 4
2292  2016-09-07 00:00:00       0.49
2015-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2014-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2013-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2012-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-08 00:00:00
               SBES1H24 Unnamed: 1
52  2023-09-08 00:00:00       1.48
               SBES1K24 Unnamed: 4
52  2023-09-08 00:00:00       1.35
2022-09-08 00:00:00
                SBES1H24 Unnamed: 1
424  2022-09-08 00:00:00       0.47
                SBES1K24 Unnamed: 4
466  2022-09-08 00:00:00       0.18
2021-09-08 00:00:00
                SBES1H24 Unnamed: 1
729  2021-09-08 00:00:00       0.53
                SBES1K24 Unnamed: 4
772  2021-09-08 00:00:00       0.63
2020-09-08 00:00:00
                 SBES1H24 Unnamed: 1
1032  2020-09-08 00:00:00       0.15
                 SBES1K24 Unnamed: 4
1076  2020-09-08 00:00:00       0.16
2019-09-08 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2018-09-08 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-08 00:00:00
                 SBES1H24 Unnamed: 1
1944  2017-09-08 00:00:00      -0.15
                 SBES1K24 Unnamed: 4
1986  2017-09-08 00:00:00      -0.24
2016-09-08 00:00:00
                 SBES1H24 Unnamed: 1
2249  2016-09-08 00:00:00       0.44
                 SBES1K24 Unnamed: 4
2291  2016-09-08 00:00:00        0.5
2015-09-08 00:00:00
                 SBES1H24 Unnamed: 1
2554  2015-09-08 00:00:00      -0.13
                 SBES1K24 Unnamed: 4
2597  2015-09-08 00:00:00      -0.04
2014-09-08 00:00:00
                 SBES1H24 Unnamed: 1
2858  2014-09-08 00:00:00      -0.47
                 SBES1K24 Unnamed: 4
2901  2014-09-08 00:00:00      -0.35
2013-09-08 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2012-09-08 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-09 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-09 00:00:00
                SBES1H24 Unnamed: 1
423  2022-09-09 00:00:00       0.47
                SBES1K24 Unnamed: 4
465  2022-09-09 00:00:00       0.17
2021-09-09 00:00:00
                SBES1H24 Unnamed: 1
728  2021-09-09 00:00:00        0.5
                SBES1K24 Unnamed: 4
771  2021-09-09 00:00:00       0.56
2020-09-09 00:00:00
                 SBES1H24 Unnamed: 1
1031  2020-09-09 00:00:00       0.17
                 SBES1K24 Unnamed: 4
1075  2020-09-09 00:00:00       0.15
2019-09-09 00:00:00
                 SBES1H24 Unnamed: 1
1337  2019-09-09 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
1380  2019-09-09 00:00:00      -0.17
2018-09-09 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-09 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-09 00:00:00
                 SBES1H24 Unnamed: 1
2248  2016-09-09 00:00:00        0.4
                 SBES1K24 Unnamed: 4
2290  2016-09-09 00:00:00       0.49
2015-09-09 00:00:00
                 SBES1H24 Unnamed: 1
2553  2015-09-09 00:00:00       -0.1
                 SBES1K24 Unnamed: 4
2596  2015-09-09 00:00:00          0
2014-09-09 00:00:00
                 SBES1H24 Unnamed: 1
2857  2014-09-09 00:00:00      -0.49
                 SBES1K24 Unnamed: 4
2900  2014-09-09 00:00:00      -0.36
2013-09-09 00:00:00
                 SBES1H24 Unnamed: 1
3162  2013-09-09 00:00:00        0.1
                 SBES1K24 Unnamed: 4
3204  2013-09-09 00:00:00       0.09
2012-09-09 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-10 00:00:00
                SBES1H24 Unnamed: 1
727  2021-09-10 00:00:00       0.45
                SBES1K24 Unnamed: 4
770  2021-09-10 00:00:00       0.53
2020-09-10 00:00:00
                 SBES1H24 Unnamed: 1
1030  2020-09-10 00:00:00       0.14
                 SBES1K24 Unnamed: 4
1074  2020-09-10 00:00:00       0.12
2019-09-10 00:00:00
                 SBES1H24 Unnamed: 1
1336  2019-09-10 00:00:00      -0.13
                 SBES1K24 Unnamed: 4
1379  2019-09-10 00:00:00      -0.17
2018-09-10 00:00:00
                 SBES1H24 Unnamed: 1
1640  2018-09-10 00:00:00      -0.15
                 SBES1K24 Unnamed: 4
1682  2018-09-10 00:00:00      -0.09
2017-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-10 00:00:00
                 SBES1H24 Unnamed: 1
2552  2015-09-10 00:00:00      -0.04
                 SBES1K24 Unnamed: 4
2595  2015-09-10 00:00:00       0.04
2014-09-10 00:00:00
                 SBES1H24 Unnamed: 1
2856  2014-09-10 00:00:00      -0.48
                 SBES1K24 Unnamed: 4
2899  2014-09-10 00:00:00      -0.41
2013-09-10 00:00:00
                 SBES1H24 Unnamed: 1
3161  2013-09-10 00:00:00        0.1
                 SBES1K24 Unnamed: 4
3203  2013-09-10 00:00:00       0.08
2012-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-11 00:00:00
               SBES1H24 Unnamed: 1
51  2023-09-11 00:00:00       1.43
               SBES1K24 Unnamed: 4
51  2023-09-11 00:00:00       1.22
2022-09-11 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-11 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2020-09-11 00:00:00
                 SBES1H24 Unnamed: 1
1029  2020-09-11 00:00:00       0.13
                 SBES1K24 Unnamed: 4
1073  2020-09-11 00:00:00       0.12
2019-09-11 00:00:00
                 SBES1H24 Unnamed: 1
1335  2019-09-11 00:00:00      -0.15
                 SBES1K24 Unnamed: 4
1378  2019-09-11 00:00:00       -0.2
2018-09-11 00:00:00
                 SBES1H24 Unnamed: 1
1639  2018-09-11 00:00:00      -0.18
                 SBES1K24 Unnamed: 4
1681  2018-09-11 00:00:00      -0.13
2017-09-11 00:00:00
                 SBES1H24 Unnamed: 1
1943  2017-09-11 00:00:00       -0.1
                 SBES1K24 Unnamed: 4
1985  2017-09-11 00:00:00      -0.18
2016-09-11 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-11 00:00:00
                 SBES1H24 Unnamed: 1
2551  2015-09-11 00:00:00       0.01
                 SBES1K24 Unnamed: 4
2594  2015-09-11 00:00:00       0.06
2014-09-11 00:00:00
                 SBES1H24 Unnamed: 1
2855  2014-09-11 00:00:00       -0.5
                 SBES1K24 Unnamed: 4
2898  2014-09-11 00:00:00       -0.4
2013-09-11 00:00:00

In [37]:
mediana_df

[{'month_day': '9-01', 'cena_flaja_mediana': -0.040000000000000036},
 {'month_day': '9-02', 'cena_flaja_mediana': -0.07499999999999998},
 {'month_day': '9-03', 'cena_flaja_mediana': -0.065},
 {'month_day': '9-04', 'cena_flaja_mediana': -0.019999999999999997},
 {'month_day': '9-05', 'cena_flaja_mediana': 0.015},
 {'month_day': '9-06', 'cena_flaja_mediana': 0.06},
 {'month_day': '9-07', 'cena_flaja_mediana': 0.030000000000000013},
 {'month_day': '9-08', 'cena_flaja_mediana': -0.035},
 {'month_day': '9-09', 'cena_flaja_mediana': -0.025000000000000022},
 {'month_day': '9-10', 'cena_flaja_mediana': -0.06},
 {'month_day': '9-11', 'cena_flaja_mediana': 0.020000000000000004},
 {'month_day': '9-12', 'cena_flaja_mediana': 0.039999999999999994},
 {'month_day': '9-13', 'cena_flaja_mediana': 0.04},
 {'month_day': '9-14', 'cena_flaja_mediana': -0.005000000000000001},
 {'month_day': '9-15', 'cena_flaja_mediana': -0.010000000000000002},
 {'month_day': '9-16', 'cena_flaja_mediana': 0.0049999999999999975},
 {'month_day': '9-17', 'cena_flaja_mediana': -0.03},
 {'month_day': '9-18', 'cena_flaja_mediana': 0.01},
 {'month_day': '9-19', 'cena_flaja_mediana': 0.029999999999999992},
 {'month_day': '9-20', 'cena_flaja_mediana': 0.020000000000000004},
 {'month_day': '9-21', 'cena_flaja_mediana': -2.6020852139652106e-18},
 {'month_day': '9-22', 'cena_flaja_mediana': -0.0049999999999999906},
 {'month_day': '9-23', 'cena_flaja_mediana': -0.010000000000000009},
 {'month_day': '9-24', 'cena_flaja_mediana': 0.010000000000000009},
 {'month_day': '9-25', 'cena_flaja_mediana': 0.030000000000000006},
 {'month_day': '9-26', 'cena_flaja_mediana': 0.025},
 {'month_day': '9-27', 'cena_flaja_mediana': 0.03999999999999999},
 {'month_day': '9-28', 'cena_flaja_mediana': 0.0049999999999999975},
 {'month_day': '9-29', 'cena_flaja_mediana': 1.3877787807814457e-17},
 {'month_day': '9-30', 'cena_flaja_mediana': -0.0049999999999999975}]

In [38]:
df_mediana = pd.DataFrame(mediana_df)

In [39]:
df_mediana

   month_day  cena_flaja_mediana
0       9-01       -4.000000e-02
1       9-02       -7.500000e-02
2       9-03       -6.500000e-02
3       9-04       -2.000000e-02
4       9-05        1.500000e-02
5       9-06        6.000000e-02
6       9-07        3.000000e-02
7       9-08       -3.500000e-02
8       9-09       -2.500000e-02
9       9-10       -6.000000e-02
10      9-11        2.000000e-02
11      9-12        4.000000e-02
12      9-13        4.000000e-02
13      9-14       -5.000000e-03
14      9-15       -1.000000e-02
15      9-16        5.000000e-03
16      9-17       -3.000000e-02
17      9-18        1.000000e-02
18      9-19        3.000000e-02
19      9-20        2.000000e-02
20      9-21       -2.602085e-18
21      9-22       -5.000000e-03
22      9-23       -1.000000e-02
23      9-24        1.000000e-02
24      9-25        3.000000e-02
25      9-26        2.500000e-02
26      9-27        4.000000e-02
27      9-28        5.000000e-03
28      9-29        1.387779e-17
29      9-30       -5.000000e-03

In [41]:
haj_df = []
for month_day in days_list:
 df= oblicz_ceny_flaja(df1, df2, "SBES1H24" , "SBES1K24" , "Unnamed: 1", "Unnamed: 4", month_day )
 haj_df.append({"month_day": month_day, "cena_flaja_haj": df["cena_flaja1"].max()})

2023-09-01 00:00:00
               SBES1H24 Unnamed: 1
56  2023-09-01 00:00:00        1.5
               SBES1K24 Unnamed: 4
56  2023-09-01 00:00:00       1.26
2022-09-01 00:00:00
                SBES1H24 Unnamed: 1
428  2022-09-01 00:00:00       0.59
                SBES1K24 Unnamed: 4
470  2022-09-01 00:00:00       0.27
2021-09-01 00:00:00
                SBES1H24 Unnamed: 1
733  2021-09-01 00:00:00       0.68
                SBES1K24 Unnamed: 4
776  2021-09-01 00:00:00        0.8
2020-09-01 00:00:00
                 SBES1H24 Unnamed: 1
1036  2020-09-01 00:00:00       0.21
                 SBES1K24 Unnamed: 4
1080  2020-09-01 00:00:00       0.28
2019-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2018-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-01 00:00:00
                 SBES1H24 Unnamed: 1
1948  2017-09-01 00:00:00      -0.24
                 SBES1K24 Unnamed: 4
1990  2017-09-01 00:00:00      -0.25
2016-09-01 00:00:00
                 SBES1H24 Unnamed: 1
2253  2016-09-01 00:00:00       0.47
                 SBES1K24 Unnamed: 4
2295  2016-09-01 00:00:00       0.51
2015-09-01 00:00:00
                 SBES1H24 Unnamed: 1
2558  2015-09-01 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
2601  2015-09-01 00:00:00          0
2014-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2013-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2012-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-02 00:00:00
                SBES1H24 Unnamed: 1
427  2022-09-02 00:00:00       0.53
                SBES1K24 Unnamed: 4
469  2022-09-02 00:00:00       0.21
2021-09-02 00:00:00
                SBES1H24 Unnamed: 1
732  2021-09-02 00:00:00       0.66
                SBES1K24 Unnamed: 4
775  2021-09-02 00:00:00       0.74
2020-09-02 00:00:00
                 SBES1H24 Unnamed: 1
1035  2020-09-02 00:00:00       0.11
                 SBES1K24 Unnamed: 4
1079  2020-09-02 00:00:00       0.18
2019-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2018-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-02 00:00:00
                 SBES1H24 Unnamed: 1
2252  2016-09-02 00:00:00       0.56
                 SBES1K24 Unnamed: 4
2294  2016-09-02 00:00:00       0.54
2015-09-02 00:00:00
                 SBES1H24 Unnamed: 1
2557  2015-09-02 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
2600  2015-09-02 00:00:00      -0.03
2014-09-02 00:00:00
                 SBES1H24 Unnamed: 1
2862  2014-09-02 00:00:00      -0.42
                 SBES1K24 Unnamed: 4
2905  2014-09-02 00:00:00      -0.23
2013-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2012-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-03 00:00:00
                SBES1H24 Unnamed: 1
731  2021-09-03 00:00:00        0.6
                SBES1K24 Unnamed: 4
774  2021-09-03 00:00:00        0.7
2020-09-03 00:00:00
                 SBES1H24 Unnamed: 1
1034  2020-09-03 00:00:00        0.1
                 SBES1K24 Unnamed: 4
1078  2020-09-03 00:00:00       0.14
2019-09-03 00:00:00
                 SBES1H24 Unnamed: 1
1341  2019-09-03 00:00:00      -0.11
                 SBES1K24 Unnamed: 4
1384  2019-09-03 00:00:00      -0.14
2018-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-03 00:00:00
                 SBES1H24 Unnamed: 1
2556  2015-09-03 00:00:00      -0.03
                 SBES1K24 Unnamed: 4
2599  2015-09-03 00:00:00       0.06
2014-09-03 00:00:00
                 SBES1H24 Unnamed: 1
2861  2014-09-03 00:00:00      -0.48
                 SBES1K24 Unnamed: 4
2904  2014-09-03 00:00:00      -0.26
2013-09-03 00:00:00
                 SBES1H24 Unnamed: 1
3166  2013-09-03 00:00:00        0.1
                 SBES1K24 Unnamed: 4
3208  2013-09-03 00:00:00       0.08
2012-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2020-09-04 00:00:00
                 SBES1H24 Unnamed: 1
1033  2020-09-04 00:00:00       0.09
                 SBES1K24 Unnamed: 4
1077  2020-09-04 00:00:00       0.12
2019-09-04 00:00:00
                 SBES1H24 Unnamed: 1
1340  2019-09-04 00:00:00      -0.14
                 SBES1K24 Unnamed: 4
1383  2019-09-04 00:00:00      -0.17
2018-09-04 00:00:00
                 SBES1H24 Unnamed: 1
1644  2018-09-04 00:00:00      -0.09
                 SBES1K24 Unnamed: 4
1686  2018-09-04 00:00:00      -0.08
2017-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-04 00:00:00
                 SBES1H24 Unnamed: 1
2555  2015-09-04 00:00:00      -0.08
                 SBES1K24 Unnamed: 4
2598  2015-09-04 00:00:00       0.01
2014-09-04 00:00:00
                 SBES1H24 Unnamed: 1
2860  2014-09-04 00:00:00      -0.54
                 SBES1K24 Unnamed: 4
2903  2014-09-04 00:00:00      -0.35
2013-09-04 00:00:00
                 SBES1H24 Unnamed: 1
3165  2013-09-04 00:00:00       0.06
                 SBES1K24 Unnamed: 4
3207  2013-09-04 00:00:00       0.06
2012-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-05 00:00:00
               SBES1H24 Unnamed: 1
55  2023-09-05 00:00:00       1.57
               SBES1K24 Unnamed: 4
55  2023-09-05 00:00:00       1.45
2022-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2020-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2019-09-05 00:00:00
                 SBES1H24 Unnamed: 1
1339  2019-09-05 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
1382  2019-09-05 00:00:00      -0.17
2018-09-05 00:00:00
                 SBES1H24 Unnamed: 1
1643  2018-09-05 00:00:00      -0.13
                 SBES1K24 Unnamed: 4
1685  2018-09-05 00:00:00      -0.13
2017-09-05 00:00:00
                 SBES1H24 Unnamed: 1
1947  2017-09-05 00:00:00      -0.22
                 SBES1K24 Unnamed: 4
1989  2017-09-05 00:00:00      -0.25
2016-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2014-09-05 00:00:00
                 SBES1H24 Unnamed: 1
2859  2014-09-05 00:00:00      -0.53
                 SBES1K24 Unnamed: 4
2902  2014-09-05 00:00:00      -0.37
2013-09-05 00:00:00
                 SBES1H24 Unnamed: 1
3164  2013-09-05 00:00:00       0.07
                 SBES1K24 Unnamed: 4
3206  2013-09-05 00:00:00       0.07
2012-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-06 00:00:00
               SBES1H24 Unnamed: 1
54  2023-09-06 00:00:00       1.45
               SBES1K24 Unnamed: 4
54  2023-09-06 00:00:00       1.37
2022-09-06 00:00:00
                SBES1H24 Unnamed: 1
426  2022-09-06 00:00:00       0.55
                SBES1K24 Unnamed: 4
468  2022-09-06 00:00:00       0.24
2021-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2020-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2019-09-06 00:00:00
                 SBES1H24 Unnamed: 1
1338  2019-09-06 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
1381  2019-09-06 00:00:00      -0.18
2018-09-06 00:00:00
                 SBES1H24 Unnamed: 1
1642  2018-09-06 00:00:00      -0.16
                 SBES1K24 Unnamed: 4
1684  2018-09-06 00:00:00      -0.13
2017-09-06 00:00:00
                 SBES1H24 Unnamed: 1
1946  2017-09-06 00:00:00      -0.17
                 SBES1K24 Unnamed: 4
1988  2017-09-06 00:00:00      -0.24
2016-09-06 00:00:00
                 SBES1H24 Unnamed: 1
2251  2016-09-06 00:00:00       0.51
                 SBES1K24 Unnamed: 4
2293  2016-09-06 00:00:00       0.49
2015-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2014-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2013-09-06 00:00:00
                 SBES1H24 Unnamed: 1
3163  2013-09-06 00:00:00       0.07
                 SBES1K24 Unnamed: 4
3205  2013-09-06 00:00:00       0.08
2012-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-07 00:00:00
               SBES1H24 Unnamed: 1
53  2023-09-07 00:00:00       1.56
               SBES1K24 Unnamed: 4
53  2023-09-07 00:00:00       1.43
2022-09-07 00:00:00
                SBES1H24 Unnamed: 1
425  2022-09-07 00:00:00       0.54
                SBES1K24 Unnamed: 4
467  2022-09-07 00:00:00       0.22
2021-09-07 00:00:00
                SBES1H24 Unnamed: 1
730  2021-09-07 00:00:00       0.57
                SBES1K24 Unnamed: 4
773  2021-09-07 00:00:00       0.67
2020-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2019-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2018-09-07 00:00:00
                 SBES1H24 Unnamed: 1
1641  2018-09-07 00:00:00      -0.15
                 SBES1K24 Unnamed: 4
1683  2018-09-07 00:00:00      -0.09
2017-09-07 00:00:00
                 SBES1H24 Unnamed: 1
1945  2017-09-07 00:00:00      -0.17
                 SBES1K24 Unnamed: 4
1987  2017-09-07 00:00:00      -0.26
2016-09-07 00:00:00
                 SBES1H24 Unnamed: 1
2250  2016-09-07 00:00:00       0.46
                 SBES1K24 Unnamed: 4
2292  2016-09-07 00:00:00       0.49
2015-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2014-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2013-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2012-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-08 00:00:00
               SBES1H24 Unnamed: 1
52  2023-09-08 00:00:00       1.48
               SBES1K24 Unnamed: 4
52  2023-09-08 00:00:00       1.35
2022-09-08 00:00:00
                SBES1H24 Unnamed: 1
424  2022-09-08 00:00:00       0.47
                SBES1K24 Unnamed: 4
466  2022-09-08 00:00:00       0.18
2021-09-08 00:00:00
                SBES1H24 Unnamed: 1
729  2021-09-08 00:00:00       0.53
                SBES1K24 Unnamed: 4
772  2021-09-08 00:00:00       0.63
2020-09-08 00:00:00
                 SBES1H24 Unnamed: 1
1032  2020-09-08 00:00:00       0.15
                 SBES1K24 Unnamed: 4
1076  2020-09-08 00:00:00       0.16
2019-09-08 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2018-09-08 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-08 00:00:00
                 SBES1H24 Unnamed: 1
1944  2017-09-08 00:00:00      -0.15
                 SBES1K24 Unnamed: 4
1986  2017-09-08 00:00:00      -0.24
2016-09-08 00:00:00
                 SBES1H24 Unnamed: 1
2249  2016-09-08 00:00:00       0.44
                 SBES1K24 Unnamed: 4
2291  2016-09-08 00:00:00        0.5
2015-09-08 00:00:00
                 SBES1H24 Unnamed: 1
2554  2015-09-08 00:00:00      -0.13
                 SBES1K24 Unnamed: 4
2597  2015-09-08 00:00:00      -0.04
2014-09-08 00:00:00
                 SBES1H24 Unnamed: 1
2858  2014-09-08 00:00:00      -0.47
                 SBES1K24 Unnamed: 4
2901  2014-09-08 00:00:00      -0.35
2013-09-08 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2012-09-08 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-09 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-09 00:00:00
                SBES1H24 Unnamed: 1
423  2022-09-09 00:00:00       0.47
                SBES1K24 Unnamed: 4
465  2022-09-09 00:00:00       0.17
2021-09-09 00:00:00
                SBES1H24 Unnamed: 1
728  2021-09-09 00:00:00        0.5
                SBES1K24 Unnamed: 4
771  2021-09-09 00:00:00       0.56
2020-09-09 00:00:00
                 SBES1H24 Unnamed: 1
1031  2020-09-09 00:00:00       0.17
                 SBES1K24 Unnamed: 4
1075  2020-09-09 00:00:00       0.15
2019-09-09 00:00:00
                 SBES1H24 Unnamed: 1
1337  2019-09-09 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
1380  2019-09-09 00:00:00      -0.17
2018-09-09 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-09 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-09 00:00:00
                 SBES1H24 Unnamed: 1
2248  2016-09-09 00:00:00        0.4
                 SBES1K24 Unnamed: 4
2290  2016-09-09 00:00:00       0.49
2015-09-09 00:00:00
                 SBES1H24 Unnamed: 1
2553  2015-09-09 00:00:00       -0.1
                 SBES1K24 Unnamed: 4
2596  2015-09-09 00:00:00          0
2014-09-09 00:00:00
                 SBES1H24 Unnamed: 1
2857  2014-09-09 00:00:00      -0.49
                 SBES1K24 Unnamed: 4
2900  2014-09-09 00:00:00      -0.36
2013-09-09 00:00:00
                 SBES1H24 Unnamed: 1
3162  2013-09-09 00:00:00        0.1
                 SBES1K24 Unnamed: 4
3204  2013-09-09 00:00:00       0.09
2012-09-09 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-10 00:00:00
                SBES1H24 Unnamed: 1
727  2021-09-10 00:00:00       0.45
                SBES1K24 Unnamed: 4
770  2021-09-10 00:00:00       0.53
2020-09-10 00:00:00
                 SBES1H24 Unnamed: 1
1030  2020-09-10 00:00:00       0.14
                 SBES1K24 Unnamed: 4
1074  2020-09-10 00:00:00       0.12
2019-09-10 00:00:00
                 SBES1H24 Unnamed: 1
1336  2019-09-10 00:00:00      -0.13
                 SBES1K24 Unnamed: 4
1379  2019-09-10 00:00:00      -0.17
2018-09-10 00:00:00
                 SBES1H24 Unnamed: 1
1640  2018-09-10 00:00:00      -0.15
                 SBES1K24 Unnamed: 4
1682  2018-09-10 00:00:00      -0.09
2017-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-10 00:00:00
                 SBES1H24 Unnamed: 1
2552  2015-09-10 00:00:00      -0.04
                 SBES1K24 Unnamed: 4
2595  2015-09-10 00:00:00       0.04
2014-09-10 00:00:00
                 SBES1H24 Unnamed: 1
2856  2014-09-10 00:00:00      -0.48
                 SBES1K24 Unnamed: 4
2899  2014-09-10 00:00:00      -0.41
2013-09-10 00:00:00
                 SBES1H24 Unnamed: 1
3161  2013-09-10 00:00:00        0.1
                 SBES1K24 Unnamed: 4
3203  2013-09-10 00:00:00       0.08
2012-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-11 00:00:00
               SBES1H24 Unnamed: 1
51  2023-09-11 00:00:00       1.43
               SBES1K24 Unnamed: 4
51  2023-09-11 00:00:00       1.22
2022-09-11 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-11 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2020-09-11 00:00:00
                 SBES1H24 Unnamed: 1
1029  2020-09-11 00:00:00       0.13
                 SBES1K24 Unnamed: 4
1073  2020-09-11 00:00:00       0.12
2019-09-11 00:00:00
                 SBES1H24 Unnamed: 1
1335  2019-09-11 00:00:00      -0.15
                 SBES1K24 Unnamed: 4
1378  2019-09-11 00:00:00       -0.2
2018-09-11 00:00:00
                 SBES1H24 Unnamed: 1
1639  2018-09-11 00:00:00      -0.18
                 SBES1K24 Unnamed: 4
1681  2018-09-11 00:00:00      -0.13
2017-09-11 00:00:00
                 SBES1H24 Unnamed: 1
1943  2017-09-11 00:00:00       -0.1
                 SBES1K24 Unnamed: 4
1985  2017-09-11 00:00:00      -0.18
2016-09-11 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-11 00:00:00
                 SBES1H24 Unnamed: 1
2551  2015-09-11 00:00:00       0.01
                 SBES1K24 Unnamed: 4
2594  2015-09-11 00:00:00       0.06
2014-09-11 00:00:00
                 SBES1H24 Unnamed: 1
2855  2014-09-11 00:00:00       -0.5
                 SBES1K24 Unnamed: 4
2898  2014-09-11 00:00:00       -0.4
2013-09-11 00:00:00

In [42]:
df_haj = pd.DataFrame(haj_df)

In [43]:
df_haj

   month_day  cena_flaja_haj
0       9-01            0.32
1       9-02            0.32
2       9-03            0.03
3       9-04            0.03
4       9-05            0.12
5       9-06            0.31
6       9-07            0.32
7       9-08            0.29
8       9-09            0.30
9       9-10            0.04
10      9-11            0.21
11      9-12            0.26
12      9-13            0.20
13      9-14            0.19
14      9-15            0.17
15      9-16            0.19
16      9-17            0.04
17      9-18            0.13
18      9-19            0.18
19      9-20            0.17
20      9-21            0.15
21      9-22            0.22
22      9-23            0.14
23      9-24            0.04
24      9-25            0.23
25      9-26            0.29
26      9-27            0.30
27      9-28            0.27
28      9-29            0.22
29      9-30            0.15

In [44]:
low_df = []
for month_day in days_list:
 df= oblicz_ceny_flaja(df1, df2, "SBES1H24" , "SBES1K24" , "Unnamed: 1", "Unnamed: 4", month_day )
 low_df.append({"month_day": month_day, "cena_flaja_low": df["cena_flaja1"].min()})

2023-09-01 00:00:00
               SBES1H24 Unnamed: 1
56  2023-09-01 00:00:00        1.5
               SBES1K24 Unnamed: 4
56  2023-09-01 00:00:00       1.26
2022-09-01 00:00:00
                SBES1H24 Unnamed: 1
428  2022-09-01 00:00:00       0.59
                SBES1K24 Unnamed: 4
470  2022-09-01 00:00:00       0.27
2021-09-01 00:00:00
                SBES1H24 Unnamed: 1
733  2021-09-01 00:00:00       0.68
                SBES1K24 Unnamed: 4
776  2021-09-01 00:00:00        0.8
2020-09-01 00:00:00
                 SBES1H24 Unnamed: 1
1036  2020-09-01 00:00:00       0.21
                 SBES1K24 Unnamed: 4
1080  2020-09-01 00:00:00       0.28
2019-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2018-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-01 00:00:00
                 SBES1H24 Unnamed: 1
1948  2017-09-01 00:00:00      -0.24
                 SBES1K24 Unnamed: 4
1990  2017-09-01 00:00:00      -0.25
2016-09-01 00:00:00
                 SBES1H24 Unnamed: 1
2253  2016-09-01 00:00:00       0.47
                 SBES1K24 Unnamed: 4
2295  2016-09-01 00:00:00       0.51
2015-09-01 00:00:00
                 SBES1H24 Unnamed: 1
2558  2015-09-01 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
2601  2015-09-01 00:00:00          0
2014-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2013-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2012-09-01 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-02 00:00:00
                SBES1H24 Unnamed: 1
427  2022-09-02 00:00:00       0.53
                SBES1K24 Unnamed: 4
469  2022-09-02 00:00:00       0.21
2021-09-02 00:00:00
                SBES1H24 Unnamed: 1
732  2021-09-02 00:00:00       0.66
                SBES1K24 Unnamed: 4
775  2021-09-02 00:00:00       0.74
2020-09-02 00:00:00
                 SBES1H24 Unnamed: 1
1035  2020-09-02 00:00:00       0.11
                 SBES1K24 Unnamed: 4
1079  2020-09-02 00:00:00       0.18
2019-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2018-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-02 00:00:00
                 SBES1H24 Unnamed: 1
2252  2016-09-02 00:00:00       0.56
                 SBES1K24 Unnamed: 4
2294  2016-09-02 00:00:00       0.54
2015-09-02 00:00:00
                 SBES1H24 Unnamed: 1
2557  2015-09-02 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
2600  2015-09-02 00:00:00      -0.03
2014-09-02 00:00:00
                 SBES1H24 Unnamed: 1
2862  2014-09-02 00:00:00      -0.42
                 SBES1K24 Unnamed: 4
2905  2014-09-02 00:00:00      -0.23
2013-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2012-09-02 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-03 00:00:00
                SBES1H24 Unnamed: 1
731  2021-09-03 00:00:00        0.6
                SBES1K24 Unnamed: 4
774  2021-09-03 00:00:00        0.7
2020-09-03 00:00:00
                 SBES1H24 Unnamed: 1
1034  2020-09-03 00:00:00        0.1
                 SBES1K24 Unnamed: 4
1078  2020-09-03 00:00:00       0.14
2019-09-03 00:00:00
                 SBES1H24 Unnamed: 1
1341  2019-09-03 00:00:00      -0.11
                 SBES1K24 Unnamed: 4
1384  2019-09-03 00:00:00      -0.14
2018-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-03 00:00:00
                 SBES1H24 Unnamed: 1
2556  2015-09-03 00:00:00      -0.03
                 SBES1K24 Unnamed: 4
2599  2015-09-03 00:00:00       0.06
2014-09-03 00:00:00
                 SBES1H24 Unnamed: 1
2861  2014-09-03 00:00:00      -0.48
                 SBES1K24 Unnamed: 4
2904  2014-09-03 00:00:00      -0.26
2013-09-03 00:00:00
                 SBES1H24 Unnamed: 1
3166  2013-09-03 00:00:00        0.1
                 SBES1K24 Unnamed: 4
3208  2013-09-03 00:00:00       0.08
2012-09-03 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2020-09-04 00:00:00
                 SBES1H24 Unnamed: 1
1033  2020-09-04 00:00:00       0.09
                 SBES1K24 Unnamed: 4
1077  2020-09-04 00:00:00       0.12
2019-09-04 00:00:00
                 SBES1H24 Unnamed: 1
1340  2019-09-04 00:00:00      -0.14
                 SBES1K24 Unnamed: 4
1383  2019-09-04 00:00:00      -0.17
2018-09-04 00:00:00
                 SBES1H24 Unnamed: 1
1644  2018-09-04 00:00:00      -0.09
                 SBES1K24 Unnamed: 4
1686  2018-09-04 00:00:00      -0.08
2017-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-04 00:00:00
                 SBES1H24 Unnamed: 1
2555  2015-09-04 00:00:00      -0.08
                 SBES1K24 Unnamed: 4
2598  2015-09-04 00:00:00       0.01
2014-09-04 00:00:00
                 SBES1H24 Unnamed: 1
2860  2014-09-04 00:00:00      -0.54
                 SBES1K24 Unnamed: 4
2903  2014-09-04 00:00:00      -0.35
2013-09-04 00:00:00
                 SBES1H24 Unnamed: 1
3165  2013-09-04 00:00:00       0.06
                 SBES1K24 Unnamed: 4
3207  2013-09-04 00:00:00       0.06
2012-09-04 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-05 00:00:00
               SBES1H24 Unnamed: 1
55  2023-09-05 00:00:00       1.57
               SBES1K24 Unnamed: 4
55  2023-09-05 00:00:00       1.45
2022-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2020-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2019-09-05 00:00:00
                 SBES1H24 Unnamed: 1
1339  2019-09-05 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
1382  2019-09-05 00:00:00      -0.17
2018-09-05 00:00:00
                 SBES1H24 Unnamed: 1
1643  2018-09-05 00:00:00      -0.13
                 SBES1K24 Unnamed: 4
1685  2018-09-05 00:00:00      -0.13
2017-09-05 00:00:00
                 SBES1H24 Unnamed: 1
1947  2017-09-05 00:00:00      -0.22
                 SBES1K24 Unnamed: 4
1989  2017-09-05 00:00:00      -0.25
2016-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2014-09-05 00:00:00
                 SBES1H24 Unnamed: 1
2859  2014-09-05 00:00:00      -0.53
                 SBES1K24 Unnamed: 4
2902  2014-09-05 00:00:00      -0.37
2013-09-05 00:00:00
                 SBES1H24 Unnamed: 1
3164  2013-09-05 00:00:00       0.07
                 SBES1K24 Unnamed: 4
3206  2013-09-05 00:00:00       0.07
2012-09-05 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-06 00:00:00
               SBES1H24 Unnamed: 1
54  2023-09-06 00:00:00       1.45
               SBES1K24 Unnamed: 4
54  2023-09-06 00:00:00       1.37
2022-09-06 00:00:00
                SBES1H24 Unnamed: 1
426  2022-09-06 00:00:00       0.55
                SBES1K24 Unnamed: 4
468  2022-09-06 00:00:00       0.24
2021-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2020-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2019-09-06 00:00:00
                 SBES1H24 Unnamed: 1
1338  2019-09-06 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
1381  2019-09-06 00:00:00      -0.18
2018-09-06 00:00:00
                 SBES1H24 Unnamed: 1
1642  2018-09-06 00:00:00      -0.16
                 SBES1K24 Unnamed: 4
1684  2018-09-06 00:00:00      -0.13
2017-09-06 00:00:00
                 SBES1H24 Unnamed: 1
1946  2017-09-06 00:00:00      -0.17
                 SBES1K24 Unnamed: 4
1988  2017-09-06 00:00:00      -0.24
2016-09-06 00:00:00
                 SBES1H24 Unnamed: 1
2251  2016-09-06 00:00:00       0.51
                 SBES1K24 Unnamed: 4
2293  2016-09-06 00:00:00       0.49
2015-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2014-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2013-09-06 00:00:00
                 SBES1H24 Unnamed: 1
3163  2013-09-06 00:00:00       0.07
                 SBES1K24 Unnamed: 4
3205  2013-09-06 00:00:00       0.08
2012-09-06 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-07 00:00:00
               SBES1H24 Unnamed: 1
53  2023-09-07 00:00:00       1.56
               SBES1K24 Unnamed: 4
53  2023-09-07 00:00:00       1.43
2022-09-07 00:00:00
                SBES1H24 Unnamed: 1
425  2022-09-07 00:00:00       0.54
                SBES1K24 Unnamed: 4
467  2022-09-07 00:00:00       0.22
2021-09-07 00:00:00
                SBES1H24 Unnamed: 1
730  2021-09-07 00:00:00       0.57
                SBES1K24 Unnamed: 4
773  2021-09-07 00:00:00       0.67
2020-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2019-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2018-09-07 00:00:00
                 SBES1H24 Unnamed: 1
1641  2018-09-07 00:00:00      -0.15
                 SBES1K24 Unnamed: 4
1683  2018-09-07 00:00:00      -0.09
2017-09-07 00:00:00
                 SBES1H24 Unnamed: 1
1945  2017-09-07 00:00:00      -0.17
                 SBES1K24 Unnamed: 4
1987  2017-09-07 00:00:00      -0.26
2016-09-07 00:00:00
                 SBES1H24 Unnamed: 1
2250  2016-09-07 00:00:00       0.46
                 SBES1K24 Unnamed: 4
2292  2016-09-07 00:00:00       0.49
2015-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2014-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2013-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2012-09-07 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-08 00:00:00
               SBES1H24 Unnamed: 1
52  2023-09-08 00:00:00       1.48
               SBES1K24 Unnamed: 4
52  2023-09-08 00:00:00       1.35
2022-09-08 00:00:00
                SBES1H24 Unnamed: 1
424  2022-09-08 00:00:00       0.47
                SBES1K24 Unnamed: 4
466  2022-09-08 00:00:00       0.18
2021-09-08 00:00:00
                SBES1H24 Unnamed: 1
729  2021-09-08 00:00:00       0.53
                SBES1K24 Unnamed: 4
772  2021-09-08 00:00:00       0.63
2020-09-08 00:00:00
                 SBES1H24 Unnamed: 1
1032  2020-09-08 00:00:00       0.15
                 SBES1K24 Unnamed: 4
1076  2020-09-08 00:00:00       0.16
2019-09-08 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2018-09-08 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-08 00:00:00
                 SBES1H24 Unnamed: 1
1944  2017-09-08 00:00:00      -0.15
                 SBES1K24 Unnamed: 4
1986  2017-09-08 00:00:00      -0.24
2016-09-08 00:00:00
                 SBES1H24 Unnamed: 1
2249  2016-09-08 00:00:00       0.44
                 SBES1K24 Unnamed: 4
2291  2016-09-08 00:00:00        0.5
2015-09-08 00:00:00
                 SBES1H24 Unnamed: 1
2554  2015-09-08 00:00:00      -0.13
                 SBES1K24 Unnamed: 4
2597  2015-09-08 00:00:00      -0.04
2014-09-08 00:00:00
                 SBES1H24 Unnamed: 1
2858  2014-09-08 00:00:00      -0.47
                 SBES1K24 Unnamed: 4
2901  2014-09-08 00:00:00      -0.35
2013-09-08 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2012-09-08 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-09 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-09 00:00:00
                SBES1H24 Unnamed: 1
423  2022-09-09 00:00:00       0.47
                SBES1K24 Unnamed: 4
465  2022-09-09 00:00:00       0.17
2021-09-09 00:00:00
                SBES1H24 Unnamed: 1
728  2021-09-09 00:00:00        0.5
                SBES1K24 Unnamed: 4
771  2021-09-09 00:00:00       0.56
2020-09-09 00:00:00
                 SBES1H24 Unnamed: 1
1031  2020-09-09 00:00:00       0.17
                 SBES1K24 Unnamed: 4
1075  2020-09-09 00:00:00       0.15
2019-09-09 00:00:00
                 SBES1H24 Unnamed: 1
1337  2019-09-09 00:00:00      -0.12
                 SBES1K24 Unnamed: 4
1380  2019-09-09 00:00:00      -0.17
2018-09-09 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2017-09-09 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-09 00:00:00
                 SBES1H24 Unnamed: 1
2248  2016-09-09 00:00:00        0.4
                 SBES1K24 Unnamed: 4
2290  2016-09-09 00:00:00       0.49
2015-09-09 00:00:00
                 SBES1H24 Unnamed: 1
2553  2015-09-09 00:00:00       -0.1
                 SBES1K24 Unnamed: 4
2596  2015-09-09 00:00:00          0
2014-09-09 00:00:00
                 SBES1H24 Unnamed: 1
2857  2014-09-09 00:00:00      -0.49
                 SBES1K24 Unnamed: 4
2900  2014-09-09 00:00:00      -0.36
2013-09-09 00:00:00
                 SBES1H24 Unnamed: 1
3162  2013-09-09 00:00:00        0.1
                 SBES1K24 Unnamed: 4
3204  2013-09-09 00:00:00       0.09
2012-09-09 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2022-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-10 00:00:00
                SBES1H24 Unnamed: 1
727  2021-09-10 00:00:00       0.45
                SBES1K24 Unnamed: 4
770  2021-09-10 00:00:00       0.53
2020-09-10 00:00:00
                 SBES1H24 Unnamed: 1
1030  2020-09-10 00:00:00       0.14
                 SBES1K24 Unnamed: 4
1074  2020-09-10 00:00:00       0.12
2019-09-10 00:00:00
                 SBES1H24 Unnamed: 1
1336  2019-09-10 00:00:00      -0.13
                 SBES1K24 Unnamed: 4
1379  2019-09-10 00:00:00      -0.17
2018-09-10 00:00:00
                 SBES1H24 Unnamed: 1
1640  2018-09-10 00:00:00      -0.15
                 SBES1K24 Unnamed: 4
1682  2018-09-10 00:00:00      -0.09
2017-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2016-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-10 00:00:00
                 SBES1H24 Unnamed: 1
2552  2015-09-10 00:00:00      -0.04
                 SBES1K24 Unnamed: 4
2595  2015-09-10 00:00:00       0.04
2014-09-10 00:00:00
                 SBES1H24 Unnamed: 1
2856  2014-09-10 00:00:00      -0.48
                 SBES1K24 Unnamed: 4
2899  2014-09-10 00:00:00      -0.41
2013-09-10 00:00:00
                 SBES1H24 Unnamed: 1
3161  2013-09-10 00:00:00        0.1
                 SBES1K24 Unnamed: 4
3203  2013-09-10 00:00:00       0.08
2012-09-10 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2023-09-11 00:00:00
               SBES1H24 Unnamed: 1
51  2023-09-11 00:00:00       1.43
               SBES1K24 Unnamed: 4
51  2023-09-11 00:00:00       1.22
2022-09-11 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2021-09-11 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2020-09-11 00:00:00
                 SBES1H24 Unnamed: 1
1029  2020-09-11 00:00:00       0.13
                 SBES1K24 Unnamed: 4
1073  2020-09-11 00:00:00       0.12
2019-09-11 00:00:00
                 SBES1H24 Unnamed: 1
1335  2019-09-11 00:00:00      -0.15
                 SBES1K24 Unnamed: 4
1378  2019-09-11 00:00:00       -0.2
2018-09-11 00:00:00
                 SBES1H24 Unnamed: 1
1639  2018-09-11 00:00:00      -0.18
                 SBES1K24 Unnamed: 4
1681  2018-09-11 00:00:00      -0.13
2017-09-11 00:00:00
                 SBES1H24 Unnamed: 1
1943  2017-09-11 00:00:00       -0.1
                 SBES1K24 Unnamed: 4
1985  2017-09-11 00:00:00      -0.18
2016-09-11 00:00:00
Empty DataFrame
Columns: [SBES1H24, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K24, Unnamed: 4]
Index: []
2015-09-11 00:00:00
                 SBES1H24 Unnamed: 1
2551  2015-09-11 00:00:00       0.01
                 SBES1K24 Unnamed: 4
2594  2015-09-11 00:00:00       0.06
2014-09-11 00:00:00
                 SBES1H24 Unnamed: 1
2855  2014-09-11 00:00:00       -0.5
                 SBES1K24 Unnamed: 4
2898  2014-09-11 00:00:00       -0.4
2013-09-11 00:00:00

In [45]:
df_low = pd.DataFrame(low_df)

In [46]:
df_low

   month_day  cena_flaja_low
0       9-01           -0.12
1       9-02           -0.19
2       9-03           -0.22
3       9-04           -0.19
4       9-05           -0.16
5       9-06           -0.03
6       9-07           -0.10
7       9-08           -0.12
8       9-09           -0.13
9       9-10           -0.08
10      9-11           -0.10
11      9-12           -0.10
12      9-13           -0.09
13      9-14           -0.09
14      9-15           -0.14
15      9-16           -0.10
16      9-17           -0.09
17      9-18           -0.10
18      9-19           -0.05
19      9-20           -0.12
20      9-21           -0.14
21      9-22           -0.14
22      9-23           -0.12
23      9-24           -0.10
24      9-25           -0.08
25      9-26           -0.09
26      9-27           -0.12
27      9-28           -0.12
28      9-29           -0.13
29      9-30           -0.10

In [47]:
merged_df = pd.merge(df_low, df_haj, on='month_day')
merged_df = pd.merge(merged_df, df_srednia, on='month_day')

merged_df = pd.merge(merged_df, df_mediana, on='month_day')

In [48]:
merged_df

,month_day,cena_flaja_low,cena_flaja_haj,cena_flaja_srednia,cena_flaja_mediana
0,9-01,-0.12,0.32,3.142857e-02,-4.000000e-02
1,9-02,-0.19,0.32,-1.500000e-02,-7.500000e-02
2,9-03,-0.22,0.03,-6.666667e-02,-6.500000e-02
3,9-04,-0.19,0.03,-4.833333e-02,-2.000000e-02
4,9-05,-0.16,0.12,6.666667e-03,1.500000e-02
5,9-06,-0.03,0.31,7.142857e-02,6.000000e-02
6,9-07,-0.10,0.32,5.833333e-02,3.000000e-02
7,9-08,-0.12,0.29,1.625000e-02,-3.500000e-02
8,9-09,-0.13,0.30,0.000000e+00,-2.500000e-02
9,9-10,-0.08,0.04,-3.000000e-02,-6.000000e-02
10,9-11,-0.10,0.21,2.250000e-02,2.000000e-02
11,9-12,-0.10,0.26,4.750000e-02,4.000000e-02
12,9-13,-0.09,0.20,4.250000e-02,4.000000e-02
13,9-14,-0.09,0.19,1.875000e-02,-5.000000e-03
14,9-15,-0.14,0.17,1.000000e-02,-1.000000e-02
15,9-16,-0.10,0.19,1.125000e-02,5.000000e-03
16,9-17,-0.09,0.04,-3.142857e-02,-3.000000e-02
17,9-18,-0.10,0.13,6.250000e-03,1.000000e-02
18,9-19,-0.05,0.18,4.875000e-02,3.000000e-02
19,9-20,-0.12,0.17,3.000000e-02,2.000000e-02
20,9-21,-0.14,0.15,1.500000e-02,-2.602085e-18
21,9-22,-0.14,0.22,1.375000e-02,-5.000000e-03
22,9-23,-0.12,0.14,-1.250000e-02,-1.000000e-02
23,9-24,-0.10,0.04,-1.285714e-02,1.000000e-02
24,9-25,-0.08,0.23,4.000000e-02,3.000000e-02
25,9-26,-0.09,0.29,5.500000e-02,2.500000e-02
26,9-27,-0.12,0.30,4.500000e-02,4.000000e-02
27,9-28,-0.12,0.27,3.750000e-02,5.000000e-03
28,9-29,-0.13,0.22,2.500000e-02,1.387779e-17
29,9-30,-0.10,0.15,-1.734723e-17,-5.000000e-03

In [49]:
nowy_wiersz_srednia = {
    'month_day': 'Åšrednia',
    'cena_flaja_srednia': merged_df['cena_flaja_srednia'].mean(),
    'cena_flaja_mediana': merged_df['cena_flaja_mediana'].mean()
}

# Dodanie nowego wiersza do DataFrame
merged_df = merged_df.append(nowy_wiersz_srednia, ignore_index=True)

<ipython-input-49-ea03d59f83ae>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_df = merged_df.append(nowy_wiersz_srednia, ignore_index=True)

In [50]:
merged_df.round(2)

,month_day,cena_flaja_low,cena_flaja_haj,cena_flaja_srednia,cena_flaja_mediana
0,9-01,-0.12,0.32,0.03,-0.04
1,9-02,-0.19,0.32,-0.01,-0.07
2,9-03,-0.22,0.03,-0.07,-0.06
3,9-04,-0.19,0.03,-0.05,-0.02
4,9-05,-0.16,0.12,0.01,0.02
5,9-06,-0.03,0.31,0.07,0.06
6,9-07,-0.10,0.32,0.06,0.03
7,9-08,-0.12,0.29,0.02,-0.04
8,9-09,-0.13,0.30,0.00,-0.03
9,9-10,-0.08,0.04,-0.03,-0.06
10,9-11,-0.10,0.21,0.02,0.02
11,9-12,-0.10,0.26,0.05,0.04
12,9-13,-0.09,0.20,0.04,0.04
13,9-14,-0.09,0.19,0.02,-0.01
14,9-15,-0.14,0.17,0.01,-0.01
15,9-16,-0.10,0.19,0.01,0.00
16,9-17,-0.09,0.04,-0.03,-0.03
17,9-18,-0.10,0.13,0.01,0.01
18,9-19,-0.05,0.18,0.05,0.03
19,9-20,-0.12,0.17,0.03,0.02
20,9-21,-0.14,0.15,0.02,-0.00
21,9-22,-0.14,0.22,0.01,-0.00
22,9-23,-0.12,0.14,-0.01,-0.01
23,9-24,-0.10,0.04,-0.01,0.01
24,9-25,-0.08,0.23,0.04,0.03
25,9-26,-0.09,0.29,0.06,0.02
26,9-27,-0.12,0.30,0.04,0.04
27,9-28,-0.12,0.27,0.04,0.00
28,9-29,-0.13,0.22,0.02,0.00
29,9-30,-0.10,0.15,-0.00,-0.00
30,Åšrednia,NaN,NaN,0.01,-0.00