<a href="https://colab.research.google.com/github/tomektom10/dataScienceBootCamp/blob/main/PROJEKT_CUKIER_NAJNOWSZE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_excel("Cukry_wszystkie.xlsx")
df
df.columns
import numpy as np

In [2]:
df1 = df[["SBES1H23", "Unnamed: 1"]].iloc[1:]
df1

                 SBES1H23 Unnamed: 1
1     2023-02-28 00:00:00       2.01
2     2023-02-27 00:00:00       1.82
3     2023-02-24 00:00:00       1.62
4     2023-02-23 00:00:00       1.27
5     2023-02-22 00:00:00       1.39
...                   ...        ...
3033  2012-12-26 00:00:00        0.1
3034  2012-12-24 00:00:00       0.12
3035  2012-12-21 00:00:00        0.1
3036  2012-12-20 00:00:00       0.11
3037  2012-12-19 00:00:00       0.11

[3037 rows x 2 columns]

In [3]:
df2 = df[["SBES1K23", "Unnamed: 4"]].iloc[1:]
df2
import datetime

In [40]:
day_month = "10-16"
wynik_dict = {"Date":[], "cena_flaja1":[] }
for year in [2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012]:
  specyfic_date = str(year) + "-" + day_month
  specyfic_date = datetime.datetime.strptime(specyfic_date, '%Y-%m-%d')
  print(specyfic_date)
  df_row1 = df1[df1["SBES1H23"] == specyfic_date]
  print(df_row1)

  df_row2 = df2[df2["SBES1K23"] == specyfic_date]
  print(df_row2)
  cena_flaja = []
  if len(df_row1) > 0 and len(df_row2) >0:

    value = df_row1['Unnamed: 1'].values[0]
    cena_flaja = value - df_row2["Unnamed: 4"].values[0]


    wynik_dict["Date"].append(specyfic_date)
    wynik_dict["cena_flaja1"].append(cena_flaja)


df_wynik = pd.DataFrame(wynik_dict)

2023-10-16 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-10-16 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-10-16 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-10-16 00:00:00
                SBES1H23 Unnamed: 1
699  2020-10-16 00:00:00       0.63
                SBES1K23 Unnamed: 4
743  2020-10-16 00:00:00       0.53
2019-10-16 00:00:00
                 SBES1H23 Unnamed: 1
1005  2019-10-16 00:00:00       -0.1
                 SBES1K23 Unnamed: 4
1048  2019-10-16 00:00:00      -0.13
2018-10-16 00:00:00
                 SBES1H23 Unnamed: 1
1309  2018-10-16 00:00:00      -0.14
                 SBES1K23 Unnamed: 4
1351  2018-10-16 00:00:00      -0.07
2017-10-16 00:00:00
                 SBES1H23 Unnamed: 1
1613  2017-10-16 00:00:00      -0.11
                 SBES1K23 Unnamed: 4
1655  2017-10-16 00:00:00      -0.15
2016-10-16 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2015-10-16 00:00:00
                 SBES1H23 Unnamed: 1
2221  2015-10-16 00:00:00       0.22
                 SBES1K23 Unnamed: 4
2264  2015-10-16 00:00:00        0.2
2014-10-16 00:00:00
                 SBES1H23 Unnamed: 1
2525  2014-10-16 00:00:00      -0.24
                 SBES1K23 Unnamed: 4
2568  2014-10-16 00:00:00      -0.26
2013-10-16 00:00:00
                 SBES1H23 Unnamed: 1
2830  2013-10-16 00:00:00       0.14
                 SBES1K23 Unnamed: 4
2872  2013-10-16 00:00:00       0.15
2012-10-16 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []

In [41]:
df_wynik

        Date  cena_flaja1
0 2020-10-16         0.10
1 2019-10-16         0.03
2 2018-10-16        -0.07
3 2017-10-16         0.04
4 2015-10-16         0.02
5 2014-10-16         0.02
6 2013-10-16        -0.01

In [42]:
def oblicz_ceny_flaja(df1, df2, kod1, kod2, cena1, cena2, day_month):

  wynik_dict = {"Date":[], "cena_flaja1":[] }
  for year in [2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012]:
    specyfic_date = str(year) + "-" + day_month
    specyfic_date = datetime.datetime.strptime(specyfic_date, '%Y-%m-%d')
    print(specyfic_date)
    df_row1 = df1[df1[kod1] == specyfic_date]
    print(df_row1)

    df_row2 = df2[df2[kod2] == specyfic_date]
    print(df_row2)
    cena_flaja = []
    if len(df_row1) > 0 and len(df_row2) >0:

      value = df_row1[cena1].values[0]
      cena_flaja = value - df_row2[cena2].values[0]


      wynik_dict["Date"].append(specyfic_date)
      wynik_dict["cena_flaja1"].append(cena_flaja)


      df_wynik = pd.DataFrame(wynik_dict)
  return df_wynik

In [43]:
oblicz_ceny_flaja(df1, df2, "SBES1H23" , "SBES1K23" , "Unnamed: 1", "Unnamed: 4", "10-16" )

2023-10-16 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-10-16 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-10-16 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-10-16 00:00:00
                SBES1H23 Unnamed: 1
699  2020-10-16 00:00:00       0.63
                SBES1K23 Unnamed: 4
743  2020-10-16 00:00:00       0.53
2019-10-16 00:00:00
                 SBES1H23 Unnamed: 1
1005  2019-10-16 00:00:00       -0.1
                 SBES1K23 Unnamed: 4
1048  2019-10-16 00:00:00      -0.13
2018-10-16 00:00:00
                 SBES1H23 Unnamed: 1
1309  2018-10-16 00:00:00      -0.14
                 SBES1K23 Unnamed: 4
1351  2018-10-16 00:00:00      -0.07
2017-10-16 00:00:00
                 SBES1H23 Unnamed: 1
1613  2017-10-16 00:00:00      -0.11
                 SBES1K23 Unnamed: 4
1655  2017-10-16 00:00:00      -0.15
2016-10-16 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2015-10-16 00:00:00
                 SBES1H23 Unnamed: 1
2221  2015-10-16 00:00:00       0.22
                 SBES1K23 Unnamed: 4
2264  2015-10-16 00:00:00        0.2
2014-10-16 00:00:00
                 SBES1H23 Unnamed: 1
2525  2014-10-16 00:00:00      -0.24
                 SBES1K23 Unnamed: 4
2568  2014-10-16 00:00:00      -0.26
2013-10-16 00:00:00
                 SBES1H23 Unnamed: 1
2830  2013-10-16 00:00:00       0.14
                 SBES1K23 Unnamed: 4
2872  2013-10-16 00:00:00       0.15
2012-10-16 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []

        Date  cena_flaja1
0 2020-10-16         0.10
1 2019-10-16         0.03
2 2018-10-16        -0.07
3 2017-10-16         0.04
4 2015-10-16         0.02
5 2014-10-16         0.02
6 2013-10-16        -0.01

In [44]:
import calendar
month = "02"

In [45]:
def create_days_for_month(month, year = 2023):
  numdays = calendar.monthrange(year, int(month))[-1]
  print(calendar.monthrange(year, int(month)))
  days_list = [f'{month}-{day:02d}' for day in range(1, numdays + 1)]
  return days_list

In [47]:
create_days_for_month("11")

(2, 30)

['11-01',
 '11-02',
 '11-03',
 '11-04',
 '11-05',
 '11-06',
 '11-07',
 '11-08',
 '11-09',
 '11-10',
 '11-11',
 '11-12',
 '11-13',
 '11-14',
 '11-15',
 '11-16',
 '11-17',
 '11-18',
 '11-19',
 '11-20',
 '11-21',
 '11-22',
 '11-23',
 '11-24',
 '11-25',
 '11-26',
 '11-27',
 '11-28',
 '11-29',
 '11-30']

In [48]:
days_list = create_days_for_month("11")

(2, 30)

In [49]:
srednia_df = []
for month_day in days_list:
 df= oblicz_ceny_flaja(df1, df2, "SBES1H23" , "SBES1K23" , "Unnamed: 1", "Unnamed: 4", month_day )
 srednia_df.append({"month_day": month_day, "cena_flaja_srednia": df["cena_flaja1"].mean()})

2023-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-01 00:00:00
               SBES1H23 Unnamed: 1
81  2022-11-01 00:00:00       1.04
                SBES1K23 Unnamed: 4
123  2022-11-01 00:00:00       0.58
2021-11-01 00:00:00
                SBES1H23 Unnamed: 1
386  2021-11-01 00:00:00       0.28
                SBES1K23 Unnamed: 4
429  2021-11-01 00:00:00       0.31
2020-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2019-11-01 00:00:00
                SBES1H23 Unnamed: 1
993  2019-11-01 00:00:00      -0.13
                 SBES1K23 Unnamed: 4
1036  2019-11-01 00:00:00      -0.13
2018-11-01 00:00:00
                 SBES1H23 Unnamed: 1
1297  2018-11-01 00:00:00      -0.09
                 SBES1K23 Unnamed: 4
1339  2018-11-01 00:00:00      -0.05
2017-11-01 00:00:00
                 SBES1H23 Unnamed: 1
1601  2017-11-01 00:00:00      -0.08
                 SBES1K23 Unnamed: 4
1643  2017-11-01 00:00:00      -0.09
2016-11-01 00:00:00
                 SBES1H23 Unnamed: 1
1906  2016-11-01 00:00:00        0.4
                 SBES1K23 Unnamed: 4
1948  2016-11-01 00:00:00       0.53
2015-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2014-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2013-11-01 00:00:00
                 SBES1H23 Unnamed: 1
2818  2013-11-01 00:00:00       0.15
                 SBES1K23 Unnamed: 4
2860  2013-11-01 00:00:00       0.17
2012-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-02 00:00:00
               SBES1H23 Unnamed: 1
80  2022-11-02 00:00:00          1
                SBES1K23 Unnamed: 4
122  2022-11-02 00:00:00       0.54
2021-11-02 00:00:00
                SBES1H23 Unnamed: 1
385  2021-11-02 00:00:00       0.25
                SBES1K23 Unnamed: 4
428  2021-11-02 00:00:00       0.27
2020-11-02 00:00:00
                SBES1H23 Unnamed: 1
688  2020-11-02 00:00:00       1.09
                SBES1K23 Unnamed: 4
732  2020-11-02 00:00:00       0.72
2019-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-11-02 00:00:00
                 SBES1H23 Unnamed: 1
1296  2018-11-02 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1338  2018-11-02 00:00:00      -0.07
2017-11-02 00:00:00
                 SBES1H23 Unnamed: 1
1600  2017-11-02 00:00:00      -0.13
                 SBES1K23 Unnamed: 4
1642  2017-11-02 00:00:00      -0.16
2016-11-02 00:00:00
                 SBES1H23 Unnamed: 1
1905  2016-11-02 00:00:00       0.56
                 SBES1K23 Unnamed: 4
1947  2016-11-02 00:00:00       0.64
2015-11-02 00:00:00
                 SBES1H23 Unnamed: 1
2210  2015-11-02 00:00:00        0.4
                 SBES1K23 Unnamed: 4
2253  2015-11-02 00:00:00       0.29
2014-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2013-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2012-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-03 00:00:00
               SBES1H23 Unnamed: 1
79  2022-11-03 00:00:00          1
                SBES1K23 Unnamed: 4
121  2022-11-03 00:00:00       0.55
2021-11-03 00:00:00
                SBES1H23 Unnamed: 1
384  2021-11-03 00:00:00       0.22
                SBES1K23 Unnamed: 4
427  2021-11-03 00:00:00       0.26
2020-11-03 00:00:00
                SBES1H23 Unnamed: 1
687  2020-11-03 00:00:00       1.03
                SBES1K23 Unnamed: 4
731  2020-11-03 00:00:00       0.68
2019-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-11-03 00:00:00
                 SBES1H23 Unnamed: 1
1599  2017-11-03 00:00:00      -0.11
                 SBES1K23 Unnamed: 4
1641  2017-11-03 00:00:00      -0.13
2016-11-03 00:00:00
                 SBES1H23 Unnamed: 1
1904  2016-11-03 00:00:00       0.49
                 SBES1K23 Unnamed: 4
1946  2016-11-03 00:00:00       0.59
2015-11-03 00:00:00
                 SBES1H23 Unnamed: 1
2209  2015-11-03 00:00:00       0.46
                 SBES1K23 Unnamed: 4
2252  2015-11-03 00:00:00       0.38
2014-11-03 00:00:00
                 SBES1H23 Unnamed: 1
2513  2014-11-03 00:00:00      -0.31
                 SBES1K23 Unnamed: 4
2556  2014-11-03 00:00:00      -0.27
2013-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2012-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-04 00:00:00
               SBES1H23 Unnamed: 1
78  2022-11-04 00:00:00       0.96
                SBES1K23 Unnamed: 4
120  2022-11-04 00:00:00       0.53
2021-11-04 00:00:00
                SBES1H23 Unnamed: 1
383  2021-11-04 00:00:00       0.23
                SBES1K23 Unnamed: 4
426  2021-11-04 00:00:00       0.28
2020-11-04 00:00:00
                SBES1H23 Unnamed: 1
686  2020-11-04 00:00:00       0.96
                SBES1K23 Unnamed: 4
730  2020-11-04 00:00:00       0.67
2019-11-04 00:00:00
                SBES1H23 Unnamed: 1
992  2019-11-04 00:00:00      -0.13
                 SBES1K23 Unnamed: 4
1035  2019-11-04 00:00:00      -0.12
2018-11-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-11-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-11-04 00:00:00
                 SBES1H23 Unnamed: 1
1903  2016-11-04 00:00:00       0.55
                 SBES1K23 Unnamed: 4
1945  2016-11-04 00:00:00       0.64
2015-11-04 00:00:00
                 SBES1H23 Unnamed: 1
2208  2015-11-04 00:00:00       0.34
                 SBES1K23 Unnamed: 4
2251  2015-11-04 00:00:00       0.25
2014-11-04 00:00:00
                 SBES1H23 Unnamed: 1
2512  2014-11-04 00:00:00      -0.38
                 SBES1K23 Unnamed: 4
2555  2014-11-04 00:00:00      -0.31
2013-11-04 00:00:00
                 SBES1H23 Unnamed: 1
2817  2013-11-04 00:00:00       0.17
                 SBES1K23 Unnamed: 4
2859  2013-11-04 00:00:00       0.18
2012-11-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-11-05 00:00:00
                SBES1H23 Unnamed: 1
382  2021-11-05 00:00:00        0.3
                SBES1K23 Unnamed: 4
425  2021-11-05 00:00:00       0.35
2020-11-05 00:00:00
                SBES1H23 Unnamed: 1
685  2020-11-05 00:00:00       0.82
                SBES1K23 Unnamed: 4
729  2020-11-05 00:00:00       0.64
2019-11-05 00:00:00
                SBES1H23 Unnamed: 1
991  2019-11-05 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1034  2019-11-05 00:00:00      -0.11
2018-11-05 00:00:00
                 SBES1H23 Unnamed: 1
1295  2018-11-05 00:00:00      -0.14
                 SBES1K23 Unnamed: 4
1337  2018-11-05 00:00:00      -0.08
2017-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2015-11-05 00:00:00
                 SBES1H23 Unnamed: 1
2207  2015-11-05 00:00:00       0.37
                 SBES1K23 Unnamed: 4
2250  2015-11-05 00:00:00       0.26
2014-11-05 00:00:00
                 SBES1H23 Unnamed: 1
2511  2014-11-05 00:00:00      -0.42
                 SBES1K23 Unnamed: 4
2554  2014-11-05 00:00:00      -0.34
2013-11-05 00:00:00
                 SBES1H23 Unnamed: 1
2816  2013-11-05 00:00:00       0.16
                 SBES1K23 Unnamed: 4
2858  2013-11-05 00:00:00       0.18
2012-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-11-06 00:00:00
                SBES1H23 Unnamed: 1
684  2020-11-06 00:00:00       0.76
                SBES1K23 Unnamed: 4
728  2020-11-06 00:00:00       0.71
2019-11-06 00:00:00
                SBES1H23 Unnamed: 1
990  2019-11-06 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1033  2019-11-06 00:00:00      -0.09
2018-11-06 00:00:00
                 SBES1H23 Unnamed: 1
1294  2018-11-06 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1336  2018-11-06 00:00:00       -0.1
2017-11-06 00:00:00
                 SBES1H23 Unnamed: 1
1598  2017-11-06 00:00:00      -0.08
                 SBES1K23 Unnamed: 4
1640  2017-11-06 00:00:00      -0.08
2016-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2015-11-06 00:00:00
                 SBES1H23 Unnamed: 1
2206  2015-11-06 00:00:00       0.33
                 SBES1K23 Unnamed: 4
2249  2015-11-06 00:00:00       0.24
2014-11-06 00:00:00
                 SBES1H23 Unnamed: 1
2510  2014-11-06 00:00:00      -0.42
                 SBES1K23 Unnamed: 4
2553  2014-11-06 00:00:00      -0.33
2013-11-06 00:00:00
                 SBES1H23 Unnamed: 1
2815  2013-11-06 00:00:00       0.12
                 SBES1K23 Unnamed: 4
2857  2013-11-06 00:00:00       0.15
2012-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-07 00:00:00
               SBES1H23 Unnamed: 1
77  2022-11-07 00:00:00       0.95
                SBES1K23 Unnamed: 4
119  2022-11-07 00:00:00       0.58
2021-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2019-11-07 00:00:00
                SBES1H23 Unnamed: 1
989  2019-11-07 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1032  2019-11-07 00:00:00      -0.11
2018-11-07 00:00:00
                 SBES1H23 Unnamed: 1
1293  2018-11-07 00:00:00      -0.09
                 SBES1K23 Unnamed: 4
1335  2018-11-07 00:00:00      -0.11
2017-11-07 00:00:00
                 SBES1H23 Unnamed: 1
1597  2017-11-07 00:00:00      -0.05
                 SBES1K23 Unnamed: 4
1639  2017-11-07 00:00:00      -0.07
2016-11-07 00:00:00
                 SBES1H23 Unnamed: 1
1902  2016-11-07 00:00:00       0.63
                 SBES1K23 Unnamed: 4
1944  2016-11-07 00:00:00       0.71
2015-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2014-11-07 00:00:00
                 SBES1H23 Unnamed: 1
2509  2014-11-07 00:00:00      -0.36
                 SBES1K23 Unnamed: 4
2552  2014-11-07 00:00:00      -0.26
2013-11-07 00:00:00
                 SBES1H23 Unnamed: 1
2814  2013-11-07 00:00:00       0.14
                 SBES1K23 Unnamed: 4
2856  2013-11-07 00:00:00       0.14
2012-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-08 00:00:00
               SBES1H23 Unnamed: 1
76  2022-11-08 00:00:00       0.95
                SBES1K23 Unnamed: 4
118  2022-11-08 00:00:00       0.58
2021-11-08 00:00:00
                SBES1H23 Unnamed: 1
381  2021-11-08 00:00:00       0.28
                SBES1K23 Unnamed: 4
424  2021-11-08 00:00:00       0.35
2020-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2019-11-08 00:00:00
                SBES1H23 Unnamed: 1
988  2019-11-08 00:00:00      -0.09
                 SBES1K23 Unnamed: 4
1031  2019-11-08 00:00:00       -0.1
2018-11-08 00:00:00
                 SBES1H23 Unnamed: 1
1292  2018-11-08 00:00:00      -0.14
                 SBES1K23 Unnamed: 4
1334  2018-11-08 00:00:00      -0.14
2017-11-08 00:00:00
                 SBES1H23 Unnamed: 1
1596  2017-11-08 00:00:00      -0.07
                 SBES1K23 Unnamed: 4
1638  2017-11-08 00:00:00      -0.05
2016-11-08 00:00:00
                 SBES1H23 Unnamed: 1
1901  2016-11-08 00:00:00       0.61
                 SBES1K23 Unnamed: 4
1943  2016-11-08 00:00:00       0.73
2015-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2014-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2013-11-08 00:00:00
                 SBES1H23 Unnamed: 1
2813  2013-11-08 00:00:00       0.13
                 SBES1K23 Unnamed: 4
2855  2013-11-08 00:00:00       0.16
2012-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-09 00:00:00
               SBES1H23 Unnamed: 1
75  2022-11-09 00:00:00       0.98
                SBES1K23 Unnamed: 4
117  2022-11-09 00:00:00       0.65
2021-11-09 00:00:00
                SBES1H23 Unnamed: 1
380  2021-11-09 00:00:00       0.28
                SBES1K23 Unnamed: 4
423  2021-11-09 00:00:00       0.35
2020-11-09 00:00:00
                SBES1H23 Unnamed: 1
683  2020-11-09 00:00:00       0.75
                SBES1K23 Unnamed: 4
727  2020-11-09 00:00:00       0.71
2019-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-11-09 00:00:00
                 SBES1H23 Unnamed: 1
1291  2018-11-09 00:00:00      -0.14
                 SBES1K23 Unnamed: 4
1333  2018-11-09 00:00:00      -0.15
2017-11-09 00:00:00
                 SBES1H23 Unnamed: 1
1595  2017-11-09 00:00:00      -0.04
                 SBES1K23 Unnamed: 4
1637  2017-11-09 00:00:00      -0.05
2016-11-09 00:00:00
                 SBES1H23 Unnamed: 1
1900  2016-11-09 00:00:00       0.56
                 SBES1K23 Unnamed: 4
1942  2016-11-09 00:00:00        0.7
2015-11-09 00:00:00
                 SBES1H23 Unnamed: 1
2205  2015-11-09 00:00:00       0.31
                 SBES1K23 Unnamed: 4
2248  2015-11-09 00:00:00        0.2
2014-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2013-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2012-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-10 00:00:00
               SBES1H23 Unnamed: 1
74  2022-11-10 00:00:00          1
                SBES1K23 Unnamed: 4
116  2022-11-10 00:00:00       0.71
2021-11-10 00:00:00
                SBES1H23 Unnamed: 1
379  2021-11-10 00:00:00       0.24
                SBES1K23 Unnamed: 4
422  2021-11-10 00:00:00       0.35
2020-11-10 00:00:00
                SBES1H23 Unnamed: 1
682  2020-11-10 00:00:00       0.64
                SBES1K23 Unnamed: 4
726  2020-11-10 00:00:00       0.65
2019-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-11-10 00:00:00
                 SBES1H23 Unnamed: 1
1594  2017-11-10 00:00:00      -0.01
                 SBES1K23 Unnamed: 4
1636  2017-11-10 00:00:00      -0.02
2016-11-10 00:00:00
                 SBES1H23 Unnamed: 1
1899  2016-11-10 00:00:00        0.6
                 SBES1K23 Unnamed: 4
1941  2016-11-10 00:00:00       0.74
2015-11-10 00:00:00
                 SBES1H23 Unnamed: 1
2204  2015-11-10 00:00:00       0.36
                 SBES1K23 Unnamed: 4
2247  2015-11-10 00:00:00       0.25
2014-11-10 00:00:00
                 SBES1H23 Unnamed: 1
2508  2014-11-10 00:00:00      -0.37
                 SBES1K23 Unnamed: 4
2551  2014-11-10 00:00:00      -0.29
2013-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2012-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-11 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-11 00:00:00
               SBES1H23 Unnamed: 1
73  2022-11-11 00:00:00       1.02
                SBES1K23 Unnamed: 4
115  2022-11-11 00:00:00       0.72
2021-11-11 00:00:00
                SBES1H23 Unnamed: 1
378  2021-11-11 00:00:00       0.26
                SBES1K23 Unnamed: 4
421  2021-11-11 00:00:00       0.41
2020-11-11 00:00:00
                SBES1H23 Unnamed: 1
681  2020-11-11 00:00:00       0.69
                SBES1K23 Unnamed: 4
725  2020-11-11 00:00:00       0.62
2019-11-11 00:00:00
                SBES1H23 Unnamed: 1
987  2019-11-11 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1030  2019-11-11 00:00:00      -0.11
2018-11-11 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-11-11 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-11-11 00:00:00
                 SBES1H23 Unnamed: 1
1898  2016-11-11 00:00:00       0.66
                 SBES1K23 Unnamed: 4
1940  2016-11-11 00:00:00       0.83
2015-11-11 00:00:00
                 SBES1H23 Unnamed: 1
2203  2015-11-11 00:00:00       0.35
                 SBES1K23 Unnamed: 4
2246  2015-11-11 00:00:00       0.27
2014-11-11 00:00:00
                 SBES1H23 Unnamed: 1
2507  2014-11-11 00:00:00      -0.26

In [50]:
srednia_df

[{'month_day': '11-01', 'cena_flaja_srednia': 0.03571428571428573},
 {'month_day': '11-02', 'cena_flaja_srednia': 0.11714285714285715},
 {'month_day': '11-03', 'cena_flaja_srednia': 0.10285714285714286},
 {'month_day': '11-04', 'cena_flaja_srednia': 0.07249999999999998},
 {'month_day': '11-05', 'cena_flaja_srednia': 0.009999999999999997},
 {'month_day': '11-06', 'cena_flaja_srednia': -0.0042857142857142694},
 {'month_day': '11-07', 'cena_flaja_srednia': 0.03142857142857144},
 {'month_day': '11-08', 'cena_flaja_srednia': 0.020000000000000007},
 {'month_day': '11-09', 'cena_flaja_srednia': 0.04142857142857145},
 {'month_day': '11-10', 'cena_flaja_srednia': 0.01},
 {'month_day': '11-11', 'cena_flaja_srednia': 0.0062500000000000056},
 {'month_day': '11-12', 'cena_flaja_srednia': -0.004285714285714283},
 {'month_day': '11-13', 'cena_flaja_srednia': 0.03285714285714285},
 {'month_day': '11-14', 'cena_flaja_srednia': -0.0042857142857142694},
 {'month_day': '11-15', 'cena_flaja_srednia': -0.012857142857142855},
 {'month_day': '11-16', 'cena_flaja_srednia': 0.07428571428571429},
 {'month_day': '11-17', 'cena_flaja_srednia': 0.04142857142857145},
 {'month_day': '11-18', 'cena_flaja_srednia': 0.04625},
 {'month_day': '11-19', 'cena_flaja_srednia': 0.004285714285714287},
 {'month_day': '11-20', 'cena_flaja_srednia': 0.024285714285714296},
 {'month_day': '11-21', 'cena_flaja_srednia': 0.025714285714285714},
 {'month_day': '11-22', 'cena_flaja_srednia': 0.048333333333333346},
 {'month_day': '11-23', 'cena_flaja_srednia': 0.10833333333333335},
 {'month_day': '11-24', 'cena_flaja_srednia': 0.042},
 {'month_day': '11-25', 'cena_flaja_srednia': 0.07571428571428569},
 {'month_day': '11-26', 'cena_flaja_srednia': -0.036},
 {'month_day': '11-27', 'cena_flaja_srednia': 0.065},
 {'month_day': '11-28', 'cena_flaja_srednia': 0.05},
 {'month_day': '11-29', 'cena_flaja_srednia': 0.0642857142857143},
 {'month_day': '11-30', 'cena_flaja_srednia': 0.1242857142857143}]

In [51]:
df_srednia = pd.DataFrame(srednia_df)

In [53]:
df_srednia

   month_day  cena_flaja_srednia
0      11-01            0.035714
1      11-02            0.117143
2      11-03            0.102857
3      11-04            0.072500
4      11-05            0.010000
5      11-06           -0.004286
6      11-07            0.031429
7      11-08            0.020000
8      11-09            0.041429
9      11-10            0.010000
10     11-11            0.006250
11     11-12           -0.004286
12     11-13            0.032857
13     11-14           -0.004286
14     11-15           -0.012857
15     11-16            0.074286
16     11-17            0.041429
17     11-18            0.046250
18     11-19            0.004286
19     11-20            0.024286
20     11-21            0.025714
21     11-22            0.048333
22     11-23            0.108333
23     11-24            0.042000
24     11-25            0.075714
25     11-26           -0.036000
26     11-27            0.065000
27     11-28            0.050000
28     11-29            0.064286
29     11-30            0.124286

In [54]:
mediana_df = []
for month_day in days_list:
 df= oblicz_ceny_flaja(df1, df2, "SBES1H23" , "SBES1K23" , "Unnamed: 1", "Unnamed: 4", month_day )
 mediana_df.append({"month_day": month_day, "cena_flaja_mediana": df["cena_flaja1"].median()})

2023-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-01 00:00:00
               SBES1H23 Unnamed: 1
81  2022-11-01 00:00:00       1.04
                SBES1K23 Unnamed: 4
123  2022-11-01 00:00:00       0.58
2021-11-01 00:00:00
                SBES1H23 Unnamed: 1
386  2021-11-01 00:00:00       0.28
                SBES1K23 Unnamed: 4
429  2021-11-01 00:00:00       0.31
2020-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2019-11-01 00:00:00
                SBES1H23 Unnamed: 1
993  2019-11-01 00:00:00      -0.13
                 SBES1K23 Unnamed: 4
1036  2019-11-01 00:00:00      -0.13
2018-11-01 00:00:00
                 SBES1H23 Unnamed: 1
1297  2018-11-01 00:00:00      -0.09
                 SBES1K23 Unnamed: 4
1339  2018-11-01 00:00:00      -0.05
2017-11-01 00:00:00
                 SBES1H23 Unnamed: 1
1601  2017-11-01 00:00:00      -0.08
                 SBES1K23 Unnamed: 4
1643  2017-11-01 00:00:00      -0.09
2016-11-01 00:00:00
                 SBES1H23 Unnamed: 1
1906  2016-11-01 00:00:00        0.4
                 SBES1K23 Unnamed: 4
1948  2016-11-01 00:00:00       0.53
2015-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2014-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2013-11-01 00:00:00
                 SBES1H23 Unnamed: 1
2818  2013-11-01 00:00:00       0.15
                 SBES1K23 Unnamed: 4
2860  2013-11-01 00:00:00       0.17
2012-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-02 00:00:00
               SBES1H23 Unnamed: 1
80  2022-11-02 00:00:00          1
                SBES1K23 Unnamed: 4
122  2022-11-02 00:00:00       0.54
2021-11-02 00:00:00
                SBES1H23 Unnamed: 1
385  2021-11-02 00:00:00       0.25
                SBES1K23 Unnamed: 4
428  2021-11-02 00:00:00       0.27
2020-11-02 00:00:00
                SBES1H23 Unnamed: 1
688  2020-11-02 00:00:00       1.09
                SBES1K23 Unnamed: 4
732  2020-11-02 00:00:00       0.72
2019-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-11-02 00:00:00
                 SBES1H23 Unnamed: 1
1296  2018-11-02 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1338  2018-11-02 00:00:00      -0.07
2017-11-02 00:00:00
                 SBES1H23 Unnamed: 1
1600  2017-11-02 00:00:00      -0.13
                 SBES1K23 Unnamed: 4
1642  2017-11-02 00:00:00      -0.16
2016-11-02 00:00:00
                 SBES1H23 Unnamed: 1
1905  2016-11-02 00:00:00       0.56
                 SBES1K23 Unnamed: 4
1947  2016-11-02 00:00:00       0.64
2015-11-02 00:00:00
                 SBES1H23 Unnamed: 1
2210  2015-11-02 00:00:00        0.4
                 SBES1K23 Unnamed: 4
2253  2015-11-02 00:00:00       0.29
2014-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2013-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2012-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-03 00:00:00
               SBES1H23 Unnamed: 1
79  2022-11-03 00:00:00          1
                SBES1K23 Unnamed: 4
121  2022-11-03 00:00:00       0.55
2021-11-03 00:00:00
                SBES1H23 Unnamed: 1
384  2021-11-03 00:00:00       0.22
                SBES1K23 Unnamed: 4
427  2021-11-03 00:00:00       0.26
2020-11-03 00:00:00
                SBES1H23 Unnamed: 1
687  2020-11-03 00:00:00       1.03
                SBES1K23 Unnamed: 4
731  2020-11-03 00:00:00       0.68
2019-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-11-03 00:00:00
                 SBES1H23 Unnamed: 1
1599  2017-11-03 00:00:00      -0.11
                 SBES1K23 Unnamed: 4
1641  2017-11-03 00:00:00      -0.13
2016-11-03 00:00:00
                 SBES1H23 Unnamed: 1
1904  2016-11-03 00:00:00       0.49
                 SBES1K23 Unnamed: 4
1946  2016-11-03 00:00:00       0.59
2015-11-03 00:00:00
                 SBES1H23 Unnamed: 1
2209  2015-11-03 00:00:00       0.46
                 SBES1K23 Unnamed: 4
2252  2015-11-03 00:00:00       0.38
2014-11-03 00:00:00
                 SBES1H23 Unnamed: 1
2513  2014-11-03 00:00:00      -0.31
                 SBES1K23 Unnamed: 4
2556  2014-11-03 00:00:00      -0.27
2013-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2012-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-04 00:00:00
               SBES1H23 Unnamed: 1
78  2022-11-04 00:00:00       0.96
                SBES1K23 Unnamed: 4
120  2022-11-04 00:00:00       0.53
2021-11-04 00:00:00
                SBES1H23 Unnamed: 1
383  2021-11-04 00:00:00       0.23
                SBES1K23 Unnamed: 4
426  2021-11-04 00:00:00       0.28
2020-11-04 00:00:00
                SBES1H23 Unnamed: 1
686  2020-11-04 00:00:00       0.96
                SBES1K23 Unnamed: 4
730  2020-11-04 00:00:00       0.67
2019-11-04 00:00:00
                SBES1H23 Unnamed: 1
992  2019-11-04 00:00:00      -0.13
                 SBES1K23 Unnamed: 4
1035  2019-11-04 00:00:00      -0.12
2018-11-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-11-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-11-04 00:00:00
                 SBES1H23 Unnamed: 1
1903  2016-11-04 00:00:00       0.55
                 SBES1K23 Unnamed: 4
1945  2016-11-04 00:00:00       0.64
2015-11-04 00:00:00
                 SBES1H23 Unnamed: 1
2208  2015-11-04 00:00:00       0.34
                 SBES1K23 Unnamed: 4
2251  2015-11-04 00:00:00       0.25
2014-11-04 00:00:00
                 SBES1H23 Unnamed: 1
2512  2014-11-04 00:00:00      -0.38
                 SBES1K23 Unnamed: 4
2555  2014-11-04 00:00:00      -0.31
2013-11-04 00:00:00
                 SBES1H23 Unnamed: 1
2817  2013-11-04 00:00:00       0.17
                 SBES1K23 Unnamed: 4
2859  2013-11-04 00:00:00       0.18
2012-11-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-11-05 00:00:00
                SBES1H23 Unnamed: 1
382  2021-11-05 00:00:00        0.3
                SBES1K23 Unnamed: 4
425  2021-11-05 00:00:00       0.35
2020-11-05 00:00:00
                SBES1H23 Unnamed: 1
685  2020-11-05 00:00:00       0.82
                SBES1K23 Unnamed: 4
729  2020-11-05 00:00:00       0.64
2019-11-05 00:00:00
                SBES1H23 Unnamed: 1
991  2019-11-05 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1034  2019-11-05 00:00:00      -0.11
2018-11-05 00:00:00
                 SBES1H23 Unnamed: 1
1295  2018-11-05 00:00:00      -0.14
                 SBES1K23 Unnamed: 4
1337  2018-11-05 00:00:00      -0.08
2017-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2015-11-05 00:00:00
                 SBES1H23 Unnamed: 1
2207  2015-11-05 00:00:00       0.37
                 SBES1K23 Unnamed: 4
2250  2015-11-05 00:00:00       0.26
2014-11-05 00:00:00
                 SBES1H23 Unnamed: 1
2511  2014-11-05 00:00:00      -0.42
                 SBES1K23 Unnamed: 4
2554  2014-11-05 00:00:00      -0.34
2013-11-05 00:00:00
                 SBES1H23 Unnamed: 1
2816  2013-11-05 00:00:00       0.16
                 SBES1K23 Unnamed: 4
2858  2013-11-05 00:00:00       0.18
2012-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-11-06 00:00:00
                SBES1H23 Unnamed: 1
684  2020-11-06 00:00:00       0.76
                SBES1K23 Unnamed: 4
728  2020-11-06 00:00:00       0.71
2019-11-06 00:00:00
                SBES1H23 Unnamed: 1
990  2019-11-06 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1033  2019-11-06 00:00:00      -0.09
2018-11-06 00:00:00
                 SBES1H23 Unnamed: 1
1294  2018-11-06 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1336  2018-11-06 00:00:00       -0.1
2017-11-06 00:00:00
                 SBES1H23 Unnamed: 1
1598  2017-11-06 00:00:00      -0.08
                 SBES1K23 Unnamed: 4
1640  2017-11-06 00:00:00      -0.08
2016-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2015-11-06 00:00:00
                 SBES1H23 Unnamed: 1
2206  2015-11-06 00:00:00       0.33
                 SBES1K23 Unnamed: 4
2249  2015-11-06 00:00:00       0.24
2014-11-06 00:00:00
                 SBES1H23 Unnamed: 1
2510  2014-11-06 00:00:00      -0.42
                 SBES1K23 Unnamed: 4
2553  2014-11-06 00:00:00      -0.33
2013-11-06 00:00:00
                 SBES1H23 Unnamed: 1
2815  2013-11-06 00:00:00       0.12
                 SBES1K23 Unnamed: 4
2857  2013-11-06 00:00:00       0.15
2012-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-07 00:00:00
               SBES1H23 Unnamed: 1
77  2022-11-07 00:00:00       0.95
                SBES1K23 Unnamed: 4
119  2022-11-07 00:00:00       0.58
2021-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2019-11-07 00:00:00
                SBES1H23 Unnamed: 1
989  2019-11-07 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1032  2019-11-07 00:00:00      -0.11
2018-11-07 00:00:00
                 SBES1H23 Unnamed: 1
1293  2018-11-07 00:00:00      -0.09
                 SBES1K23 Unnamed: 4
1335  2018-11-07 00:00:00      -0.11
2017-11-07 00:00:00
                 SBES1H23 Unnamed: 1
1597  2017-11-07 00:00:00      -0.05
                 SBES1K23 Unnamed: 4
1639  2017-11-07 00:00:00      -0.07
2016-11-07 00:00:00
                 SBES1H23 Unnamed: 1
1902  2016-11-07 00:00:00       0.63
                 SBES1K23 Unnamed: 4
1944  2016-11-07 00:00:00       0.71
2015-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2014-11-07 00:00:00
                 SBES1H23 Unnamed: 1
2509  2014-11-07 00:00:00      -0.36
                 SBES1K23 Unnamed: 4
2552  2014-11-07 00:00:00      -0.26
2013-11-07 00:00:00
                 SBES1H23 Unnamed: 1
2814  2013-11-07 00:00:00       0.14
                 SBES1K23 Unnamed: 4
2856  2013-11-07 00:00:00       0.14
2012-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-08 00:00:00
               SBES1H23 Unnamed: 1
76  2022-11-08 00:00:00       0.95
                SBES1K23 Unnamed: 4
118  2022-11-08 00:00:00       0.58
2021-11-08 00:00:00
                SBES1H23 Unnamed: 1
381  2021-11-08 00:00:00       0.28
                SBES1K23 Unnamed: 4
424  2021-11-08 00:00:00       0.35
2020-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2019-11-08 00:00:00
                SBES1H23 Unnamed: 1
988  2019-11-08 00:00:00      -0.09
                 SBES1K23 Unnamed: 4
1031  2019-11-08 00:00:00       -0.1
2018-11-08 00:00:00
                 SBES1H23 Unnamed: 1
1292  2018-11-08 00:00:00      -0.14
                 SBES1K23 Unnamed: 4
1334  2018-11-08 00:00:00      -0.14
2017-11-08 00:00:00
                 SBES1H23 Unnamed: 1
1596  2017-11-08 00:00:00      -0.07
                 SBES1K23 Unnamed: 4
1638  2017-11-08 00:00:00      -0.05
2016-11-08 00:00:00
                 SBES1H23 Unnamed: 1
1901  2016-11-08 00:00:00       0.61
                 SBES1K23 Unnamed: 4
1943  2016-11-08 00:00:00       0.73
2015-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2014-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2013-11-08 00:00:00
                 SBES1H23 Unnamed: 1
2813  2013-11-08 00:00:00       0.13
                 SBES1K23 Unnamed: 4
2855  2013-11-08 00:00:00       0.16
2012-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-09 00:00:00
               SBES1H23 Unnamed: 1
75  2022-11-09 00:00:00       0.98
                SBES1K23 Unnamed: 4
117  2022-11-09 00:00:00       0.65
2021-11-09 00:00:00
                SBES1H23 Unnamed: 1
380  2021-11-09 00:00:00       0.28
                SBES1K23 Unnamed: 4
423  2021-11-09 00:00:00       0.35
2020-11-09 00:00:00
                SBES1H23 Unnamed: 1
683  2020-11-09 00:00:00       0.75
                SBES1K23 Unnamed: 4
727  2020-11-09 00:00:00       0.71
2019-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-11-09 00:00:00
                 SBES1H23 Unnamed: 1
1291  2018-11-09 00:00:00      -0.14
                 SBES1K23 Unnamed: 4
1333  2018-11-09 00:00:00      -0.15
2017-11-09 00:00:00
                 SBES1H23 Unnamed: 1
1595  2017-11-09 00:00:00      -0.04
                 SBES1K23 Unnamed: 4
1637  2017-11-09 00:00:00      -0.05
2016-11-09 00:00:00
                 SBES1H23 Unnamed: 1
1900  2016-11-09 00:00:00       0.56
                 SBES1K23 Unnamed: 4
1942  2016-11-09 00:00:00        0.7
2015-11-09 00:00:00
                 SBES1H23 Unnamed: 1
2205  2015-11-09 00:00:00       0.31
                 SBES1K23 Unnamed: 4
2248  2015-11-09 00:00:00        0.2
2014-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2013-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2012-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-10 00:00:00
               SBES1H23 Unnamed: 1
74  2022-11-10 00:00:00          1
                SBES1K23 Unnamed: 4
116  2022-11-10 00:00:00       0.71
2021-11-10 00:00:00
                SBES1H23 Unnamed: 1
379  2021-11-10 00:00:00       0.24
                SBES1K23 Unnamed: 4
422  2021-11-10 00:00:00       0.35
2020-11-10 00:00:00
                SBES1H23 Unnamed: 1
682  2020-11-10 00:00:00       0.64
                SBES1K23 Unnamed: 4
726  2020-11-10 00:00:00       0.65
2019-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-11-10 00:00:00
                 SBES1H23 Unnamed: 1
1594  2017-11-10 00:00:00      -0.01
                 SBES1K23 Unnamed: 4
1636  2017-11-10 00:00:00      -0.02
2016-11-10 00:00:00
                 SBES1H23 Unnamed: 1
1899  2016-11-10 00:00:00        0.6
                 SBES1K23 Unnamed: 4
1941  2016-11-10 00:00:00       0.74
2015-11-10 00:00:00
                 SBES1H23 Unnamed: 1
2204  2015-11-10 00:00:00       0.36
                 SBES1K23 Unnamed: 4
2247  2015-11-10 00:00:00       0.25
2014-11-10 00:00:00
                 SBES1H23 Unnamed: 1
2508  2014-11-10 00:00:00      -0.37
                 SBES1K23 Unnamed: 4
2551  2014-11-10 00:00:00      -0.29
2013-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2012-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-11 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-11 00:00:00
               SBES1H23 Unnamed: 1
73  2022-11-11 00:00:00       1.02
                SBES1K23 Unnamed: 4
115  2022-11-11 00:00:00       0.72
2021-11-11 00:00:00
                SBES1H23 Unnamed: 1
378  2021-11-11 00:00:00       0.26
                SBES1K23 Unnamed: 4
421  2021-11-11 00:00:00       0.41
2020-11-11 00:00:00
                SBES1H23 Unnamed: 1
681  2020-11-11 00:00:00       0.69
                SBES1K23 Unnamed: 4
725  2020-11-11 00:00:00       0.62
2019-11-11 00:00:00
                SBES1H23 Unnamed: 1
987  2019-11-11 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1030  2019-11-11 00:00:00      -0.11
2018-11-11 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-11-11 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-11-11 00:00:00
                 SBES1H23 Unnamed: 1
1898  2016-11-11 00:00:00       0.66
                 SBES1K23 Unnamed: 4
1940  2016-11-11 00:00:00       0.83
2015-11-11 00:00:00
                 SBES1H23 Unnamed: 1
2203  2015-11-11 00:00:00       0.35
                 SBES1K23 Unnamed: 4
2246  2015-11-11 00:00:00       0.27
2014-11-11 00:00:00
                 SBES1H23 Unnamed: 1
2507  2014-11-11 00:00:00      -0.26

In [55]:
mediana_df

[{'month_day': '11-01', 'cena_flaja_mediana': -0.020000000000000018},
 {'month_day': '11-02', 'cena_flaja_mediana': 0.03},
 {'month_day': '11-03', 'cena_flaja_mediana': 0.020000000000000004},
 {'month_day': '11-04', 'cena_flaja_mediana': -0.009999999999999995},
 {'month_day': '11-05', 'cena_flaja_mediana': -0.01999999999999999},
 {'month_day': '11-06', 'cena_flaja_mediana': -0.01999999999999999},
 {'month_day': '11-07', 'cena_flaja_mediana': 0.0},
 {'month_day': '11-08', 'cena_flaja_mediana': -0.020000000000000004},
 {'month_day': '11-09', 'cena_flaja_mediana': 0.010000000000000002},
 {'month_day': '11-10', 'cena_flaja_mediana': -0.010000000000000009},
 {'month_day': '11-11', 'cena_flaja_mediana': -0.0049999999999999975},
 {'month_day': '11-12', 'cena_flaja_mediana': -0.009999999999999995},
 {'month_day': '11-13', 'cena_flaja_mediana': 0.0},
 {'month_day': '11-14', 'cena_flaja_mediana': -0.020000000000000004},
 {'month_day': '11-15', 'cena_flaja_mediana': -0.01999999999999999},
 {'month_day': '11-16', 'cena_flaja_mediana': 0.030000000000000002},
 {'month_day': '11-17', 'cena_flaja_mediana': -0.020000000000000004},
 {'month_day': '11-18', 'cena_flaja_mediana': -0.019999999999999997},
 {'month_day': '11-19', 'cena_flaja_mediana': -0.010000000000000009},
 {'month_day': '11-20', 'cena_flaja_mediana': 0.0},
 {'month_day': '11-21', 'cena_flaja_mediana': -0.009999999999999995},
 {'month_day': '11-22', 'cena_flaja_mediana': -0.015},
 {'month_day': '11-23', 'cena_flaja_mediana': 0.045000000000000005},
 {'month_day': '11-24', 'cena_flaja_mediana': 0.039999999999999994},
 {'month_day': '11-25', 'cena_flaja_mediana': -0.01999999999999999},
 {'month_day': '11-26', 'cena_flaja_mediana': -0.03},
 {'month_day': '11-27', 'cena_flaja_mediana': 0.024999999999999994},
 {'month_day': '11-28', 'cena_flaja_mediana': 0.020000000000000004},
 {'month_day': '11-29', 'cena_flaja_mediana': 0.0},
 {'month_day': '11-30', 'cena_flaja_mediana': 0.1}]

In [56]:
df_mediana = pd.DataFrame(mediana_df)

In [57]:
df_mediana

   month_day  cena_flaja_mediana
0      11-01              -0.020
1      11-02               0.030
2      11-03               0.020
3      11-04              -0.010
4      11-05              -0.020
5      11-06              -0.020
6      11-07               0.000
7      11-08              -0.020
8      11-09               0.010
9      11-10              -0.010
10     11-11              -0.005
11     11-12              -0.010
12     11-13               0.000
13     11-14              -0.020
14     11-15              -0.020
15     11-16               0.030
16     11-17              -0.020
17     11-18              -0.020
18     11-19              -0.010
19     11-20               0.000
20     11-21              -0.010
21     11-22              -0.015
22     11-23               0.045
23     11-24               0.040
24     11-25              -0.020
25     11-26              -0.030
26     11-27               0.025
27     11-28               0.020
28     11-29               0.000
29     11-30               0.100

In [58]:
haj_df = []
for month_day in days_list:
 df= oblicz_ceny_flaja(df1, df2, "SBES1H23" , "SBES1K23" , "Unnamed: 1", "Unnamed: 4", month_day )
 haj_df.append({"month_day": month_day, "cena_flaja_haj": df["cena_flaja1"].max()})

2023-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-01 00:00:00
               SBES1H23 Unnamed: 1
81  2022-11-01 00:00:00       1.04
                SBES1K23 Unnamed: 4
123  2022-11-01 00:00:00       0.58
2021-11-01 00:00:00
                SBES1H23 Unnamed: 1
386  2021-11-01 00:00:00       0.28
                SBES1K23 Unnamed: 4
429  2021-11-01 00:00:00       0.31
2020-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2019-11-01 00:00:00
                SBES1H23 Unnamed: 1
993  2019-11-01 00:00:00      -0.13
                 SBES1K23 Unnamed: 4
1036  2019-11-01 00:00:00      -0.13
2018-11-01 00:00:00
                 SBES1H23 Unnamed: 1
1297  2018-11-01 00:00:00      -0.09
                 SBES1K23 Unnamed: 4
1339  2018-11-01 00:00:00      -0.05
2017-11-01 00:00:00
                 SBES1H23 Unnamed: 1
1601  2017-11-01 00:00:00      -0.08
                 SBES1K23 Unnamed: 4
1643  2017-11-01 00:00:00      -0.09
2016-11-01 00:00:00
                 SBES1H23 Unnamed: 1
1906  2016-11-01 00:00:00        0.4
                 SBES1K23 Unnamed: 4
1948  2016-11-01 00:00:00       0.53
2015-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2014-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2013-11-01 00:00:00
                 SBES1H23 Unnamed: 1
2818  2013-11-01 00:00:00       0.15
                 SBES1K23 Unnamed: 4
2860  2013-11-01 00:00:00       0.17
2012-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-02 00:00:00
               SBES1H23 Unnamed: 1
80  2022-11-02 00:00:00          1
                SBES1K23 Unnamed: 4
122  2022-11-02 00:00:00       0.54
2021-11-02 00:00:00
                SBES1H23 Unnamed: 1
385  2021-11-02 00:00:00       0.25
                SBES1K23 Unnamed: 4
428  2021-11-02 00:00:00       0.27
2020-11-02 00:00:00
                SBES1H23 Unnamed: 1
688  2020-11-02 00:00:00       1.09
                SBES1K23 Unnamed: 4
732  2020-11-02 00:00:00       0.72
2019-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-11-02 00:00:00
                 SBES1H23 Unnamed: 1
1296  2018-11-02 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1338  2018-11-02 00:00:00      -0.07
2017-11-02 00:00:00
                 SBES1H23 Unnamed: 1
1600  2017-11-02 00:00:00      -0.13
                 SBES1K23 Unnamed: 4
1642  2017-11-02 00:00:00      -0.16
2016-11-02 00:00:00
                 SBES1H23 Unnamed: 1
1905  2016-11-02 00:00:00       0.56
                 SBES1K23 Unnamed: 4
1947  2016-11-02 00:00:00       0.64
2015-11-02 00:00:00
                 SBES1H23 Unnamed: 1
2210  2015-11-02 00:00:00        0.4
                 SBES1K23 Unnamed: 4
2253  2015-11-02 00:00:00       0.29
2014-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2013-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2012-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-03 00:00:00
               SBES1H23 Unnamed: 1
79  2022-11-03 00:00:00          1
                SBES1K23 Unnamed: 4
121  2022-11-03 00:00:00       0.55
2021-11-03 00:00:00
                SBES1H23 Unnamed: 1
384  2021-11-03 00:00:00       0.22
                SBES1K23 Unnamed: 4
427  2021-11-03 00:00:00       0.26
2020-11-03 00:00:00
                SBES1H23 Unnamed: 1
687  2020-11-03 00:00:00       1.03
                SBES1K23 Unnamed: 4
731  2020-11-03 00:00:00       0.68
2019-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-11-03 00:00:00
                 SBES1H23 Unnamed: 1
1599  2017-11-03 00:00:00      -0.11
                 SBES1K23 Unnamed: 4
1641  2017-11-03 00:00:00      -0.13
2016-11-03 00:00:00
                 SBES1H23 Unnamed: 1
1904  2016-11-03 00:00:00       0.49
                 SBES1K23 Unnamed: 4
1946  2016-11-03 00:00:00       0.59
2015-11-03 00:00:00
                 SBES1H23 Unnamed: 1
2209  2015-11-03 00:00:00       0.46
                 SBES1K23 Unnamed: 4
2252  2015-11-03 00:00:00       0.38
2014-11-03 00:00:00
                 SBES1H23 Unnamed: 1
2513  2014-11-03 00:00:00      -0.31
                 SBES1K23 Unnamed: 4
2556  2014-11-03 00:00:00      -0.27
2013-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2012-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-04 00:00:00
               SBES1H23 Unnamed: 1
78  2022-11-04 00:00:00       0.96
                SBES1K23 Unnamed: 4
120  2022-11-04 00:00:00       0.53
2021-11-04 00:00:00
                SBES1H23 Unnamed: 1
383  2021-11-04 00:00:00       0.23
                SBES1K23 Unnamed: 4
426  2021-11-04 00:00:00       0.28
2020-11-04 00:00:00
                SBES1H23 Unnamed: 1
686  2020-11-04 00:00:00       0.96
                SBES1K23 Unnamed: 4
730  2020-11-04 00:00:00       0.67
2019-11-04 00:00:00
                SBES1H23 Unnamed: 1
992  2019-11-04 00:00:00      -0.13
                 SBES1K23 Unnamed: 4
1035  2019-11-04 00:00:00      -0.12
2018-11-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-11-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-11-04 00:00:00
                 SBES1H23 Unnamed: 1
1903  2016-11-04 00:00:00       0.55
                 SBES1K23 Unnamed: 4
1945  2016-11-04 00:00:00       0.64
2015-11-04 00:00:00
                 SBES1H23 Unnamed: 1
2208  2015-11-04 00:00:00       0.34
                 SBES1K23 Unnamed: 4
2251  2015-11-04 00:00:00       0.25
2014-11-04 00:00:00
                 SBES1H23 Unnamed: 1
2512  2014-11-04 00:00:00      -0.38
                 SBES1K23 Unnamed: 4
2555  2014-11-04 00:00:00      -0.31
2013-11-04 00:00:00
                 SBES1H23 Unnamed: 1
2817  2013-11-04 00:00:00       0.17
                 SBES1K23 Unnamed: 4
2859  2013-11-04 00:00:00       0.18
2012-11-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-11-05 00:00:00
                SBES1H23 Unnamed: 1
382  2021-11-05 00:00:00        0.3
                SBES1K23 Unnamed: 4
425  2021-11-05 00:00:00       0.35
2020-11-05 00:00:00
                SBES1H23 Unnamed: 1
685  2020-11-05 00:00:00       0.82
                SBES1K23 Unnamed: 4
729  2020-11-05 00:00:00       0.64
2019-11-05 00:00:00
                SBES1H23 Unnamed: 1
991  2019-11-05 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1034  2019-11-05 00:00:00      -0.11
2018-11-05 00:00:00
                 SBES1H23 Unnamed: 1
1295  2018-11-05 00:00:00      -0.14
                 SBES1K23 Unnamed: 4
1337  2018-11-05 00:00:00      -0.08
2017-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2015-11-05 00:00:00
                 SBES1H23 Unnamed: 1
2207  2015-11-05 00:00:00       0.37
                 SBES1K23 Unnamed: 4
2250  2015-11-05 00:00:00       0.26
2014-11-05 00:00:00
                 SBES1H23 Unnamed: 1
2511  2014-11-05 00:00:00      -0.42
                 SBES1K23 Unnamed: 4
2554  2014-11-05 00:00:00      -0.34
2013-11-05 00:00:00
                 SBES1H23 Unnamed: 1
2816  2013-11-05 00:00:00       0.16
                 SBES1K23 Unnamed: 4
2858  2013-11-05 00:00:00       0.18
2012-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-11-06 00:00:00
                SBES1H23 Unnamed: 1
684  2020-11-06 00:00:00       0.76
                SBES1K23 Unnamed: 4
728  2020-11-06 00:00:00       0.71
2019-11-06 00:00:00
                SBES1H23 Unnamed: 1
990  2019-11-06 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1033  2019-11-06 00:00:00      -0.09
2018-11-06 00:00:00
                 SBES1H23 Unnamed: 1
1294  2018-11-06 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1336  2018-11-06 00:00:00       -0.1
2017-11-06 00:00:00
                 SBES1H23 Unnamed: 1
1598  2017-11-06 00:00:00      -0.08
                 SBES1K23 Unnamed: 4
1640  2017-11-06 00:00:00      -0.08
2016-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2015-11-06 00:00:00
                 SBES1H23 Unnamed: 1
2206  2015-11-06 00:00:00       0.33
                 SBES1K23 Unnamed: 4
2249  2015-11-06 00:00:00       0.24
2014-11-06 00:00:00
                 SBES1H23 Unnamed: 1
2510  2014-11-06 00:00:00      -0.42
                 SBES1K23 Unnamed: 4
2553  2014-11-06 00:00:00      -0.33
2013-11-06 00:00:00
                 SBES1H23 Unnamed: 1
2815  2013-11-06 00:00:00       0.12
                 SBES1K23 Unnamed: 4
2857  2013-11-06 00:00:00       0.15
2012-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-07 00:00:00
               SBES1H23 Unnamed: 1
77  2022-11-07 00:00:00       0.95
                SBES1K23 Unnamed: 4
119  2022-11-07 00:00:00       0.58
2021-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2019-11-07 00:00:00
                SBES1H23 Unnamed: 1
989  2019-11-07 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1032  2019-11-07 00:00:00      -0.11
2018-11-07 00:00:00
                 SBES1H23 Unnamed: 1
1293  2018-11-07 00:00:00      -0.09
                 SBES1K23 Unnamed: 4
1335  2018-11-07 00:00:00      -0.11
2017-11-07 00:00:00
                 SBES1H23 Unnamed: 1
1597  2017-11-07 00:00:00      -0.05
                 SBES1K23 Unnamed: 4
1639  2017-11-07 00:00:00      -0.07
2016-11-07 00:00:00
                 SBES1H23 Unnamed: 1
1902  2016-11-07 00:00:00       0.63
                 SBES1K23 Unnamed: 4
1944  2016-11-07 00:00:00       0.71
2015-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2014-11-07 00:00:00
                 SBES1H23 Unnamed: 1
2509  2014-11-07 00:00:00      -0.36
                 SBES1K23 Unnamed: 4
2552  2014-11-07 00:00:00      -0.26
2013-11-07 00:00:00
                 SBES1H23 Unnamed: 1
2814  2013-11-07 00:00:00       0.14
                 SBES1K23 Unnamed: 4
2856  2013-11-07 00:00:00       0.14
2012-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-08 00:00:00
               SBES1H23 Unnamed: 1
76  2022-11-08 00:00:00       0.95
                SBES1K23 Unnamed: 4
118  2022-11-08 00:00:00       0.58
2021-11-08 00:00:00
                SBES1H23 Unnamed: 1
381  2021-11-08 00:00:00       0.28
                SBES1K23 Unnamed: 4
424  2021-11-08 00:00:00       0.35
2020-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2019-11-08 00:00:00
                SBES1H23 Unnamed: 1
988  2019-11-08 00:00:00      -0.09
                 SBES1K23 Unnamed: 4
1031  2019-11-08 00:00:00       -0.1
2018-11-08 00:00:00
                 SBES1H23 Unnamed: 1
1292  2018-11-08 00:00:00      -0.14
                 SBES1K23 Unnamed: 4
1334  2018-11-08 00:00:00      -0.14
2017-11-08 00:00:00
                 SBES1H23 Unnamed: 1
1596  2017-11-08 00:00:00      -0.07
                 SBES1K23 Unnamed: 4
1638  2017-11-08 00:00:00      -0.05
2016-11-08 00:00:00
                 SBES1H23 Unnamed: 1
1901  2016-11-08 00:00:00       0.61
                 SBES1K23 Unnamed: 4
1943  2016-11-08 00:00:00       0.73
2015-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2014-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2013-11-08 00:00:00
                 SBES1H23 Unnamed: 1
2813  2013-11-08 00:00:00       0.13
                 SBES1K23 Unnamed: 4
2855  2013-11-08 00:00:00       0.16
2012-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-09 00:00:00
               SBES1H23 Unnamed: 1
75  2022-11-09 00:00:00       0.98
                SBES1K23 Unnamed: 4
117  2022-11-09 00:00:00       0.65
2021-11-09 00:00:00
                SBES1H23 Unnamed: 1
380  2021-11-09 00:00:00       0.28
                SBES1K23 Unnamed: 4
423  2021-11-09 00:00:00       0.35
2020-11-09 00:00:00
                SBES1H23 Unnamed: 1
683  2020-11-09 00:00:00       0.75
                SBES1K23 Unnamed: 4
727  2020-11-09 00:00:00       0.71
2019-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-11-09 00:00:00
                 SBES1H23 Unnamed: 1
1291  2018-11-09 00:00:00      -0.14
                 SBES1K23 Unnamed: 4
1333  2018-11-09 00:00:00      -0.15
2017-11-09 00:00:00
                 SBES1H23 Unnamed: 1
1595  2017-11-09 00:00:00      -0.04
                 SBES1K23 Unnamed: 4
1637  2017-11-09 00:00:00      -0.05
2016-11-09 00:00:00
                 SBES1H23 Unnamed: 1
1900  2016-11-09 00:00:00       0.56
                 SBES1K23 Unnamed: 4
1942  2016-11-09 00:00:00        0.7
2015-11-09 00:00:00
                 SBES1H23 Unnamed: 1
2205  2015-11-09 00:00:00       0.31
                 SBES1K23 Unnamed: 4
2248  2015-11-09 00:00:00        0.2
2014-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2013-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2012-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-10 00:00:00
               SBES1H23 Unnamed: 1
74  2022-11-10 00:00:00          1
                SBES1K23 Unnamed: 4
116  2022-11-10 00:00:00       0.71
2021-11-10 00:00:00
                SBES1H23 Unnamed: 1
379  2021-11-10 00:00:00       0.24
                SBES1K23 Unnamed: 4
422  2021-11-10 00:00:00       0.35
2020-11-10 00:00:00
                SBES1H23 Unnamed: 1
682  2020-11-10 00:00:00       0.64
                SBES1K23 Unnamed: 4
726  2020-11-10 00:00:00       0.65
2019-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-11-10 00:00:00
                 SBES1H23 Unnamed: 1
1594  2017-11-10 00:00:00      -0.01
                 SBES1K23 Unnamed: 4
1636  2017-11-10 00:00:00      -0.02
2016-11-10 00:00:00
                 SBES1H23 Unnamed: 1
1899  2016-11-10 00:00:00        0.6
                 SBES1K23 Unnamed: 4
1941  2016-11-10 00:00:00       0.74
2015-11-10 00:00:00
                 SBES1H23 Unnamed: 1
2204  2015-11-10 00:00:00       0.36
                 SBES1K23 Unnamed: 4
2247  2015-11-10 00:00:00       0.25
2014-11-10 00:00:00
                 SBES1H23 Unnamed: 1
2508  2014-11-10 00:00:00      -0.37
                 SBES1K23 Unnamed: 4
2551  2014-11-10 00:00:00      -0.29
2013-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2012-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-11 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-11 00:00:00
               SBES1H23 Unnamed: 1
73  2022-11-11 00:00:00       1.02
                SBES1K23 Unnamed: 4
115  2022-11-11 00:00:00       0.72
2021-11-11 00:00:00
                SBES1H23 Unnamed: 1
378  2021-11-11 00:00:00       0.26
                SBES1K23 Unnamed: 4
421  2021-11-11 00:00:00       0.41
2020-11-11 00:00:00
                SBES1H23 Unnamed: 1
681  2020-11-11 00:00:00       0.69
                SBES1K23 Unnamed: 4
725  2020-11-11 00:00:00       0.62
2019-11-11 00:00:00
                SBES1H23 Unnamed: 1
987  2019-11-11 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1030  2019-11-11 00:00:00      -0.11
2018-11-11 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-11-11 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-11-11 00:00:00
                 SBES1H23 Unnamed: 1
1898  2016-11-11 00:00:00       0.66
                 SBES1K23 Unnamed: 4
1940  2016-11-11 00:00:00       0.83
2015-11-11 00:00:00
                 SBES1H23 Unnamed: 1
2203  2015-11-11 00:00:00       0.35
                 SBES1K23 Unnamed: 4
2246  2015-11-11 00:00:00       0.27
2014-11-11 00:00:00
                 SBES1H23 Unnamed: 1
2507  2014-11-11 00:00:00      -0.26

In [59]:
df_haj = pd.DataFrame(haj_df)

In [60]:
df_haj

   month_day  cena_flaja_haj
0      11-01            0.46
1      11-02            0.46
2      11-03            0.45
3      11-04            0.43
4      11-05            0.18
5      11-06            0.09
6      11-07            0.37
7      11-08            0.37
8      11-09            0.33
9      11-10            0.29
10     11-11            0.30
11     11-12            0.14
12     11-13            0.24
13     11-14            0.32
14     11-15            0.32
15     11-16            0.45
16     11-17            0.41
17     11-18            0.45
18     11-19            0.13
19     11-20            0.20
20     11-21            0.45
21     11-22            0.39
22     11-23            0.39
23     11-24            0.27
24     11-25            0.40
25     11-26            0.07
26     11-27            0.27
27     11-28            0.42
28     11-29            0.46
29     11-30            0.43

In [61]:
low_df = []
for month_day in days_list:
 df= oblicz_ceny_flaja(df1, df2, "SBES1H23" , "SBES1K23" , "Unnamed: 1", "Unnamed: 4", month_day )
 low_df.append({"month_day": month_day, "cena_flaja_low": df["cena_flaja1"].min()})

2023-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-01 00:00:00
               SBES1H23 Unnamed: 1
81  2022-11-01 00:00:00       1.04
                SBES1K23 Unnamed: 4
123  2022-11-01 00:00:00       0.58
2021-11-01 00:00:00
                SBES1H23 Unnamed: 1
386  2021-11-01 00:00:00       0.28
                SBES1K23 Unnamed: 4
429  2021-11-01 00:00:00       0.31
2020-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2019-11-01 00:00:00
                SBES1H23 Unnamed: 1
993  2019-11-01 00:00:00      -0.13
                 SBES1K23 Unnamed: 4
1036  2019-11-01 00:00:00      -0.13
2018-11-01 00:00:00
                 SBES1H23 Unnamed: 1
1297  2018-11-01 00:00:00      -0.09
                 SBES1K23 Unnamed: 4
1339  2018-11-01 00:00:00      -0.05
2017-11-01 00:00:00
                 SBES1H23 Unnamed: 1
1601  2017-11-01 00:00:00      -0.08
                 SBES1K23 Unnamed: 4
1643  2017-11-01 00:00:00      -0.09
2016-11-01 00:00:00
                 SBES1H23 Unnamed: 1
1906  2016-11-01 00:00:00        0.4
                 SBES1K23 Unnamed: 4
1948  2016-11-01 00:00:00       0.53
2015-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2014-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2013-11-01 00:00:00
                 SBES1H23 Unnamed: 1
2818  2013-11-01 00:00:00       0.15
                 SBES1K23 Unnamed: 4
2860  2013-11-01 00:00:00       0.17
2012-11-01 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-02 00:00:00
               SBES1H23 Unnamed: 1
80  2022-11-02 00:00:00          1
                SBES1K23 Unnamed: 4
122  2022-11-02 00:00:00       0.54
2021-11-02 00:00:00
                SBES1H23 Unnamed: 1
385  2021-11-02 00:00:00       0.25
                SBES1K23 Unnamed: 4
428  2021-11-02 00:00:00       0.27
2020-11-02 00:00:00
                SBES1H23 Unnamed: 1
688  2020-11-02 00:00:00       1.09
                SBES1K23 Unnamed: 4
732  2020-11-02 00:00:00       0.72
2019-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-11-02 00:00:00
                 SBES1H23 Unnamed: 1
1296  2018-11-02 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1338  2018-11-02 00:00:00      -0.07
2017-11-02 00:00:00
                 SBES1H23 Unnamed: 1
1600  2017-11-02 00:00:00      -0.13
                 SBES1K23 Unnamed: 4
1642  2017-11-02 00:00:00      -0.16
2016-11-02 00:00:00
                 SBES1H23 Unnamed: 1
1905  2016-11-02 00:00:00       0.56
                 SBES1K23 Unnamed: 4
1947  2016-11-02 00:00:00       0.64
2015-11-02 00:00:00
                 SBES1H23 Unnamed: 1
2210  2015-11-02 00:00:00        0.4
                 SBES1K23 Unnamed: 4
2253  2015-11-02 00:00:00       0.29
2014-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2013-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2012-11-02 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-03 00:00:00
               SBES1H23 Unnamed: 1
79  2022-11-03 00:00:00          1
                SBES1K23 Unnamed: 4
121  2022-11-03 00:00:00       0.55
2021-11-03 00:00:00
                SBES1H23 Unnamed: 1
384  2021-11-03 00:00:00       0.22
                SBES1K23 Unnamed: 4
427  2021-11-03 00:00:00       0.26
2020-11-03 00:00:00
                SBES1H23 Unnamed: 1
687  2020-11-03 00:00:00       1.03
                SBES1K23 Unnamed: 4
731  2020-11-03 00:00:00       0.68
2019-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-11-03 00:00:00
                 SBES1H23 Unnamed: 1
1599  2017-11-03 00:00:00      -0.11
                 SBES1K23 Unnamed: 4
1641  2017-11-03 00:00:00      -0.13
2016-11-03 00:00:00
                 SBES1H23 Unnamed: 1
1904  2016-11-03 00:00:00       0.49
                 SBES1K23 Unnamed: 4
1946  2016-11-03 00:00:00       0.59
2015-11-03 00:00:00
                 SBES1H23 Unnamed: 1
2209  2015-11-03 00:00:00       0.46
                 SBES1K23 Unnamed: 4
2252  2015-11-03 00:00:00       0.38
2014-11-03 00:00:00
                 SBES1H23 Unnamed: 1
2513  2014-11-03 00:00:00      -0.31
                 SBES1K23 Unnamed: 4
2556  2014-11-03 00:00:00      -0.27
2013-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2012-11-03 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-04 00:00:00
               SBES1H23 Unnamed: 1
78  2022-11-04 00:00:00       0.96
                SBES1K23 Unnamed: 4
120  2022-11-04 00:00:00       0.53
2021-11-04 00:00:00
                SBES1H23 Unnamed: 1
383  2021-11-04 00:00:00       0.23
                SBES1K23 Unnamed: 4
426  2021-11-04 00:00:00       0.28
2020-11-04 00:00:00
                SBES1H23 Unnamed: 1
686  2020-11-04 00:00:00       0.96
                SBES1K23 Unnamed: 4
730  2020-11-04 00:00:00       0.67
2019-11-04 00:00:00
                SBES1H23 Unnamed: 1
992  2019-11-04 00:00:00      -0.13
                 SBES1K23 Unnamed: 4
1035  2019-11-04 00:00:00      -0.12
2018-11-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-11-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-11-04 00:00:00
                 SBES1H23 Unnamed: 1
1903  2016-11-04 00:00:00       0.55
                 SBES1K23 Unnamed: 4
1945  2016-11-04 00:00:00       0.64
2015-11-04 00:00:00
                 SBES1H23 Unnamed: 1
2208  2015-11-04 00:00:00       0.34
                 SBES1K23 Unnamed: 4
2251  2015-11-04 00:00:00       0.25
2014-11-04 00:00:00
                 SBES1H23 Unnamed: 1
2512  2014-11-04 00:00:00      -0.38
                 SBES1K23 Unnamed: 4
2555  2014-11-04 00:00:00      -0.31
2013-11-04 00:00:00
                 SBES1H23 Unnamed: 1
2817  2013-11-04 00:00:00       0.17
                 SBES1K23 Unnamed: 4
2859  2013-11-04 00:00:00       0.18
2012-11-04 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-11-05 00:00:00
                SBES1H23 Unnamed: 1
382  2021-11-05 00:00:00        0.3
                SBES1K23 Unnamed: 4
425  2021-11-05 00:00:00       0.35
2020-11-05 00:00:00
                SBES1H23 Unnamed: 1
685  2020-11-05 00:00:00       0.82
                SBES1K23 Unnamed: 4
729  2020-11-05 00:00:00       0.64
2019-11-05 00:00:00
                SBES1H23 Unnamed: 1
991  2019-11-05 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1034  2019-11-05 00:00:00      -0.11
2018-11-05 00:00:00
                 SBES1H23 Unnamed: 1
1295  2018-11-05 00:00:00      -0.14
                 SBES1K23 Unnamed: 4
1337  2018-11-05 00:00:00      -0.08
2017-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2015-11-05 00:00:00
                 SBES1H23 Unnamed: 1
2207  2015-11-05 00:00:00       0.37
                 SBES1K23 Unnamed: 4
2250  2015-11-05 00:00:00       0.26
2014-11-05 00:00:00
                 SBES1H23 Unnamed: 1
2511  2014-11-05 00:00:00      -0.42
                 SBES1K23 Unnamed: 4
2554  2014-11-05 00:00:00      -0.34
2013-11-05 00:00:00
                 SBES1H23 Unnamed: 1
2816  2013-11-05 00:00:00       0.16
                 SBES1K23 Unnamed: 4
2858  2013-11-05 00:00:00       0.18
2012-11-05 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2021-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-11-06 00:00:00
                SBES1H23 Unnamed: 1
684  2020-11-06 00:00:00       0.76
                SBES1K23 Unnamed: 4
728  2020-11-06 00:00:00       0.71
2019-11-06 00:00:00
                SBES1H23 Unnamed: 1
990  2019-11-06 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1033  2019-11-06 00:00:00      -0.09
2018-11-06 00:00:00
                 SBES1H23 Unnamed: 1
1294  2018-11-06 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1336  2018-11-06 00:00:00       -0.1
2017-11-06 00:00:00
                 SBES1H23 Unnamed: 1
1598  2017-11-06 00:00:00      -0.08
                 SBES1K23 Unnamed: 4
1640  2017-11-06 00:00:00      -0.08
2016-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2015-11-06 00:00:00
                 SBES1H23 Unnamed: 1
2206  2015-11-06 00:00:00       0.33
                 SBES1K23 Unnamed: 4
2249  2015-11-06 00:00:00       0.24
2014-11-06 00:00:00
                 SBES1H23 Unnamed: 1
2510  2014-11-06 00:00:00      -0.42
                 SBES1K23 Unnamed: 4
2553  2014-11-06 00:00:00      -0.33
2013-11-06 00:00:00
                 SBES1H23 Unnamed: 1
2815  2013-11-06 00:00:00       0.12
                 SBES1K23 Unnamed: 4
2857  2013-11-06 00:00:00       0.15
2012-11-06 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-07 00:00:00
               SBES1H23 Unnamed: 1
77  2022-11-07 00:00:00       0.95
                SBES1K23 Unnamed: 4
119  2022-11-07 00:00:00       0.58
2021-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2020-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2019-11-07 00:00:00
                SBES1H23 Unnamed: 1
989  2019-11-07 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1032  2019-11-07 00:00:00      -0.11
2018-11-07 00:00:00
                 SBES1H23 Unnamed: 1
1293  2018-11-07 00:00:00      -0.09
                 SBES1K23 Unnamed: 4
1335  2018-11-07 00:00:00      -0.11
2017-11-07 00:00:00
                 SBES1H23 Unnamed: 1
1597  2017-11-07 00:00:00      -0.05
                 SBES1K23 Unnamed: 4
1639  2017-11-07 00:00:00      -0.07
2016-11-07 00:00:00
                 SBES1H23 Unnamed: 1
1902  2016-11-07 00:00:00       0.63
                 SBES1K23 Unnamed: 4
1944  2016-11-07 00:00:00       0.71
2015-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2014-11-07 00:00:00
                 SBES1H23 Unnamed: 1
2509  2014-11-07 00:00:00      -0.36
                 SBES1K23 Unnamed: 4
2552  2014-11-07 00:00:00      -0.26
2013-11-07 00:00:00
                 SBES1H23 Unnamed: 1
2814  2013-11-07 00:00:00       0.14
                 SBES1K23 Unnamed: 4
2856  2013-11-07 00:00:00       0.14
2012-11-07 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-08 00:00:00
               SBES1H23 Unnamed: 1
76  2022-11-08 00:00:00       0.95
                SBES1K23 Unnamed: 4
118  2022-11-08 00:00:00       0.58
2021-11-08 00:00:00
                SBES1H23 Unnamed: 1
381  2021-11-08 00:00:00       0.28
                SBES1K23 Unnamed: 4
424  2021-11-08 00:00:00       0.35
2020-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2019-11-08 00:00:00
                SBES1H23 Unnamed: 1
988  2019-11-08 00:00:00      -0.09
                 SBES1K23 Unnamed: 4
1031  2019-11-08 00:00:00       -0.1
2018-11-08 00:00:00
                 SBES1H23 Unnamed: 1
1292  2018-11-08 00:00:00      -0.14
                 SBES1K23 Unnamed: 4
1334  2018-11-08 00:00:00      -0.14
2017-11-08 00:00:00
                 SBES1H23 Unnamed: 1
1596  2017-11-08 00:00:00      -0.07
                 SBES1K23 Unnamed: 4
1638  2017-11-08 00:00:00      -0.05
2016-11-08 00:00:00
                 SBES1H23 Unnamed: 1
1901  2016-11-08 00:00:00       0.61
                 SBES1K23 Unnamed: 4
1943  2016-11-08 00:00:00       0.73
2015-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2014-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2013-11-08 00:00:00
                 SBES1H23 Unnamed: 1
2813  2013-11-08 00:00:00       0.13
                 SBES1K23 Unnamed: 4
2855  2013-11-08 00:00:00       0.16
2012-11-08 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-09 00:00:00
               SBES1H23 Unnamed: 1
75  2022-11-09 00:00:00       0.98
                SBES1K23 Unnamed: 4
117  2022-11-09 00:00:00       0.65
2021-11-09 00:00:00
                SBES1H23 Unnamed: 1
380  2021-11-09 00:00:00       0.28
                SBES1K23 Unnamed: 4
423  2021-11-09 00:00:00       0.35
2020-11-09 00:00:00
                SBES1H23 Unnamed: 1
683  2020-11-09 00:00:00       0.75
                SBES1K23 Unnamed: 4
727  2020-11-09 00:00:00       0.71
2019-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-11-09 00:00:00
                 SBES1H23 Unnamed: 1
1291  2018-11-09 00:00:00      -0.14
                 SBES1K23 Unnamed: 4
1333  2018-11-09 00:00:00      -0.15
2017-11-09 00:00:00
                 SBES1H23 Unnamed: 1
1595  2017-11-09 00:00:00      -0.04
                 SBES1K23 Unnamed: 4
1637  2017-11-09 00:00:00      -0.05
2016-11-09 00:00:00
                 SBES1H23 Unnamed: 1
1900  2016-11-09 00:00:00       0.56
                 SBES1K23 Unnamed: 4
1942  2016-11-09 00:00:00        0.7
2015-11-09 00:00:00
                 SBES1H23 Unnamed: 1
2205  2015-11-09 00:00:00       0.31
                 SBES1K23 Unnamed: 4
2248  2015-11-09 00:00:00        0.2
2014-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2013-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2012-11-09 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-10 00:00:00
               SBES1H23 Unnamed: 1
74  2022-11-10 00:00:00          1
                SBES1K23 Unnamed: 4
116  2022-11-10 00:00:00       0.71
2021-11-10 00:00:00
                SBES1H23 Unnamed: 1
379  2021-11-10 00:00:00       0.24
                SBES1K23 Unnamed: 4
422  2021-11-10 00:00:00       0.35
2020-11-10 00:00:00
                SBES1H23 Unnamed: 1
682  2020-11-10 00:00:00       0.64
                SBES1K23 Unnamed: 4
726  2020-11-10 00:00:00       0.65
2019-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2018-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-11-10 00:00:00
                 SBES1H23 Unnamed: 1
1594  2017-11-10 00:00:00      -0.01
                 SBES1K23 Unnamed: 4
1636  2017-11-10 00:00:00      -0.02
2016-11-10 00:00:00
                 SBES1H23 Unnamed: 1
1899  2016-11-10 00:00:00        0.6
                 SBES1K23 Unnamed: 4
1941  2016-11-10 00:00:00       0.74
2015-11-10 00:00:00
                 SBES1H23 Unnamed: 1
2204  2015-11-10 00:00:00       0.36
                 SBES1K23 Unnamed: 4
2247  2015-11-10 00:00:00       0.25
2014-11-10 00:00:00
                 SBES1H23 Unnamed: 1
2508  2014-11-10 00:00:00      -0.37
                 SBES1K23 Unnamed: 4
2551  2014-11-10 00:00:00      -0.29
2013-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2012-11-10 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2023-11-11 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2022-11-11 00:00:00
               SBES1H23 Unnamed: 1
73  2022-11-11 00:00:00       1.02
                SBES1K23 Unnamed: 4
115  2022-11-11 00:00:00       0.72
2021-11-11 00:00:00
                SBES1H23 Unnamed: 1
378  2021-11-11 00:00:00       0.26
                SBES1K23 Unnamed: 4
421  2021-11-11 00:00:00       0.41
2020-11-11 00:00:00
                SBES1H23 Unnamed: 1
681  2020-11-11 00:00:00       0.69
                SBES1K23 Unnamed: 4
725  2020-11-11 00:00:00       0.62
2019-11-11 00:00:00
                SBES1H23 Unnamed: 1
987  2019-11-11 00:00:00      -0.12
                 SBES1K23 Unnamed: 4
1030  2019-11-11 00:00:00      -0.11
2018-11-11 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2017-11-11 00:00:00
Empty DataFrame
Columns: [SBES1H23, Unnamed: 1]
Index: []
Empty DataFrame
Columns: [SBES1K23, Unnamed: 4]
Index: []
2016-11-11 00:00:00
                 SBES1H23 Unnamed: 1
1898  2016-11-11 00:00:00       0.66
                 SBES1K23 Unnamed: 4
1940  2016-11-11 00:00:00       0.83
2015-11-11 00:00:00
                 SBES1H23 Unnamed: 1
2203  2015-11-11 00:00:00       0.35
                 SBES1K23 Unnamed: 4
2246  2015-11-11 00:00:00       0.27
2014-11-11 00:00:00
                 SBES1H23 Unnamed: 1
2507  2014-11-11 00:00:00      -0.26

In [62]:
df_low = pd.DataFrame(low_df)

In [63]:
df_low

   month_day  cena_flaja_low
0      11-01           -0.13
1      11-02           -0.08
2      11-03           -0.10
3      11-04           -0.09
4      11-05           -0.08
5      11-06           -0.09
6      11-07           -0.10
7      11-08           -0.12
8      11-09           -0.14
9      11-10           -0.14
10     11-11           -0.17
11     11-12           -0.15
12     11-13           -0.09
13     11-14           -0.17
14     11-15           -0.20
15     11-16           -0.14
16     11-17           -0.14
17     11-18           -0.13
18     11-19           -0.12
19     11-20           -0.14
20     11-21           -0.15
21     11-22           -0.07
22     11-23           -0.05
23     11-24           -0.17
24     11-25           -0.18
25     11-26           -0.16
26     11-27           -0.04
27     11-28           -0.16
28     11-29           -0.08
29     11-30           -0.08

In [64]:
merged_df = pd.merge(df_low, df_haj, on='month_day')
merged_df = pd.merge(merged_df, df_srednia, on='month_day')

merged_df = pd.merge(merged_df, df_mediana, on='month_day')

In [82]:
merged_df

,month_day,cena_flaja_low,cena_flaja_haj,cena_flaja_srednia,cena_flaja_mediana
0,11-01,-0.13,0.46,0.035714,-0.020000
1,11-02,-0.08,0.46,0.117143,0.030000
2,11-03,-0.10,0.45,0.102857,0.020000
3,11-04,-0.09,0.43,0.072500,-0.010000
4,11-05,-0.08,0.18,0.010000,-0.020000
5,11-06,-0.09,0.09,-0.004286,-0.020000
6,11-07,-0.10,0.37,0.031429,0.000000
7,11-08,-0.12,0.37,0.020000,-0.020000
8,11-09,-0.14,0.33,0.041429,0.010000
9,11-10,-0.14,0.29,0.010000,-0.010000
10,11-11,-0.17,0.30,0.006250,-0.005000
11,11-12,-0.15,0.14,-0.004286,-0.010000
12,11-13,-0.09,0.24,0.032857,0.000000
13,11-14,-0.17,0.32,-0.004286,-0.020000
14,11-15,-0.20,0.32,-0.012857,-0.020000
15,11-16,-0.14,0.45,0.074286,0.030000
16,11-17,-0.14,0.41,0.041429,-0.020000
17,11-18,-0.13,0.45,0.046250,-0.020000
18,11-19,-0.12,0.13,0.004286,-0.010000
19,11-20,-0.14,0.20,0.024286,0.000000
20,11-21,-0.15,0.45,0.025714,-0.010000
21,11-22,-0.07,0.39,0.048333,-0.015000
22,11-23,-0.05,0.39,0.108333,0.045000
23,11-24,-0.17,0.27,0.042000,0.040000
24,11-25,-0.18,0.40,0.075714,-0.020000
25,11-26,-0.16,0.07,-0.036000,-0.030000
26,11-27,-0.04,0.27,0.065000,0.025000
27,11-28,-0.16,0.42,0.050000,0.020000
28,11-29,-0.08,0.46,0.064286,0.000000
29,11-30,-0.08,0.43,0.124286,0.100000
31,Åšrednia,NaN,NaN,0.078237,0.002581

In [77]:
nowy_wiersz_srednia = {
    'month_day': 'Åšrednia',
    'cena_flaja_srednia': merged_df['cena_flaja_srednia'].mean(),
    'cena_flaja_mediana': merged_df['cena_flaja_mediana'].mean()
}

# Dodanie nowego wiersza do DataFrame
merged_df = merged_df.append(nowy_wiersz_srednia, ignore_index=True)

<ipython-input-77-ea03d59f83ae>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_df = merged_df.append(nowy_wiersz_srednia, ignore_index=True)

In [83]:
merged_df.round(2)

,month_day,cena_flaja_low,cena_flaja_haj,cena_flaja_srednia,cena_flaja_mediana
0,11-01,-0.13,0.46,0.04,-0.02
1,11-02,-0.08,0.46,0.12,0.03
2,11-03,-0.10,0.45,0.10,0.02
3,11-04,-0.09,0.43,0.07,-0.01
4,11-05,-0.08,0.18,0.01,-0.02
5,11-06,-0.09,0.09,-0.00,-0.02
6,11-07,-0.10,0.37,0.03,0.00
7,11-08,-0.12,0.37,0.02,-0.02
8,11-09,-0.14,0.33,0.04,0.01
9,11-10,-0.14,0.29,0.01,-0.01
10,11-11,-0.17,0.30,0.01,-0.00
11,11-12,-0.15,0.14,-0.00,-0.01
12,11-13,-0.09,0.24,0.03,0.00
13,11-14,-0.17,0.32,-0.00,-0.02
14,11-15,-0.20,0.32,-0.01,-0.02
15,11-16,-0.14,0.45,0.07,0.03
16,11-17,-0.14,0.41,0.04,-0.02
17,11-18,-0.13,0.45,0.05,-0.02
18,11-19,-0.12,0.13,0.00,-0.01
19,11-20,-0.14,0.20,0.02,0.00
20,11-21,-0.15,0.45,0.03,-0.01
21,11-22,-0.07,0.39,0.05,-0.02
22,11-23,-0.05,0.39,0.11,0.05
23,11-24,-0.17,0.27,0.04,0.04
24,11-25,-0.18,0.40,0.08,-0.02
25,11-26,-0.16,0.07,-0.04,-0.03
26,11-27,-0.04,0.27,0.06,0.02
27,11-28,-0.16,0.42,0.05,0.02
28,11-29,-0.08,0.46,0.06,0.00
29,11-30,-0.08,0.43,0.12,0.10
31,Åšrednia,NaN,NaN,0.08,0.00