<a href="https://colab.research.google.com/github/tomektom10/dataScienceBootCamp/blob/main/Untitled6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("kkkkkkkk.xlsx")

In [3]:
df.drop('Unnamed: 10', axis=1, inplace=True)
df.drop('Unnamed: 11', axis=1, inplace=True)
df['Profit_Loss'] = df['Bilans'] - df['Price SK (EUR/MWh)']

In [7]:
df.columns

Index(['Delivery day', 'Period number', 'Period',
       'Traded Price Average (EUR/MWh)',
       'Weighted average price of all trades (EUR/MWh)',
       'Minimal price (EUR/MWh)', 'Maximal price (EUR/MWh)',
       'Last price (EUR/MWh)', 'Bilans', 'Price SK (EUR/MWh)', 'Profit_Loss'],
      dtype='object')

In [4]:
df

,Delivery day,Period number,Period,Traded Price Average (EUR/MWh),Weighted average price of all trades (EUR/MWh),Minimal price (EUR/MWh),Maximal price (EUR/MWh),Last price (EUR/MWh),Bilans,Price SK (EUR/MWh),Profit_Loss
0,2023-01-01,1.0,00:00 - 01:00,19.40,18.93,7.00,30.26,19.00,-5.0000,20.26,-25.2600
1,2023-01-01,2.0,01:00 - 02:00,3.07,1.35,0.30,10.33,0.30,-2.2525,0.33,-2.5825
2,2023-01-01,3.0,02:00 - 03:00,4.18,2.05,0.50,10.50,0.50,-5.0000,0.50,-5.5000
3,2023-01-01,4.0,03:00 - 04:00,4.40,2.26,0.00,10.50,0.00,-5.0000,0.50,-5.5000
4,2023-01-01,5.0,04:00 - 05:00,5.08,3.12,0.00,10.10,0.00,-5.0000,0.10,-5.1000
...,...,...,...,...,...,...,...,...,...,...,...
8756,2023-12-31,21.0,20:00 - 21:00,26.51,27.36,14.23,48.00,15.00,-5.0000,24.04,-29.0400
8757,2023-12-31,22.0,21:00 - 22:00,17.22,18.78,3.87,45.00,5.00,-5.0000,9.85,-14.8500
8758,2023-12-31,23.0,22:00 - 23:00,16.81,19.80,4.23,55.00,5.00,-5.0000,10.68,-15.6800
8759,2023-12-31,24.0,23:00 - 00:00,13.72,18.38,6.64,35.11,8.59,-5.0000,15.11,-20.1100
8760,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:

# Extract the top 30 rows with the highest 'Profit_Loss' values
top_30_profits = df.nlargest(30, 'Profit_Loss')

top_30_profits[['Delivery day', 'Period number', 'Price SK (EUR/MWh)', "Bilans" ,'Profit_Loss']]

     Delivery day  Period number  Price SK (EUR/MWh)    Bilans  Profit_Loss
6091   2023-09-11           20.0              444.02  666.0300     222.0100
6092   2023-09-11           21.0              394.00  591.0000     197.0000
711    2023-01-30           16.0              297.93  446.8950     148.9650
709    2023-01-30           14.0              285.94  428.9100     142.9700
705    2023-01-30           10.0              284.62  426.9300     142.3100
714    2023-01-30           19.0              277.81  416.7150     138.9050
92     2023-01-04           21.0              276.56  414.8400     138.2800
703    2023-01-30            8.0              276.40  414.6000     138.2000
88     2023-01-04           17.0              275.34  413.0100     137.6700
6115   2023-09-12           20.0              271.13  406.6950     135.5650
706    2023-01-30           11.0              268.16  402.2400     134.0800
708    2023-01-30           13.0              267.40  401.1000     133.7000
3880   2023-06-11           17.0               -0.10  132.0000     132.1000
3874   2023-06-11           11.0                0.02  132.0000     131.9800
712    2023-01-30           17.0              262.09  393.1350     131.0450
5054   2023-07-30           15.0                1.00  131.5000     130.5000
3206   2023-05-14           15.0                0.16  130.4950     130.3350
5050   2023-07-30           11.0                0.03  130.0000     129.9700
4696   2023-07-15           17.0                1.65  131.5000     129.8500
3207   2023-05-14           16.0                1.78  130.7475     128.9675
2005   2023-03-25           14.0                1.75  130.5000     128.7500
3205   2023-05-14           14.0                1.85  130.2475     128.3975
707    2023-01-30           12.0              256.70  385.0500     128.3500
3182   2023-05-13           15.0                2.90  131.0000     128.1000
6265   2023-09-19            2.0                2.97  130.5000     127.5300
5258   2023-08-08            3.0               -1.45  126.0000     127.4500
560    2023-01-24            9.0              254.81  382.2150     127.4050
5138   2023-08-03            3.0                3.08  130.0000     126.9200
5053   2023-07-30           14.0                3.67  130.5000     126.8300
2004   2023-03-25           13.0                5.00  130.5000     125.5000